### ISSUE TITLE
Where do i specifiy "githubArtifactName" within package.json?

### ISSUE THREAD

**Issue by sidneys** [electron-userland/electron-builder#1390]
* **Version**: 15.6.2

* **Target**: win32

None of the locations i tried (within `package.json`) lets me add a custom `githubArtifactName` (or any properties from `latest.yml`, like `path`), my config never passes validation. 

Where can i add these custom `versionInfo`properties?

#### my package.json

 ```json
...
 },
  "build": {
    "win": {
      "icon": "./icons/win32/icon.ico",
      "target": [
        "nsis"
      ]
    },
    "nsis": {
      "artifactName": "${name}-setup-${version}.${ext}",
      "deleteAppDataOnUninstall": true,
      "oneClick": false,
      "runAfterFinish": false
    }
  }
...
```

Thanks, @develar !

**Comment by develar** [comment]
You cannot add custom `githubArtifactName`. Github has weird file name rules and electron-builder computes it for you.

It seems you want to use GitHub urls as generic provider urls, right?

**Comment by sidneys** [comment]
@develar 

Thanks for the response! Nope, the problem is that my ´artifactName´ is correctly formatted `${name}-setup-${version}.${ext}`, and is uploaded as such to GitHub, while `githubArtifactName` is still incorrectly formatted as `${name}-Setup-${version}.${ext}` (note the uppercase "Setup") and does not recognize the renamed actual artifact name in the generated `latest.yml` (see below):

#### my latest.yml
```yml
version: 4.1.5
releaseDate: '2017-03-21T08:46:38.280Z'
githubArtifactName: pb-for-desktop-setup-4.1.5.exe
path: pb-for-desktop-setup-4.1.5.exe
sha2: 8958bb0ffe95194077cc58c2e6f1a15835275a7b84ed1c4c91a13cf9989f0677
```
