### ISSUE TITLE
electron-builder ignores directories named `build` in `files:` configuration

### ISSUE THREAD

**Issue by mikew** [electron-userland/electron-builder#1401]
* **Version**: electron-builder@16.2.1

* **Target**: Any

`create-react-app` by default outputs to a directory named `build/`. With a `electron-builder.yml` structured like so:

```yml
files:
  - electron/
  - node_modules/
  - build/
```

The `build/` directory is excluded. Most likely due to some internal logic.

It's also unfortunate that setting `files:` really means `asarFiles`, and setting it manually overwrites the default values (IE you won't get `node_modules/`), and that there's no equivalent `extraAsarFiles`.

**Comment by develar** [comment]
> It's also unfortunate that setting files: really means asarFiles, and setting it manually overwrites the default values (IE you won't get node_modules/),

You just want to _append_ files, right?

**Comment by develar** [comment]
Please change [directories.output](https://github.com/electron-userland/electron-builder/wiki/Developer-API#MetadataDirectories-output) from default `build` to another value. In this case you also don't need to add `build` to `files`

**Comment by walknwind** [comment]
I don't see how @develar's suggestion helps this issue. setting `directories.output`, say, in package.json like this:

```
{
  "build": {
    "directories": {
      "output": "custom-output"
    }
  }
}
```

changes electron-builder's output folder from the default `dist/` to `custom-output/`. It doesn't seem to affect the OP's issue (and my issue at the moment) at all. Might I be missing something?

**Comment by mikew** [comment]
You're not, this issue was closed without resolution. 

Here's the `electron-builder.yml` I ended up with:

```yaml
publish:
  provider: s3
  bucket: xxx
  path: xxx

npmRebuild: false

directories:
  buildResources: electron-builder

files:
  - electron/
  - node_modules/
  - build/
  - "!node_modules/.cache/"
  - "!**/*.map"
```
