### ISSUE TITLE
Indicator icons are broken in snaps of Electron applications.

### ISSUE THREAD

**Issue by flexiondotorg** [electron-userland/electron-builder#1452]
Which version of electron-builder are you using?
  * **Version**: 16.8.2

What target are you building for?
* **Target**: Linux. snap

When building snaps for Linux the Indicator icons (if supported by the applications) have broken image icons. This can be resolved by coercing the `TMPDIR` path for Chromium Framework/Electron to ensure `libappindicator` has readable resources. For example:

```
apps:
  example:
    # Correct the TMPDIR path for Chromium Framework/Electron to
    # ensure libappindicator has readable resources.
    command: env TMPDIR=$XDG_RUNTIME_DIR ${SNAP}/bin/desktop-launch $SNAP/usr/bin/example
```

Coercing TMPDIR is a safe default for all snapped Electron applications.
