### ISSUE TITLE
Wrong file being uploaded to Github

### ISSUE THREAD

**Issue by djalmaaraujo** [electron-userland/electron-builder#1526]
* **Version**: 16.8.3

* **Target**: macOS and Win

For some reason, after the build, electron-builder uploads the wrong artifactName to github.

Log:
```bash
Publishing to Github (owner: djalmaaraujo, project: my-repo, version: 3.0.0)
Uploading my-repo-setup-3.0.0.exe to GitHub
```

Here's how my artifact name is:

```yml
mac:
  category: public.app-category.productivity
  artifactName: my-repo-${version}-${env.NODE_ENV}-mac.${ext}
  target:
    - zip
  publish:
    - github

files:
  - app/**/*
  - node_modules/**/*
  - package.json
  - "!env.json"

extraResources:
  - 
    from: config/dev/env.json
    to: env.json

win:
  target: "nsis"
  artifactName: my-repo-${version}-${env.NODE_ENV}.${ext}
  publish:
    - github

nsis:
  artifactName: my-repo-${version}-${env.NODE_ENV}.${ext}

```

Running:
```bash
cross-env NODE_ENV='dev' build -w --config=config/dev/electron-builder.yml --x64 --ia32
```

I am generating this file:

- dist\dev\my-repo-3.0.0-dev.exe

But for some reason, only this ```my-repo-setup-3.0.0.exe``` is uploaded.

Any idea on how to upload all my files?
