### ISSUE TITLE
Additional file in electron-build dmg not working

### ISSUE THREAD

**Issue by withintheruins14** [electron-userland/electron-builder#1613]
I would like to enclose a js file in the dmg created by electron builder. When I open the dmg, I am expecting to see 3 things: the app, a link to the applications folder, and my javascript file. I am using a electron-builder.yml file to do this, and I am adding this file to the dmgContents section. Here is the snippet from my electron-builder.yml

```
dmg:
  contents:
    - type: link
      path: /Applications
      x: 438
      y: 275
    - type: file
      x: 192
      y: 275
    - type: file
      x: 292
      y: 275
      path: 'build/plugins/photoshop-save.js'
```

Should I expect something like this to work? I am confident the js file is in my build folder, but nothing has worked. I have also tried the extraFiles and extraResources options in combination with dmgContents. In that case, my path value was just the filename. Thanks! Phillip
