### ISSUE TITLE
Crash during build with 19.0.0

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#1647]
* **Version**: 19.0.0

I'm using:
- Windows 10 Pro x64
- Node 8.1.0

* **Target**: Windows ia32

Following error occurs:

```
> build --ia32

electron-builder 19.0.0
Using electron-builder.yml configuration file
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for win32 ia32 using electron 1.7.3 to dist\win-ia32-unpacked
TypeError: Cannot read property 'add' of undefined
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\readInstalled.ts:187:7
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at dependencies (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\readInstalled.js:156:22)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\asarUtil.ts:67:9
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-util\src\fs.ts:70:60
From previous event:
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-util\src\fs.ts:65:10
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-util\src\fs.ts:62:51
    at Generator.next (<anonymous>)
    at go$readdir$cb (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\graceful-fs\graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at walk (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder-util\out\fs.js:110:22)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\asarUtil.ts:61:17
    at Generator.next (<anonymous>)
From previous event:
    at AsarPackager.pack (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\asarUtil.js:187:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\platformPackager.ts:197:140
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at WinPackager.doPack (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\platformPackager.js:259:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\platformPackager.ts:104:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\platformPackager.js:160:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\packager.ts:270:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\packager.js:388:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\packager.ts:183:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\packager.js:283:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\builder.ts:199:33
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\builder.js:70:21)
    at Object.<anonymous> (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\cli\build-cli.js:71:41)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

My `electron-builder.yml`:

```
appId: media.presenter
compression: maximum
npmRebuild: false

files:
  - "**/*"
  - "!{app,build,electron,mobile,theme,uploads,util,dist,dist-app/aot,dist-app/app.bundle.js,dist-app/dependencies/shim.min.js,dist-app/dependencies/classList.min.js,dist-app/dependencies/web-animations.min.js,favicon.ico,index.html,index-aot.html,index.js,index-aot.js,index-electron.js,index.bundle.js,systemjs.config.js}"
  - "!**/*.{ts,scss,map,md,csv,wrapped}"
  - "!**/*.{o,hprof,orig,pyc,pyo,rbc}"
  - "!**/._*"
  - "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,thumbs.db,.gitignore,.gitattributes,.editorconfig,.flowconfig,.yarn-metadata.json,.idea,appveyor.yml,.travis.yml,circle.yml,npm-debug.log,.nyc_output,yarn.lock,.yarn-integrity}"

publish:
  provider: generic
  url: "https://redacted/${os}"

win:
  target:
    - nsis

mac:
  target:
    - dmg

nsis:
  deleteAppDataOnUninstall: true
```

Edit: I just tested 18.8.1, that version works fine.
