### ISSUE TITLE
githubArtifactName in latet-mac.yml

### ISSUE THREAD

**Issue by ert78gb** [electron-userland/electron-builder#1709]
* **Version**: 18.3.0
I tried the latest version, but got #1707 error

* **Target**: MAC

I create the build config with script.
```javascript
let target = '';
let artifactName = 'UHK.Agent-${version}-${os}';

if (process.platform === 'darwin') {
    target = Platform.MAC.createTarget();
    artifactName += '.${ext}';
} else if (process.platform === 'win32') {
    target = Platform.WINDOWS.createTarget();
    artifactName += '-${arch}.${ext}';
} else if (process.platform === 'linux') {
    target = Platform.LINUX.createTarget();
    artifactName += '.${ext}';
} else {
    console.error(`I dunno how to publish a release for ${process.platform} :(`);
    process.exit(1);
}

if (process.platform === 'darwin') {
    // TODO: Remove comment when macOS certificates boughted and exported
    //require('./setup-macos-keychain').registerKeyChain();
}

let version = '';
if (TEST_BUILD || gitTag) {
    version = gitTag;

    builder.build({
        dir: true,
        targets: target,
        appMetadata: {
            main: 'electron-main.js',
            name: 'UHK Agent',
            author: {
                name: 'Ultimate Gadget Laboratories'
            },
            version: require('../package.json').version
        },
        config: {
            directories: {
                app: electron_build_folder
            },
            appId: 'com.ultimategadgetlabs.uhk.agent',
            productName: 'UHK Agent',
            mac: {
                category: 'public.app-category.utilities'
            },
            publish: 'github',
            artifactName,
            files: [
                '**/*'
            ]
        },
    })
        .then(() => {
            console.log('Packing success.');
        })
        .catch((error) => {
            console.error(`${error}`);
            process.exit(1);
        })
}
```
lates-mac.yml
```yaml
version: 0.9.0
releaseDate: '2017-06-19T19:11:46.663Z'
githubArtifactName: UHK Agent-0.9.0-mac.zip
path: UHK.Agent-0.9.0-mac.zip
sha512: >-
  1e9bf1fb6a88c0fb3cfb7e37c801ae55ff0ba63b25e17caad46614d1216c071990f3667f24e739b58c47f362f7764acdb2222f7a236d21c601b6d6568945f835

```
in the generated file the githubArtifactName contains space and the updater not download it 404 error the HTTP response

How could I change the githubArtifactName??? It is bug or I forgot something?

https://github.com/ert78gb/agent/tree/issue-250-update-dialog
The build script path is script/release.js
and the generated yml https://github.com/UltimateHackingKeyboard/agent/releases/download/v1.0.0/latest-mac.yml
Thx
