### ISSUE TITLE
Support channels for Github provider

### ISSUE THREAD

**Issue by MaKleSoft** [electron-userland/electron-builder#1722]
* **Version**: 19.6.3
* **Target**: win, mac

When using the github provider, electron builder always generates `latest.yml` and `latest-mac.yml`, even for alpha/beta releases.

I dug into the source code and the problem seems to be this part: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/publish/PublishManager.ts#L476

The channel is correctly extracted from the file name but not assigned to the options object for any provider other than `generic`. However, looking at the source code of `electron-updater` it looks like the Github provider should support channels as well?

**Comment by MaKleSoft** [comment]
Ok so it seems that as of now, `GithubProvider` is always looking for `latest.yml` regardless of the actual channel: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/GitHubProvider.ts#L62

Does this mean channels are simply not supported for the Github provider at this point? Is this an oversight or intentional? Seems like it would be trivial to implement this?

The whole channel implementation seems kind of broken imo. Why do we need separate channel files in the first place? Or why separate files for all platforms for that matter? Wouldn't it be easier to simply have one `latest.yml` and have all the information in there? Something like:

```yaml
version: 2.0.0-alpha.1
releaseDate: '2017-06-21T20:25:04.622Z'
win:
  githubArtifactName: padlock-setup-2.0.0-alpha.1.exe
  path: Padlock Setup 2.0.0-alpha.1.exe
  sha512: ...
  sha2: ...
mac:
  githubArtifactName: padlock-2.0.0-alpha.1-mac.zip
  path: Padlock-2.0.0-alpha.1-mac.zip
  sha512: ...
```

**Comment by MaKleSoft** [comment]
Another problem is that for the generic provider, information about previous releases is lost when `latest.yml` is updated which is a problem if you want to roll back a release for example. Imo it would be more appropriate to have a `releases.yml`, like so:

```yaml
- version: 2.0.0-alpha.1
  releaseDate: ...
  win:
    githubArtifactName: padlock-setup-2.0.0-alpha.1.exe
    path: Padlock Setup 2.0.0-alpha.1.exe
    sha512: ...
    sha2: ...
  mac: ...
- version: 1.5.0
  releaseDate: ...
  win:
    githubArtifactName: padlock-setup-1.5.0.exe
    path: Padlock Setup 1.5.0.exe
    sha512: ...
    sha2: ...
  mac: ...
```
It is then trivial for the client to download the `releases.yml` file and figure out the latest appropriate version for a given channel. For managing the `releases.yml` file, I see two options:

1. Explicitly store the state in a `releases.yml` file that is commited to source control. This file is augmented on every release.
2. Generate the file from the git meta data. Storing artifact-related information like checksums and file names could be a challenge, but we might be able to use [git-notes](https://www.kernel.org/pub/software/scm/git/docs/git-notes.html) for that.

I like option 2, because we could use the same logic to extract all necessary release information directly from a github repo. That would mean that no `latest.yml` or `releases.yml` would be required for the Github provider at all!
