### ISSUE TITLE
19.8.0 broke ignoring folders in electron-builder.yml

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#1741]
* **Version**: 19.8.0 to 19.9.1

* **Target**: Windows x86 NSIS

Folders don't get ignored since version 19.8.0. Version 19.7.3 works fine.

My electron-builder.yml

```
appId: media.presenter
compression: maximum
npmRebuild: false
asar: false

files:
  - "**/*"
  - "!{app,build,electron,mobile,theme,uploads,util,dist,dist-app/aot,dist-app/app.bundle.js,dist-app/dependencies/shim.min.js,dist-app/dependencies/classList.min.js,dist-app/dependencies/web-animations.min.js,main.js,main-aot.js,favicon.ico,index.html,index-aot.html,index-cordova.html,index.js,index-aot.js,index-electron.js,index.bundle.js,systemjs.config.js,systemjs-angular-loader.js,package-lock.json}"
  - "!*config*.json"
  - "!**/*.{ts,scss,map,md,csv,wrapped}"
  - "!**/*.{o,hprof,orig,pyc,pyo,rbc}"
  - "!**/._*"
  - "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,thumbs.db,.gitignore,.gitattributes,.editorconfig,.flowconfig,.yarn-metadata.json,.idea,appveyor.yml,.travis.yml,circle.yml,npm-debug.log,.nyc_output,yarn.lock,.yarn-integrity}"

publish:
  provider: generic
  url: "https://[redacted]/${os}"

win:
  target:
    - nsis

mac:
  target:
    - dmg

nsis:
  deleteAppDataOnUninstall: true

```

I set `asar: false` to see if folders are being excluded properly.

In this config the app, build, electron, mobile... etc. folders are not ignored. Files on the other hand like dist-app/app.bundle.js are ignored.
