### ISSUE TITLE
Document how to build for all platforms on Travis

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-builder#1751]
* **Version**: 19.8.0
* **Target**: macOS, Linux, Windows

[Version 19.6.0](https://github.com/electron-userland/electron-builder/releases/tag/v19.6.0) introduced support for building Windows target on macOS. It's awesome that I can drop AppVeyor, but would be nice if it was documented how to set this up on Travis.

For example, can I do `electron-builder -mwl` in a `dist` npm run script and will `electron-builder` ignore building the Windows and macOS apps when running in the Linux image on Travis and ignore building the Linux app on the macOS image on Travis, or do I need a complicated `.travis.yml`? 

Would be nice if electron-builder had a simple mode for this. I can imagine this would be the most common use-case.

**Comment by sindresorhus** [comment]
Actually, do I even need the Linux image, can I just build for all platforms on the Travis macOS image?

**Comment by develar** [comment]
If you don't have native deps, don't need to build rpm, snap, appx — you can use only Travis macOS. Nothing is required to setup — just build -mwl

**Comment by develar** [comment]
Example will be provided as soon as I will create prebuilt for keytar :)

**Comment by develar** [comment]
TODO: cache build matrix.

**Comment by develar** [comment]
I don't like "one travis OS to build all" Reason — Travis OS X is slow. See https://travis-ci.org/develar/onshape-desktop-shell  7m (macOS) vs 3m (linux) Well, to be considered.

**Comment by sindresorhus** [comment]
@develar Doesn't matter for me whether it's 3 minutes or 10. I'll be doing something else in the meantime anyways.

**Comment by develar** [comment]
```yml
osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

addons:
  apt:
    packages:
      - libsecret-1-0

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xvz && mv dist $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release -- --mac --win; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
```
