### ISSUE TITLE
File macro expansion does not work in mac.binaries configuration 

### ISSUE THREAD

**Issue by pronebird** [electron-userland/electron-builder#1791]
* **Version**:  19.12

* **Target**:  macOS

```
mac:
  target:
    - dmg
  binaries:
   - dist/${productName}/Contents/Resources/duck
```

`${productName}` is not being expanded when passed to codesign, results in codesign error.
