### ISSUE TITLE
NSIS template translation lang code with region

### ISSUE THREAD

**Issue by zh99998** [electron-userland/electron-builder#1904]
* **Version**: 19.19.1

* **Target**: NSIS

currently `messages.yml` and `boringMessages.yml` using lang without region as key.
it's awful. since different locale will share same lang code but different region code.
such as bundled `zh_CN` and `zh_TW`.

if add a `zh` key in `boringMessages.yml`
```yaml
chooseInstallationOptions:
  en: Choose Installation Options
  de: Installationsoption wählen
  ru: Выберите опции установки
  sk: Vyberte možnosti inštalácie
  zh: 选择安装选项
```

It will only shown in `zh-TW` Windows system. on `zh-CN` (Chinese-Simplified) Windows, It will show **English**

because in https://github.com/electron-userland/electron-builder/blob/83da89a6f06bb97fac6e79b8aba75bc43d6c2d9b/packages/electron-builder/src/targets/license.ts#L5-L10, `zh_TW` presents later than `zh-CN`, so it overrides in langToLangWithRegion.

I think this is a bug. now I can't find anyway to let Chinese-Simplified Windows show custom Chinese message.

currently it doesn't allow specific `zh_CN` as key, will throw.

in https://github.com/electron-userland/electron-builder/blob/83da89a6f06bb97fac6e79b8aba75bc43d6c2d9b/packages/electron-builder/src/targets/nsis/nsisUtil.ts#L93 only allow specific lang code
