### ISSUE TITLE
Travis NSIS EPIPE error

### ISSUE THREAD

**Issue by ghost** [electron-userland/electron-builder#1978]
* **Version**: 19.24.1

* **Target**: Windows, Linux | ia32, x64

I have the following .travis.yml, and I get the following error in the Travis log.

```
dist: trusty
sudo: required

language: node_js
node_js: '8'

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux

cache:
  directories:
    - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"
    - "$HOME/.npm/_prebuilds"

addons:
  apt:
    packages:
    - libsecret-1-0

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-linux-amd64-2.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xvz && mv dist $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y && sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list && sudo apt-get update && sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono wine1.8 gcc-multilib g++-multilib icnsutils graphicsmagick xz-utils

install:
  - yarn

script:
  - yarn dist --linux --win --ia32 --x64

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
```

```
Building NSIS installer
  Packaging NSIS installer for arch x64
  Packaging NSIS installer for arch ia32
Downloading nsis-3.0.1.13, please wait
Downloading nsis-resources-3.1.0, please wait
Error: write EPIPE
    at _errnoException (util.js:1041:11)
    at WriteWrap.afterWrite (net.js:858:14)
error Command failed with exit code 1.
```
