### ISSUE TITLE
Resource busy (elevate.exe)

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#2123]
* **Version**: 19.31.3

* **Target**: (ia32 & x64) & (NSIS & NSIS-Web)

Since 19.31.x I sometimes get a resource busy message for `elevate.exe`.

Most of the times the error fixes itself by re-running `build --x64 --ia32` again. This error is hard to debug as it happens randomly.

```
> media-presenter@2.4.0 dist:n C:\Users\johann.rekowski\Documents\Apps\Media-Presenter
> build --x64 --ia32

electron-builder 19.31.3
Using electron-builder.yml configuration file
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for win32 x64 using electron 1.7.8 to dist\win-unpacked
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for win32 ia32 using electron 1.7.8 to dist\win-ia32-unpacked
Building nsis installer (x64 and ia32)
Building nsis-web installer (x64 and ia32)
Error: EBUSY: resource busy or locked, copyfile 'C:\Users\johann.rekowski\AppData\Local\electron-builder\cache\nsis\nsis-3.0.2.1\elevate.exe' -> 'C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\dist\win-unpacked\resources\elevate.exe'
    at copyOrLinkFile (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\builder-util\src\fs.ts:186:5)
    at then (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\builder-util\src\fs.ts:131:95)
From previous event:
    at copyFile (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\builder-util\src\fs.ts:131:84)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\targets\nsis\nsis.ts:73:13
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at WebInstallerTarget.buildAppPackage (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\targets\nsis\nsis.js:192:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\targets\nsis\nsisUtil.ts:20:28
    at Generator.next (<anonymous>)
From previous event:
    at AppPackageHelper.packArch (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\targets\nsis\nsisUtil.js:60:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\targets\nsis\nsis.ts:180:51
    at Generator.next (<anonymous>)
From previous event:
    at default.map (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\targets\nsis\nsis.js:289:37)
From previous event:
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\targets\nsis\nsis.ts:179:29
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at WebInstallerTarget.buildInstaller (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\targets\nsis\nsis.js:325:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\targets\nsis\nsis.ts:105:18
    at Generator.next (<anonymous>)
From previous event:
    at WebInstallerTarget.finishBuild (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\targets\nsis\nsis.js:207:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\packager.ts:268:36
From previous event:
    at Packager.doBuild (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\packager.js:344:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\packager.js:263:11)
    at C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\builder.ts:286:40
    at Generator.next (<anonymous>)
    at build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\builder.js:69:21)
    at loadEnv.then (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\src\cli\cli.ts:49:4)
From previous event:
    at build (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\builder.js:69:21)
    at loadEnv.then (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\cli\cli.js:155:79)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Object.args [as handler] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\cli\cli.js:155:68)
    at Object.runCommand (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\yargs\lib\command.js:226:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\yargs\yargs.js:998:24)
    at Object.get [as argv] (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\yargs\yargs.js:912:21)    at Object.<anonymous> (C:\Users\johann.rekowski\Documents\Apps\Media-Presenter\node_modules\electron-builder\out\cli\cli.js:151:418)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! media-presenter@2.4.0 dist:n: `build --x64 --ia32`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the media-presenter@2.4.0 dist:n script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\johann.rekowski\AppData\Roaming\npm-cache\_logs\2017-09-27T14_33_44_238Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! media-presenter@2.4.0 dist: `npm run compile:electronaot && npm run dist:n`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the media-presenter@2.4.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\johann.rekowski\AppData\Roaming\npm-cache\_logs\2017-09-27T14_33_44_254Z-debug.log
```

My config:

```
appId: media.presenter
copyright: "© 2016 - 2017 MEGO GmbH"
compression: maximum
npmRebuild: false

files:
  - "**/*"
  - "!{app,build,electron,mobile,theme,videos,util,dist,dist-app/aot,dist-app/app.bundle.js,dist-app/dependencies/shim.min.js,dist-app/dependencies/classList.min.js,dist-app/dependencies/web-animations.min.js,main.js,main-aot.js,favicon.ico,index.html,index-aot.html,index-cordova.html,index.js,index-aot.js,index-electron.js,index.bundle.js,systemjs.config.js,systemjs-angular-loader.js,package-lock.json}"
  - "!*config*.json"
  - "!**/*.{ts,scss,map,md,csv,wrapped}"
  - "!**/*.{o,hprof,orig,pyc,pyo,rbc}"
  - "!**/._*"
  - "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,thumbs.db,.gitignore,.gitattributes,.editorconfig,.flowconfig,.yarn-metadata.json,.idea,appveyor.yml,.travis.yml,circle.yml,npm-debug.log,.nyc_output,yarn.lock,.yarn-integrity}"

publish:
  provider: generic
  url: "https://[redacted]/${os}"

win:
  target:
    - nsis
    - nsis-web

mac:
  target:
    - dmg

nsis:
  differentialPackage: true
  deleteAppDataOnUninstall: true
```
