### ISSUE TITLE
Deprecation message for releaseType is always shown

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#2126]
* **Version**: 19.32.0

* **Target**: (ia32 & x64) & (NSIS & NSIS-Web)

I get a deprecation message for GitHub publish options, even though I'm not using GitHub for publishing.

```
> media-presenter@2.4.0 dist:n C:\Users\johann.rekowski\Documents\Apps\Media-Presenter
> build --x64 --ia32

⚠️  --draft and --prerelease is deprecated, please set releaseType (http://electron.build/configuration/publish#GithubOptions-releaseType) in the GitHub publish options instead
electron-builder 19.32.0
Using electron-builder.yml configuration file
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for win32 x64 using electron 1.7.8 to dist\win-unpacked
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for win32 ia32 using electron 1.7.8 to dist\win-ia32-unpacked
Building nsis installer (x64 and ia32)
Building nsis-web installer (x64 and ia32)
```

My config:

```
appId: media.presenter
copyright: "© 2016 - 2017 MEGO GmbH"
compression: maximum
npmRebuild: false

files:
  - "**/*"
  - "!{app,build,electron,mobile,theme,videos,util,dist,dist-app/aot,dist-app/app.bundle.js,dist-app/dependencies/shim.min.js,dist-app/dependencies/classList.min.js,dist-app/dependencies/web-animations.min.js,main.js,main-aot.js,favicon.ico,index.html,index-aot.html,index-cordova.html,index.js,index-aot.js,index-electron.js,index.bundle.js,systemjs.config.js,systemjs-angular-loader.js,package-lock.json}"
  - "!*config*.json"
  - "!**/*.{ts,scss,map,md,csv,wrapped}"
  - "!**/*.{o,hprof,orig,pyc,pyo,rbc}"
  - "!**/._*"
  - "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,thumbs.db,.gitignore,.gitattributes,.editorconfig,.flowconfig,.yarn-metadata.json,.idea,appveyor.yml,.travis.yml,circle.yml,npm-debug.log,.nyc_output,yarn.lock,.yarn-integrity}"

publish:
  provider: generic
  url: "https://[redacted]/${os}"

win:
  target:
    - nsis
    - nsis-web

mac:
  target:
    - dmg

nsis:
  differentialPackage: true
  deleteAppDataOnUninstall: true
```
