### ISSUE TITLE
Uncaught Exception: Error: Cannot find module '@paulcbetts/system-idle-time'

### ISSUE THREAD

**Issue by hovancik** [electron-userland/electron-builder#2135]
* **Version**: electron-builder 19.32.2, electron-builder 19.27.7

* **Target**: Packaging for darwin x64 using electron 1.7.6 to dist/mac, node 7.9.0

After building my app, I get:  

```
Uncaught Exception:
Error: Cannot find module '@paulcbetts/system-idle-time'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/janhovancik/Workspace/hovancik/stretchly/dist/mac/stretchly.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at NaturalBreaksManager.get idleTime [as idleTime] (/Users/janhovancik/Workspace/hovancik/stretchly/dist/mac/stretchly.app/Contents/Resources/app.asar/utils/naturalBreaksManager.js:27:14)
    at Timeout.timer.setInterval [as _onTimeout] (/Users/janhovancik/Workspace/hovancik/stretchly/dist/mac/stretchly.app/Contents/Resources/app.asar/utils/naturalBreaksManager.js:36:26)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

build: 

```
> stretchly@0.11.0 dist /Users/janhovancik/Workspace/hovancik/stretchly
> build --x64 --ia32

electron-builder 19.32.2
No native production dependencies
Packaging for darwin x64 using electron 1.7.6 to dist/mac
```

package.json: 

```
...
"postinstall": "electron-builder install-app-deps",
...
"devDependencies": {

....
    "electron": "^1.7.6",
    "electron-builder": "^19.32.2",
    "electron-rebuild": "^1.6.0",
...
  },
....,
  "dependencies": {
    "@paulcbetts/system-idle-time": "^1.0.4"
  }
}
```
What am I missing?

**Comment by hovancik** [comment]
Forgot to mention: I call it with `require('@paulcbetts/system-idle-time').getIdleTime()`

**Comment by develar** [comment]
Do you use npm or yarn? Or Shrinkwrap?

**Comment by hovancik** [comment]
`npm 5.4.2`

`npm start` works fine

**Comment by develar** [comment]
Well... could you please try remove node_modules and install again?

If still errors, set env DEBUG=electron-builder and attach terminal output file `electron-builder-debug.yml` (in the dist).

BTW electron-rebuild is not required.

**Comment by hovancik** [comment]
How do I run my app without `electron-rebuild `? I am getting without it (and running: `./node_modules/.bin/electron-rebuild`) when `npm start`:  

```
Uncaught Exception:
Error: The module '/Users/janhovancik/Workspace/hovancik/stretchly/node_modules/@paulcbetts/system-idle-time/build/Release/system_idle_time.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/janhovancik/Workspace/hovancik/stretchly/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/janhovancik/Workspace/hovancik/stretchly/node_modules/@paulcbetts/system-idle-time/addon.js:1:192)
```
Anyway, I removed `electron-rebuild`, `node_modules` and still the error. 

```

x64:
  firstOrDefaultFilePatterns:
    - '**/*'
    - '!dist{,/**/*}'
    - '!**/node_modules/**/*.{dll,exe}'
    - >-
      !**/node_modules/*/{README.md,karma.conf.js,.coveralls.yml,readme.markdown,README,readme.md,readme,test,__tests__,tests,powered-test,example,examples}
    - '!**/*.{iml,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,xproj,cc,pdb}'
    - '!**/._*'
    - '!**/electron-builder.{yaml,yml,json,json5,toml}'
    - >-
      !**/{.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,.DS_Store,thumbs.db,.gitignore,.gitkeep,.gitattributes,.npmignore,.idea,.vs,.flowconfig,.jshintrc,.eslintrc,.circleci,.yarn-integrity,.yarn-metadata.json,yarn-error.log,yarn.lock,package-lock.json,npm-debug.log,appveyor.yml,.travis.yml,circle.yml,.nyc_output}
    - '!.editorconfig'
productionDependencies:
  /Users/janhovancik/Workspace/hovancik/stretchly/app: []

```
