### ISSUE TITLE
What version is written to channel.yml?

### ISSUE THREAD

**Issue by thomastvedt** [electron-userland/electron-builder#2232]
* **Version**: 19.35.1

* **Target**: win, S3

In package.json, version is set to "1.0.0". I'm setting environment variable BUILD_NUMBER=56. Standard "artifactName": "${productName}${buildVersion}.${ext}". When I publish to S3 bucket I get the following:
```
electron-builder 19.35.1
Rebuilding native production dependencies for win32:x64
Rebuilding native dependency fsevents
Packaging for win32 x64 using electron 1.7.6 to dist/win-unpacked
Building nsis installer (x64)
Publishing to S3 (bucket: download.mydomain.com)
[====================] 100% 0.0s | App1.0.0.56.exe to S3
[====================] 100% 0.0s | temp.yml to S3
✨  Done in 97.41s.
```

But version number in temp.yml is not 1.0.0.56 as I  wanted, but 1.0.0.. Can I configure electron builder in any way to make it use 1.0.0.56 as version number in channel.yml?

```yml
version: 1.0.0
releaseDate: '2017-10-26T14:30:43.797Z'
path: App1.0.0.56.exe
sha512: >-
 C1njB+H8IxLDBXQIQde9IY50l3tohbLl4rQng7wnOILyR0PuLJURowt/0BQtawFlatAUQjwmV9xxf5G9QW5guQ==
sha2: 463af7e6d469f2f6bfb0d3d86a0dddd1ec88b9014825af368bf091f63bab1c0a
```
