### ISSUE TITLE
Electron-updater confuses Github and S3 when publishing

### ISSUE THREAD

**Issue by leinelissen** [electron-userland/electron-builder#2307]
* **Version**: 19.46.1

* **electron-updater Version**: 2.16.2 

* **Target**: Windows x64 & ia32

I have an electron app which is being built on windows. I have configured electron-builder so that any release is automatically pushed to a S3 bucket and the private Github repository from which it originates. This is my publishing config (package.json):
```
    "publish": [
      {
        "provider": "s3",
        "bucket": "i3-imoconnect"
      },
      {
        "provider": "github"
      }
    ],
```

When I create a new release, all files are generated beautifully - for which I thank you very much. The files are then pushed to both S3 and Github as expected. I was trying out the auto update today, and I noticed that when a new release was pushed, the auto-update did not execute properly. When inspecting the app logs I noted this:

```
Checking for update
Found version 2.0.1 (url: iMO-connect-Setup-2.0.1.exe)
Downloading update from iMO-connect-Setup-2.0.1.exe
Error: Error: Cannot download "https://i3-imoconnect.s3.amazonaws.com/iMO-connect-Setup-2.0.1.exe", status 404: Not Found
```

I checked the s3 bucket and the installer file was there, albeit without the hyphens. While consulting the latest.yml file, I noted how the url included hyphens but the path did not, as such:

```
version: 2.0.1
files:
  - url: iMO-connect-Setup-2.0.1.exe
    sha512: g9qxbwwMc5+Rp8vKhKag9TghXqIeOpQvWghGp5WsOLSSrczo3WmJVXfP/K+UvIJSauykHOkvj31o7Z3z8f5k9w==
path: iMO Connect Setup 2.0.1.exe
sha512: g9qxbwwMc5+Rp8vKhKag9TghXqIeOpQvWghGp5WsOLSSrczo3WmJVXfP/K+UvIJSauykHOkvj31o7Z3z8f5k9w==
sha2: fb4b20ea685f108ba769da1fa60fe3650c5e1392cff4acb46f2d71e69ebd763f
releaseDate: '2017-11-16T17:08:40.269Z'
```

However, the release that was uploaded to Github did include hyphens in its filename. In order to test this, I removed Github as a publishing provider, and re-run the release schedule. When it was complete, the auto-update function ran as expected:

```
Checking for update
Found version 2.0.1 (url: iMO Connect Setup 2.0.1.exe)
Downloading update from iMO Connect Setup 2.0.1.exe
New version 2.0.1 has been downloaded to C:\Users\Lei\AppData\Local\Temp\up-S3Ou8B\iMO%20Connect%20Setup%202.0.1.exe
Auto install update on quit
```

My theory is that for some reason Github will not allow spaces in its filenames, and thus the filename is hyphenated. However, this hyphenation somehow passes onto the latest.yml file. Have I done something weird, or is something fishy going on?

Thanks for any help in advance!
