### ISSUE TITLE
latest-mac.yml not being generated

### ISSUE THREAD

**Issue by Ajeey** [electron-userland/electron-builder#2313]
* **Version**: 
"electron-builder": "19.45.5",
"electron-publisher-s3": "19.43.0",
"electron-updater": "2.16.1",

* **Target**: 
Mac

After updating to electron-builder to ```19.45.5```,  ```the latest-mac.yml``` file is not being generated.

**Comment by antoinedeschenes** [comment]
Same here, publishing to S3, with a zip target for mac, any versions of electron-builder after 19.43
with any combination of electronUpdaterCompatibility and generateUpdatesFilesForAllChannels

**Comment by Ajeey** [comment]
yes I had to downgrade to 10.43.4 to get updates working on mac!

**Comment by antoinedeschenes** [comment]
Maybe it's related to https://github.com/electron-userland/electron-builder/issues/2326 
I'm building the zip using the electron-builder:wine Docker image.

**Comment by purplekrayons** [comment]
In my case:

electron-builder: 19.45.4
electron-updater: 2.16.1
electron-publisher-s3: 19.46.0

I am also publishing to an S3 bucket.

```
"publish": {
      "provider": "s3",
      "bucket": "myBucketName",
      "path": "release",
      "acl": "public-read"
    }
```

When I release my application, it builds three files:

```
filename-x.x.x.dmg
filename-x.x.x.dmg.blockmap
filename-x.x.x-mac.zip
```

In addition, it also produces (interestingly), both a `.yml` and `.json` file.

`latest-mac.yml`
```
version: x.x.x
files:
  - url: filename-x.x.x-mac.zip
    sha512: BLAH
  - url: filename-x.x.x.dmg
    sha512: BLAH
    size: 178399055
path: filename-x.x.x-mac.zip
sha512: BLAH
releaseDate: '2017-11-21T21:56:35.912Z'
```

`latest-mac.json`
```
{
  "version": "x.x.x",
  "releaseDate": "2017-11-21T21:54:45.945Z",
  "url": "https://batman.s3.amazonaws.com/release/filename-x.x.x-mac.zip"
}
```

@Ajeey Are you signing your mac apps?
