### ISSUE TITLE
file url in latest.yml is not correct

### ISSUE THREAD

**Issue by bisonfute** [electron-userland/electron-builder#2329]
electron-builder : 19.45.4
electron-updater: 2.16.1

I am building several nsis files customizing the artifactName as follows
```
"dist:win.dev": "electron-builder --windows --c.directories.output=$npm_package_config_dev_output --c.extraMetadata.server=$npm_package_config_dev_server --c.nsis.artifactName=SETUP-'${productName}'-$npm_package_config_dev_shortName-'${version}.${ext}'"
```
It works like a charm, my output is for example `SETUP-eGull Pay-dev-0.1.2.exe`

But in the latest.yml file, I have this
```
version: 0.1.2
files:
  - url: eGull-Setup-0.1.2.exe
    sha512: bsPpBK+V6a4z7LywWKoyshXxlsNLzxgBgBJmzi4DUGFGXmUPxlNCXyR+hrQR+tuM4+wK23M2p3sLVgVb4q/jBA==
path: eGull-Setup-0.1.2.exe
...
```

It seems to me that in the latest.yml, the default artifactName is used and not the customized one.

I need it to be generated correctly if I want the autoupdate to work, don't I ?
