### ISSUE TITLE
nsis-web differential update fails

### ISSUE THREAD

**Issue by HitomiTenshi** [electron-userland/electron-builder#2366]
* **Version**: 19.48.2

* **Updater Version**: 2.17.0

* **Target**: Win NSIS-Web (x64 & ia32)

Differential update now always fails, can't say for sure when it started happening. The fallback full update works.

All I did for this test is change the version number, updater and electron-builder versions were not changed in between.

```
Checking for update
Found version 1.0.3 (url: Media Presenter Web Setup 1.0.3.exe)
Downloading update from Media Presenter Web Setup 1.0.3.exe
Cannot download differentially, fallback to full download: SyntaxError: C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\_blockMap.yml: Unexpected token ∩┐╜ in JSON at position 0
SyntaxError: C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\_blockMap.yml: Unexpected token ∩┐╜ in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\jsonfile\index.js:33:18
    at C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:504:3)
From previous event:
    at C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\differentialDownloader\SevenZipDifferentialDownloader.js:44:84
From previous event:
    at SevenZipDifferentialDownloader.download (C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\differentialDownloader\SevenZipDifferentialDownloader.js:46:11)
    at C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:102:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:126:33
    at C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:85:23
    at Generator.next (<anonymous>)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at NsisUpdater.executeDownload (C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:95:11)
    at C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:84:25
From previous event:
    at NsisUpdater.doDownloadUpdate (C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\NsisUpdater.js:133:11)
    at C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:350:37
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.downloadUpdate (C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:355:11)
    at C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:324:63
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:326:11)
    at C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:275:37
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:280:11)
    at NsisUpdater.checkForUpdates (C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:226:39)
    at App.update (C:\Users\johann.rekowski\AppData\Local\Programs\media-presenter\resources\app.asar\index.bundle.min.js:1:2487)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
New version 1.0.3 has been downloaded to C:\Users\JOHANN~1.REK\AppData\Local\Temp\up-UpFLHU\Media%20Presenter%20Web%20Setup%201.0.3.exe
```

My config:

```
appId: media.presenter
copyright: "© 2016 - 2017 MEGO GmbH"
compression: maximum
npmRebuild: false

files:
  - "**/*"
  - "!{app,build,electron,mobile,theme,videos,util,dist,dist-app/app.bundle.js,dist-app/dependencies/shim.min.js,dist-app/dependencies/classList.min.js,dist-app/dependencies/web-animations.min.js,favicon.ico,index.html,index-aot.html,index-cordova.html,index.js,index-electron.js,index.bundle.js,systemjs.config.js,systemjs-angular-loader.js,package-lock.json}"
  - "!*config*.json"
  - "!**/*.{ts,scss,map,md,csv,wrapped,yml}"
  - "!**/*.{o,hprof,orig,pyc,pyo,rbc}"
  - "!**/._*"
  - "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,thumbs.db,.gitignore,.gitattributes,.editorconfig,.flowconfig,.yarn-metadata.json,.idea,appveyor.yml,.travis.yml,circle.yml,npm-debug.log,.nyc_output,yarn.lock,.yarn-integrity}"

publish:
  provider: generic
  url: "https://[redacted]/${os}"

win:
  verifyUpdateCodeSignature: false
  target:
    - nsis-web

nsisWeb:
  deleteAppDataOnUninstall: true
```
