### ISSUE TITLE
nsis installer removes existing app links in start menu subdirectory

### ISSUE THREAD

**Issue by timfish** [electron-userland/electron-builder#2381]
`electron-builder@19.45.5`
`platform: Windows 10`

nsis config:
```yml
nsis:
  guid: XXXXX-XXXXX-XXXXX-XXXXX
  multiLanguageInstaller: true
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  menuCategory: true
```

We have multiple applications all added to the start menu under a `Company Name` directory. When installing our Electron app, the contents of this directory are getting removed and after we are only left with a link to our Electron app.

I know very little about nsis scripts so I'm guessing it has something to do with [cleanupOldMenuDirectory or keepShortcuts](https://github.com/electron-userland/electron-builder/blob/541605ff2038c1b9485d8f0a3c88167f61e80b8d/packages/electron-builder-lib/templates/nsis/include/installer.nsh#L181) but I haven't managed to get my head around the logic yet.
