### ISSUE TITLE
"Error: spawn 7za ENOENT" in docker:wine

### ISSUE THREAD

**Issue by jesse23** [electron-userland/electron-builder#2430]
* **Version**: 
commit e4a2ede

* **Target**: 
Windows

"Error: spawn 7za ENOENT" in docker:wine. I suspect it is related to commit e4a2ede. Because it was working fine around 5 days ago. I will try to roll it back and see.

**Comment by jesse23** [comment]
It is reproducible by gitlab ci below:
```
release:       
  stage: release
  image: electronuserland/builder:wine
  script:
    - npm rebuild
    - npm run release
  only:
    - master
  artifacts:
    name: transformer
    paths:
      - out/site_last/dist/transformer*
  variables:
    USE_SYSTEM_7ZA: "true"
```

Works fine with:
```
release:       
  stage: release
  image: electronuserland/builder:wine
  script:
    - npm rebuild
    - npm install 7zip-bin-linux
    - npm run release
  only:
    - master
  artifacts:
    name: transformer
    paths:
      - out/site_last/dist/transformer*
```
