### ISSUE TITLE
Can't run app built from travis (corrupted asar)

### ISSUE THREAD

**Issue by magne4000** [electron-userland/electron-builder#2440]
* **Version**: `19.27.3`, `19.52.1`
* **Target**: OSX 0.13.2, XCode 9.2

Building manually with `yarn run make` on my Macbook actually generates a valid build, but travis generates a build that shows the following error upon launch:

![image](https://user-images.githubusercontent.com/1098371/34594051-99bec5ce-f183-11e7-9fab-751affddb366.png)

**NB** `yarn run make` actually runs `cross-env NODE_ENV=production build --config electron-builder.yml`

### electron-builder.yml
```yml
appId: org.efounders.BrowserXCanary
productName: 'Station Canary'
mac:
  category: public.app-category.tools
  icon: 'build/icon-canary.icns'

asar: true
asarUnpack: [ "**/node_modules/sharp/**/*" ]
electronCompile: true

directories:
  output: release

protocols:
  name: Station
  schemes:
  - station

dmg:
  contents:
  - x: 410
    y: 150
    type: link
    path: "/Applications"
  - x: 130
    y: 150
    type: file

win:
  icon: 'build/icon-canary.ico'
  target:
  - squirrel

linux:
  target:
  - deb
  - AppImage

files:
  - "!app/theme/scss${/*}"
```

### .travis.yml
```yml
language: node_js

os:
  - osx

osx_image: xcode9.2

node_js:
  - "8"

cache:
  yarn: false

script:
  - yarn run test
  - yarn run make
```
