### ISSUE TITLE
Auto update fails for nsis-web

### ISSUE THREAD

**Issue by arjun-g** [electron-userland/electron-builder#2499]
* **Version**:  electron-builder : 19.36.0 , electron-updater: 2.11.0

* **Target**: Windows x86 & x64

I am building a nsis-web installer programmatically using the following code

```
const builder = require('electron-builder')
const Platform = builder.Platform
builder.build({
	targets: Platform.WINDOWS.createTarget('nsis-web', builder.Arch.ia32, builder.Arch.x64),
	config: {
		appId: 'com.example.app',
		buildVersion: '2.2.4',
		productName: 'ProductName',
		compression: 'maximum',
		copyright: 'Copyright © 2018',
		icon: path.join(__dirname, 'dist', 'app', 'assets', 'icons', 'icon.ico'),
		files: [
			{
				from: 'dist',
				filter: [
					'**/*',
					'!bin/**/*'
				]
			}
		],
		asarUnpack: [
			'bin/**/*'
		],
		extraResources: [
			'bin/application.exe'
		],
		directories: {
			output: `build`
		},
		nsisWeb: {
			artifactName: "${name}-${version}.${ext}",
			oneClick: false,
			allowToChangeInstallationDirectory: true,
			publish: {
				provider: 'generic',
				url: `https://example.com/installers/dev/win`
			}
		},
		publish: {
			provider: 'generic',
			url: `https://example.com/installers/dev/win`
		}
	}
}).then()
```
I got the following files as output.

- latest.yml
- ProductName-2.2.4.exe
- ProductName-2.2.4-ia32.nsis.7z
- ProductName-2.2.4-x64.nsis.7z

I uploaded these files to the publish location. Then downloading and installing ProductName-2.2.4.exe works fine. When I publish a update I get the 'update-available' event in autoupdater but when I call autoUpdater.downloadUpdate() I get the following error.

`Cannot download "https://example.com/installers/dev/win/undefined", status 404`

and here is the content of latest.yml file of the update

```
version: 2.2.5
releaseDate: '2018-01-19T15:50:37.552Z'
path: ProductName-2.2.5.exe
sha512: >-
  aVFNNwvat4x5NILXiO7rAtDKLJh0DFxlkE9hgjerYd4DTYqO13CUNJMrfjshEylSRtJkC7YtqUaIsvzw==
packages:
  ia32:
    file: ProductName-2.2.5-ia32.nsis.7z
    size: 45241465
    sha512: >-
      yT2YA5j8qL6o94TDwnhPkghdRDYIBvsYCBz/cgfgfa/cB4mysUH2Mc4ozPLll588TZcEM/MjknVSLmQ==
    headerSize: 11954
    blockMapSize: 143627
  x64:
    file: ProductName-2.2.5-x64.nsis.7z
    size: 51087790
    sha512: >-
      sqIMeLaIQ26U0gRV8qhlJQsKKhOW/gfgfjfgjtasfexQ0Mmy6PDhHJud1poZO5hyk4wcJtDDVxVfQoOg==
    headerSize: 11954
    blockMapSize: 159951
sha2: 53784f21923b14d5328dc317c5iu789f9ea2478cd0989d85e11b44cd2bd9
```

I am not sure why I get a undefined in the url. Can anyone help me out on this ?
