### ISSUE TITLE
Appx builder creates only a tarball

### ISSUE THREAD

**Issue by ZaninAndrea** [electron-userland/electron-builder#2527]
* **Version**: 19.52.1

* **Target**: Appx

I set up electron-builder to create an appx export, but it only creates a tarball.

This is my `electron-builder.yml`
```yml
appId: com.Nimbl
files:
    - build/**/*
    - node_modules/**/*"
directories:
    buildResources: assets
    output: dist
productName: Nimbl
extraMetadata:
    main: build/electron.js
win: 
    icon: build/icon.ico
    target:
        - appx
target:
    - appx
appx:
    applicationId: com.Nimbl
    backgroundColor: "#073642"
    displayName: Nimbl
    identityName: 48363AndreaZanin.NimblNotes
    publisher: CN=CCFAD946-9153-4EE0-B202-640EA1BB9886
    publisherDisplayName: Andrea Zanin
```

And this is the script I'm running
```
build --em.main=build/electron.js --win --ia32 -c electron-builder.yml
```
