### ISSUE TITLE
[nsis] artifactName breaks the build

### ISSUE THREAD

**Issue by apphelpyulongs** [electron-userland/electron-builder#2552]
* **Version**: 

19.56.0

* **Target**: 
win

I'm building on windows 8 and if I don't put the artifactName everything is ok. Here is the electron-builder.yaml

```
directories:
  output: test-release
  buildResources: src/test/install-resources
  app: electron-build
appId: 'test'
copyright: test'
files:
  - test-build/
  - main.js
  - package.json
extraFiles:
  - from: test-build/assets/img
    to: img
mac:
  target: default
  icon: test-build/assets/img/icon.ico
win:
  target: nsis
  icon: test-build/assets/img/icon.ico
nsis:
  oneClick: false
  perMachine: true
  artifactName: '${productName}'
  menuCategory: '${productName}'
  deleteAppDataOnUninstall: true
  installerSidebar: SidebarImage.bmp
  displayLanguageSelector: true
  installerLanguages:
    - fr
    - en
  include: installer.nsh
  warningsAsErrors: false
publish:
  url: >-
    https://test..userdev.test.net/test-release/${os}/${arch}
  provider: generic
electronVersion: 1.8.1
```

Logs on console

```
• electron-builder version=19.56.0
  • loaded configuration file=C:\Users\someone\workspace\test-apps\test-build\builder-config.json
  • writing effective config file=test-release\electron-builder.yaml
  • installing production dependencies platform=win32 arch=x64 appDir=C:\Users\someone\workspace\test-apps\electron-build
  • packaging       platform=win32 arch=x64 electron=1.8.1 appOutDir=test-release\win-unpacked
  • building        target=nsis file=test-release\test Service Agent archs=x64 oneClick=false
Error: Exit code: ENOENT. spawn C:\Users\someone\workspace\test-apps\test-release\test Service Agent ENOENT
    at C:\Users\someone\workspace\test-apps\node_modules\builder-util\src\util.ts:122:16
    at exithandler (child_process.js:212:5)
    at ChildProcess.errorhandler (child_process.js:224:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at exec (C:\Users\someone\workspace\test-apps\node_modules\builder-util\src\util.ts:85:3)
    at execWine (C:\Users\someone\workspace\test-apps\node_modules\builder-util\src\wine.ts:60:12)
    at C:\Users\someone\workspace\test-apps\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:267:11
From previous event:
    at NsisTarget.computeScriptAndSignUninstaller (C:\Users\someone\workspace\test-apps\node_modules\electron-builder-lib\out\targets\nsis\NsisTarget.js:373:11)
    at C:\Users\someone\workspace\test-apps\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:211:114
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at NsisTarget.buildInstaller (C:\Users\someone\workspace\test-apps\node_modules\electron-builder-lib\out\targets\nsis\NsisTarget.js:336:11)
    at C:\Users\someone\workspace\test-apps\node_modules\electron-builder-lib\src\targets\nsis\NsisTarget.ts:96:18
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (C:\Users\someone\workspace\test-apps\node_modules\electron-builder-lib\out\targets\nsis\NsisTarget.js:214:11)
    at C:\Users\someone\workspace\test-apps\node_modules\electron-builder-lib\src\packager.ts:372:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Packager.doBuild (C:\Users\someone\workspace\test-apps\node_modules\electron-builder-lib\out\packager.js:432:11)
    at C:\Users\someone\workspace\test-apps\node_modules\electron-builder-lib\src\packager.ts:308:52
    at Generator.next (<anonymous>)
    at C:\Users\someone\workspace\test-apps\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\someone\workspace\test-apps\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at Packager._build (C:\Users\someone\workspace\test-apps\node_modules\electron-builder-lib\out\packager.js:376:11)
    at C:\Users\someone\workspace\test-apps\node_modules\electron-builder-lib\src\packager.ts:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Packager.build (C:\Users\someone\workspace\test-apps\node_modules\electron-builder-lib\out\packager.js:332:11)
    at C:\Users\someone\workspace\test-apps\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\Users\someone\workspace\test-apps\node_modules\electron-builder\out\builder.js:61:21)
    at build (C:\Users\someone\workspace\test-apps\node_modules\electron-builder\src\builder.ts:280:10)
    at then (C:\Users\someone\workspace\test-apps\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Object.args [as handler] (C:\Users\someone\workspace\test-apps\node_modules\electron-builder\out\cli\cli.js:121:117)
    at Object.runCommand (C:\Users\someone\workspace\test-apps\node_modules\electron-builder\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\someone\workspace\test-apps\node_modules\electron-builder\node_modules\yargs\yargs.js:1042:24)
    at Object.get [as argv] (C:\Users\someone\workspace\test-apps\node_modules\electron-builder\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\Users\someone\workspace\test-apps\node_modules\electron-builder\out\cli\cli.js:117:439)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:148:9)
    at bootstrap_node.js:542:3
(node:9000) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'C:\Users\someone\workspace\test-apps\test-release\latest.yml'
(node:9000) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
