### ISSUE TITLE
Snap builds do not have architectures key specified in snapcraft.yaml

### ISSUE THREAD

**Issue by kspearrin** [electron-userland/electron-builder#2596]
* **Version**: 19.56.0

* **Target**: x64

Building linux with:

```
build --linux --x64
```

and

    "linux": {
      "target": [
        "snap",
        "rpm",
        "AppImage",
        "deb"
      ]
    },

results in a snap file: `myapp_0.0.1_amd64.snap`.

I try to submit this with `snapcraft push` and get errors. I contacted the snapcraft team on their forums and they say:

> electron-builder seems to be producing a snap without an architectures key

> there’s also a bug in electron-builder-- the snaps it’s producing are claiming to be compatible with all architectures (armhf, arm64, amd64, etc.).

See thread here: https://forum.snapcraft.io/t/snapcraft-push-error-keyerror-architectures/4056

For reference, my project: https://github.com/bitwarden/desktop

**Comment by kspearrin** [comment]
This is what I am seeing in the `bitwarden_0.0.4_amd64.snap\meta\snap.yml` file that is packaged:

```
name: bitwarden
version: 0.0.4
summary: Bitwarden
description: A secure and free password manager for all of your devices.
confinement: strict
grade: stable
apps:
  bitwarden:
    command: command-bitwarden.wrapper
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
```
