### ISSUE TITLE
NSIS AppSetup.exe icon not changed in some case

### ISSUE THREAD

**Issue by apolkingg8** [electron-userland/electron-builder#2601]
* **Version**: 20.0.5

none

* **Target**: Windows

I build my app with `nsis`, it almost works great, but the `App Setup 1.0.0.exe` icon in Windows File Explore with `list` or `small icon` view mode not changed (still the default nsis icon). In other mode (bigger icon) it works fine.

my setting: 
```yaml
directories:
  output: dist
  buildResources: build
  app: 'PATH_TO_APP'
npmRebuild: false
appId: com.kingapol.alice
asar: false
win:
  target:
    - nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: build/icon_256.ico
  uninstallerIcon: build/icon_256.ico
  installerSidebar: build/sidebar.bmp
  uninstallerSidebar: build/sidebar.bmp
appx:
  backgroundColor: '#d1d1d1'
  displayName: Tiat
mac:
  target:
    - dmg
    - zip
dmg:
  backgroundColor: '#424242'
electronVersion: 1.8.2
```
