### ISSUE TITLE
Stuck building deb package under Ubuntu VM in Windows 10

### ISSUE THREAD

**Issue by jimpark** [electron-userland/electron-builder#2668]
* **Version**: 20.0.5, 20.0.8, 20.3.1

* **Target**:  deb
Environments tried:
Ubuntu 16.04 VM via VMWare Player on Windows 10 Professional
Ubuntu 17.10 VMs via VMWare Player on Windows 10 Professional
Ubuntu 17.10 VM via VirtualBox on Windows 10 Professional
Ubuntu 17.10 VM via VMWare Fusion on macOS High Sierra

It gets to:
  * building target=deb arch=x64 file=dist/app_1.1.2_amd64.deb

And hangs indefinitely.

**Comment by develar** [comment]
Please set env `DEBUG=electron-builder` and attach log of the terminal output.

**Comment by jimpark** [comment]
```
  • electron-builder version=20.3.1
  • loaded configuration file=package.json ("build" field)
  • effective config config=
                       directories:
                         output: dist
                         buildResources: build
                       appId: org.jw.meps.inscribe
                       productName: Inscribe
                       copyright: Copyright © 2017 Watch Tower Bible and Tract Society of Pennsylvania
                       files:
                         - ./main.js
                         - ./dist/render/**
                         - ./bin/**
                         - ./electron/*.js
                       asarUnpack:
                         - ./bin/**
                       mac:
                         icon: src/assets/icon.icns
                       dmg:
                         contents:
                           - x: 110
                             'y': 150
                           - x: 240
                             'y': 150
                             type: link
                             path: /Applications
                       linux:
                         target:
                           - deb
                         maintainer: MEPS Programming
                         synopsis: Editor for MEPS Article files
                       nsis:
                         oneClick: true
                         perMachine: true
                         runAfterFinish: false
                       win:
                         target:
                           - appx
                           - 7z
                           - nsis
                         icon: src/assets/icon.ico
                       appx:
                         applicationId: MepsInscribe
                         identityName: MepsInscribe
                       protocols:
                         - name: Inscribe
                           schemes:
                             - inscribe
                       
  • writing effective config file=dist/electron-builder.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=1.8.2 appOutDir=dist/linux-unpacked
  • spawning        command=/home/jim/mf/inscribe/node_modules/7zip-bin-linux/x64/7za x -bd -bb /home/jim/.cache/electron/electron-v1.8.2-linux-x64.zip -aoa -o/home/jim/mf/inscribe/dist/linux-unpacked

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (906E9),ASM,AES-NI)

Scanning the drive for archives:
1 file, 51030111 bytes (49 MiB)

Extracting archive: /home/jim/.cache/electron/electron-v1.8.2-linux-x64.zip
--
Path = /home/jim/.cache/electron/electron-v1.8.2-linux-x64.zip
Type = zip
Physical Size = 51030111

- electron
- content_shell.pak
- pdf_viewer_resources.pak
- icudtl.dat
- libffmpeg.so
- libnode.so
- blink_image_resources_200_percent.pak
- content_resources_200_percent.pak
- ui_resources_200_percent.pak
- views_resources_200_percent.pak
- natives_blob.bin
- snapshot_blob.bin
- LICENSE
- LICENSES.chromium.html
- version
- resources/default_app.asar
- resources/electron.asar
- locales/zh-CN.pak
- locales/id.pak
- locales/hu.pak
- locales/bg.pak
- locales/bn.pak
- locales/zh-TW.pak
- locales/ml.pak
- locales/lt.pak
- locales/pl.pak
- locales/ru.pak
- locales/it.pak
- locales/fil.pak
- locales/mr.pak
- locales/ta.pak
- locales/ar.pak
- locales/nb.pak
- locales/sw.pak
- locales/te.pak
- locales/sr.pak
- locales/ca.pak
- locales/sl.pak
- locales/fr.pak
- locales/gu.pak
- locales/vi.pak
- locales/ro.pak
- locales/pt-PT.pak
- locales/pt-BR.pak
- locales/kn.pak
- locales/am.pak
- locales/th.pak
- locales/fake-bidi.pak
- locales/he.pak
- locales/sv.pak
- locales/de.pak
- locales/cs.pak
- locales/tr.pak
- locales/fa.pak
- locales/en-GB.pak
- locales/lv.pak
- locales/fi.pak
- locales/ja.pak
- locales/ms.pak
- locales/uk.pak
- locales/nl.pak
- locales/es.pak
- locales/es-419.pak
- locales/sk.pak
- locales/da.pak
- locales/ko.pak
- locales/hr.pak
- locales/hi.pak
- locales/et.pak
- locales/en-US.pak
- locales/el.pak
Everything is Ok

Files: 71
Size:       132259996
Compressed: 51030111
  • exited          command=7za code=0 pid=3288
  • spawning        command=/home/jim/mf/inscribe/node_modules/builder-util/node_modules/app-builder-bin-linux/x64/app-builder clear-exec-stack --input /home/jim/mf/inscribe/dist/linux-unpacked/inscribe
  • exited          command=app-builder code=0 pid=3289
  • building        target=deb arch=x64 file=dist/inscribe_1.1.2_amd64.deb
  • spawning        command=/home/jim/mf/inscribe/node_modules/builder-util/node_modules/app-builder-bin-linux/x64/app-builder icon --format set --root /home/jim/mf/inscribe/build --root /home/jim/mf/inscribe --out /home/jim/mf/inscribe/dist/.icon-set --input icons --input src/assets/icon.icns --input icon.icns --input /home/jim/mf/inscribe/node_modules/electron-builder-lib/templates/linux/electron-icons
  • path doesn't exist        path=/home/jim/mf/inscribe/build/icons
  • path doesn't exist        path=/home/jim/mf/inscribe/icons
  • path doesn't exist        path=/home/jim/mf/inscribe/build/icon.png
  • path doesn't exist        path=/home/jim/mf/inscribe/icon.png
  • path doesn't exist        path=/home/jim/mf/inscribe/build/src/assets/icon.icns
  • path resolved             outputFormat=set path=/home/jim/mf/inscribe/src/assets/icon.icns
  • skip unsupported icns sub image format file=/home/jim/mf/inscribe/src/assets/icon.icns type=ic04
  • skip unsupported icns sub image format file=/home/jim/mf/inscribe/src/assets/icon.icns type=ic05
  • map async                 taskCount=6
```
After this point, it just hangs there forever. Also of interest is that this project has no problems building in a non-VM environment.
