### ISSUE TITLE
Target Linux ignores productName

### ISSUE THREAD

**Issue by adlk** [electron-userland/electron-builder#2705]
* **Version**: 20.5.1, 20.3.1

* **Target**: Linux; .deb, .tar.gz

While doing a multi platform build, I've realized that the Linux target is ignoring `productName` and instead is falling back to the `name` field from package.json.

It did not make any differences if `productName` is specified in root or the `build` object.

To reproduce the issue just make a build for mac/windows and linux and you can see the artifact name for Linux being `name` instead of `productName`

<details>
  <summary>Generated electron-builder.yaml:</summary>

```
directories:
  output: ./release
  buildResources: build
productName: App
appId: com.example.id
files:
  - ./build/app.js
mac:
  icon: ./resource/image/app-icon.icns
  category: public.app-category.social-networking
dmg:
  title: Installer
  icon: ./resource/image/dmg-icon.icns
  iconSize: 150
  background: ./resource/image/dmg-background/background.png
  contents:
    - x: 486
      'y': 176
      type: link
      path: /Applications
    - x: 156
      'y': 179
      type: file
win:
  target:
    target: nsis
    arch:
      - x64
      - ia32
  icon: ./resource/image/icon.ico
nsis:
  oneClick: false
linux:
  target:
    - deb
    - tar.gz
  icon: ./resource/image/app-icon/icon/512x512.png
  executableName: app
  category: Development
  synopsis: Desktop client
electronVersion: 1.6.16
```

</details>
