### ISSUE TITLE
latest-mac.yml doesn't take into account artifactName configuration for .zip build

### ISSUE THREAD

**Issue by IGassmann** [electron-userland/electron-builder#2706]
The generated `latest-mac.yml` file doesn't use the configured name format for the macOS zip build.

**Comment by develar** [comment]
As far I remember, it was checked and cannot reproduce. I will check again (probably there are also tests for it).

**Comment by IGassmann** [comment]
Just happened with version `20.5.1`. `artifactName` was set to `${productName}_${version}.${ext}`. Mac target was not defined.

**Comment by develar** [comment]
I cannot reproduce.


latest-mac.yml:
```
version: 1.1.0
files:
  - url: Test App ßW_1.1.0_mac.zip
    sha512: zwhWkajsM/GBjbsM8GBEeTEFgjvrbi844IvubH46FZ+mAA1Dppa8Kd4+OumtHNmi7b8DAi9vUvgk0SaxlPWYpw==
path: Test App ßW_1.1.0_mac.zip
sha512: zwhWkajsM/GBjbsM8GBEeTEFgjvrbi844IvubH46FZ+mAA1Dppa8Kd4+OumtHNmi7b8DAi9vUvgk0SaxlPWYpw==
releaseDate: '2018-03-18T16:53:49.990Z'
```

```
artifactName: "${productName}_${version}_${os}.${ext}",
```

```
Test App ßW_1.1.0_mac.zip
```

**Comment by IGassmann** [comment]
Wasn't able to reproduce it either with a minimum configuration.

**Comment by IGassmann** [comment]
So I was finally able to reproduce the error in a minimal configuration. It seems to happen only with a configured S3 publisher. If you check out the branch [`electron-builder` on the repository IGassmann/electron-builder](https://github.com/IGassmann/electron-playground/tree/electron-builder) you can test it on a macOS environment by running `yarn build`. You'll notice that the produced `.zip` file don't have the suffix `-mac`, but on the file `latest-mac.yml` it has it.

**Comment by IGassmann** [comment]
Here's the interesting line of a Travis job that ran the code: https://travis-ci.org/IGassmann/electron-playground/jobs/357485512 .  As you can see, `electron-builder` produces two different file names for GitHub and S3.

**Comment by IGassmann** [comment]
@seanyesmunt @nikooo777

**Comment by tzarebczan** [comment]
@develar this is still an issue for us. We need to keep renaming the url in both the yml and json file.

**Comment by tzarebczan** [comment]
@develar pulled this our of Igors logs:
```
 uploading       file=ElectronPlayground_1.0.0.zip provider=S3
  â€¢ uploading       file=electron-playground-1.0.0-mac.zip provider=GitHub
2018-03-23T17:05:44.146Z electron-builder Request: {
  "hostname": "uploads.github.com",
  "path": "/repos/IGassmann/electron-playground/releases/10154073/assets?name=electron-playground-1.0.0-mac.zip",
```

Narrowed it down to: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-lib/src/targets/ArchiveTarget.ts#L46

Specifically, it's an issue with the URL on both the yml and json file. 
```

{
  "version": "0.22.0-rc.15",
  "releaseDate": "2018-06-25T19:58:48.236Z",
  "url": "https://s3.amazonaws.com/build.lbry.io/app/release/LBRY-0.22.0-rc.15-mac.zip"
} 
```
- should be: LBRY_0.22.0-rc.15.zip (underscore and remove mac)


```
version: 0.22.0-rc.11
files:
  - url: LBRY-0.22.0-rc.11-mac.zip
 
```
- should be: LBRY_0.22.0-rc.15.zip (underscore and remove mac)

**Comment by tzarebczan** [comment]
@develar tried on electron updater 2.23.3 and builder 20.22.0 and it's half fixed. The yml file is correct, but the json file still shows the incorrect artifact name, see below. I just found that the json file is no longer used...any idea why it's still created? 

json:
```
{
  "version": "0.1.0-rc.2",
  "releaseDate": "2018-07-17T21:05:50.532Z",
  "url": "https://s3.amazonaws.com/build.lbry.io/app/release/LBRY-0.1.0-rc.2-mac.zip"
}
```

yml:
```
version: 0.1.0-rc.2
files:
  - url: LBRY_0.1.0-rc.2.zip
    sha512: G8jrOlT/ouWzK9/L48/T45GAm0zbj6hW6g8f67uQAZkVn4X16BfWx/7QDF4hdJuKv/l4N+uT+2akjnyjRIbR7w==
  - &ref_0
    url: LBRY_0.1.0-rc.2.dmg
    sha512: c2aRD+aQ37xJu5h28EXQBBiI/eEbm5kLV9O3IFx2qHqYM49gUcaD6emMgciwYYMgDPnwLgzix757KBwfxxaZXA==
    size: 86916200
  - *ref_0
path: LBRY_0.1.0-rc.2.zip
sha512: G8jrOlT/ouWzK9/L48/T45GAm0zbj6hW6g8f67uQAZkVn4X16BfWx/7QDF4hdJuKv/l4N+uT+2akjnyjRIbR7w==
releaseDate: '2018-07-17T21:05:58.590Z'
```
