### ISSUE TITLE
Installer reported as a virus as win32:evo-gen

### ISSUE THREAD

**Issue by AhadCove** [electron-userland/electron-builder#2905]
* **Version**: 20.8.1
* **Electron-Updater**: 2.21.4

* **Target**: Windows

Avast and other Antivirus are giving false reports to my installer and stopping them for my users. They're being reported as **win32:evo-gen** and I received one report a little while ago as **filerepmalware**. It reports the updates as well. 

The installer is signed and Microsoft seems to say it's okay. It's just the other Anti-viruses 

* VirusTotal Report

4/64 Engines detected this file

- Trojan.Win32.TheRat.eykuxz
- FileRepMalware
- Trojan[Exploit]/EXE.CVE-2016-0099.Generic

**Comment by benoist** [comment]
I'm having this issue as well, anything we can do?

**Comment by AhadCove** [comment]
I just reverted back to a previous version. It must have been a new/updated dll in the newer versions that weren't being used previously. Now I don't have any issues

**Comment by benoist** [comment]
Reverting doesn't solve the issue right?

**Comment by timfish** [comment]
I can't reproduce this with any of the recent versions and this config:

```yml
nsis:
  multiLanguageInstaller: true
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  menuCategory: true
```
