### ISSUE TITLE
Weird ref_0 lines being written in latest-mac.yml

### ISSUE THREAD

**Issue by odiseo42** [electron-userland/electron-builder#2993]
* **Version**:  20.4.1

* **Electron updater version**: 2.20.1

* **Target**:  Mac

When I build my electron app for mac, I'm seeing these weird lines in the latest-mac.yml including `- &ref_0` and `- *ref_0`. They're causing me issues parsing the file, so I have a couple of questions:

* what does those things mean?

* is it possible to make the build process not write those lines?

```
version: 1.10.1
files:
  - url: [Redacted].zip
    sha512: rJNq+v51VQtFTmruU+ZRvzQ4SHs+906k50wj6bHDa0YxEeRNP24JTmU1MrC9QV53r1hwO5ZTDWRuj61xCt9lVQ==
  - &ref_0
    url: [Redacted].dmg
    sha512: M3bcqRn7ZbLRjITRBc/1nmTA9vcRIZECYJyG6XK9uJOk1CE5Ha8UvFu9Cft99OFl5w5VuRM/IADgJIuHRQNe1A==
    size: 55682820
  - *ref_0
path: [Redacted].zip
sha512: rJNq+v51VQtFTmruU+ZRvzQ4SHs+906k50wj6bHDa0YxEeRNP24JTmU1MrC9QV53r1hwO5ZTDWRuj61xCt9lVQ==
releaseDate: '2018-06-07T16:59:27.524Z'
```
