### ISSUE TITLE
Installer reported as a virus: Trojan[Exploit]/EXE.CVE-2016-0099.Generic

### ISSUE THREAD

**Issue by AhadCove** [electron-userland/electron-builder#3315]
### Version

* **Version**: 20.28.4 
* **Electron-Updater**: 3.1.2
* **Target**: Windows

### NSIS Config

```
nsis:
  oneClick: false
  allowElevation: true
  warningsAsErrors: false
  perMachine: true
  unicode: false
  allowToChangeInstallationDirectory: true
```

### Issue
I had this issue months ago and resolved it by just reverting to the last version that didn't flag my app, but now I want all of my users to benefit from all of the cool updates that you all are doing, yet I seem to still run into both windows and virustotal claiming there's a virus when I use the latest electron-builder. Virus total shows this is the virus:
**Trojan[Exploit]/EXE.CVE-2016-0099.Generic**

One of the main reasons I wanted to update the app was because I was getting reports that when a few users updated the app it uninstalled it without ever reinstalling.
