### ISSUE TITLE
Mac S3 auto updater url and path 404 error

### ISSUE THREAD

**Issue by Circuit8** [electron-userland/electron-builder#3414]
* **Version**: 20.28.4

* **Electron Updater**: 3.1.2

* **Target**: Mac

When building for Mac with the following settings:
```
    "mac": {
      "publish": [
        {
          "provider": "s3",
          "bucket": "my-bucket"
        },
        "github"
      ]
    },
```
The generated `alpha-mac.yml` file is as below:

```
version: 0.11.6-alpha
files:
  - url: my-software-0.11.6-alpha-mac.zip
    sha512: VZiKuD27K26aQy8Ty6kDwkwrzV4m971PujOPoaFE5UJZKvpDFuVV/DNBRBY22tf4om/hHj4YhnewPMOYu6ooTg==
  - url: my-software-0.11.6-alpha.dmg
    sha512: WI4ozW7EaScE7VHsZQRVTSn2g6FXCyngY8cT+rqZrGmiLal7wrvI7zPlJxhtreqyvKpUGxtdJ3ImVxLox1/NtQ==
    size: 63149164
path: My Software-0.11.6-alpha-mac.zip
sha512: VZiKuD27K26aQy8Ty6kDwkwrzV4m971PujOPoaFE5UJZKvpDFuVV/DNBRBY22tf4om/hHj4YhnewPMOYu6ooTg==
releaseDate: '2018-10-24T11:42:14.636Z'
```

The auto updater then throws a 404 error because the path and url are different. It seems to look for the path rather than the url, but its saved on S3 as it suggests in the url.
