### ISSUE TITLE
Unable to exclude files from app.asar

### ISSUE THREAD

**Issue by douglassllc** [electron-userland/electron-builder#3446]
* **Version**: 20.28.4 and 
* **Target**: all, but specifically I am currently testing mac

On my project the ability to excludes files by annotating them under the build section in package.json was working.

After adding electron-webpack.  This now no longer works.  I am seeing everything included in my app.asar file.  I have attempted to exclude electron-webpack from my build process and only run electron-build, but I still see everything in app.asar.  Here is my debug log from running ```DEBUG=electron-builder npm run pack```

```
"pack": "electron-builder --dir",
```

```
directories:
  output: dist
  buildResources: src/assets
extraMetadata:
  main: main.js
files:
  - from: .
    filter:
      - package.json
      - '**/*'
      - src
      - '!webpack*'
      - '!.*'
      - '!config/jsdoc.json'
      - '!package.json'
      - '!docs'
      - '!private'
  - from: dist/main
  - from: dist/renderer
  - from: dist/renderer-dll
extraResources:
  - from: src/assets
    to: assets
    filter:
      - '!track*'
      - '!css'
appId: com.test.test
productName: Test Desktop
copyright: '© 2018 Test, LLC.'
artifactName: '${name}-${version}-${os}-${arch}.${ext}'
publish:
  - provider: s3
    bucket: xxx
    storageClass: STANDARD_IA
    path: '${channel}/${os}'
  - provider: github
    owner: xxx
    repo: xxx
linux:
  files:
    - '!node_modules/@ffprobe-installer/darwin-x64/${/*}'
    - '!node_modules/@ffprobe-installer/win32-ia32/${/*}'
    - '!node_modules/@ffprobe-installer/win32-x64/${/*}'
    - '!node_modules/@ffmpeg-installer/darwin-x64/${/*}'
    - '!node_modules/@ffmpeg-installer/win32-ia32/${/*}'
    - '!node_modules/@ffmpeg-installer/win32-x64/${/*}'
  category: AudioVideoEditing
  description: Test desktop video processing and file uploader
  icon: src/assets/icon.png
  desktop:
    Name: Test-Desktop
    GenericName: Test Desktop
    X-GNOME-FullName: test-desktop
    Comment: Test desktop video processing and file uploader
    Type: Application
    Terminal: 'false'
    StartupNotify: 'false'
    Categories: AudioVideoEditing
mac:
  files:
    - '!node_modules/@ffprobe-installer/linux-ia32/${/*}'
    - '!node_modules/@ffprobe-installer/linux-x64/${/*}'
    - '!node_modules/@ffprobe-installer/win32-ia32/${/*}'
    - '!node_modules/@ffprobe-installer/win32-x64/${/*}'
    - '!node_modules/@ffmpeg-installer/linux-ia32/${/*}'
    - '!node_modules/@ffmpeg-installer/linux-x64/${/*}'
    - '!node_modules/@ffmpeg-installer/win32-ia32/${/*}'
    - '!node_modules/@ffmpeg-installer/win32-x64/${/*}'
  category: public.app-category.video
win:
  files:
    - '!node_modules/@ffprobe-installer/linux-ia32/${/*}'
    - '!node_modules/@ffprobe-installer/linux-x64/${/*}'
    - '!node_modules/@ffprobe-installer/darwin-x64/${/*}'
    - '!node_modules/@ffmpeg-installer/linux-ia32/${/*}'
    - '!node_modules/@ffmpeg-installer/linux-x64/${/*}'
    - '!node_modules/@ffmpeg-installer/darwin-x64/${/*}'
  certificateFile: private/test.pfx
  verifyUpdateCodeSignature: false
  publisherName: trackops
extends: electron-webpack/electron-builder.yml
electronVersion: 3.0.7
```
