### ISSUE TITLE
Error building with custom electron build (reopening #3407)

### ISSUE THREAD

**Issue by rr326** [electron-userland/electron-builder#3461]
* **Version**: 20.33.2
Electron version: > 4.0.0-beta.6 
Custom electron build, last commit: 4e53019b75ece9e83aea03221470c94d0e8158c3

* **Target**: mas, mac

This is reopening #3407 
My current setup is more complicated to get it all working properly. I build, then use a custom electronDownload config to use my local mirror.

### Build Error
```
  • electron-builder version=20.33.2
  • loaded configuration file=/Users/rrosen/dev/filing/build/ebuilderconfig_masdev.json
  • writing effective config file=dist_masdev/builder-effective-config.yaml
  • rebuilding native production dependencies platform=darwin arch=x64
  • packaging       platform=mas arch=x64 electron=4.0.0-beta.6 appOutDir=dist_masdev/mas-dev
[xmldom error]	invalid doc source
@#[line:0,col:undefined]
TypeError: Cannot read property 'documentElement' of undefined
    at parse (/Users/rrosen/dev/filing/node_modules/plist/lib/parse.js:68:9)
    at /Users/rrosen/dev/filing/node_modules/app-builder-lib/src/electron/electronMac.ts:60:20
From previous event:
    at _createMacApp (/Users/rrosen/dev/filing/node_modules/app-builder-lib/out/electron/electronMac.js:262:24)
    at createMacApp (/Users/rrosen/dev/filing/node_modules/app-builder-lib/out/electron/electronMac.js:120:24)
    at /Users/rrosen/dev/filing/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:76:11
    at Generator.next (<anonymous>)
From previous event:
    at _beforeCopyExtraFiles (/Users/rrosen/dev/filing/node_modules/app-builder-lib/out/electron/ElectronFramework.js:162:32)
    at beforeCopyExtraFiles (/Users/rrosen/dev/filing/node_modules/app-builder-lib/out/electron/ElectronFramework.js:111:32)
    at beforeCopyExtraFiles (/Users/rrosen/dev/filing/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:151:14)
    at /Users/rrosen/dev/filing/node_modules/app-builder-lib/src/platformPackager.ts:222:13
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at MacPackager.doPack (/Users/rrosen/dev/filing/node_modules/app-builder-lib/src/platformPackager.ts:166:165)
    at /Users/rrosen/dev/filing/node_modules/app-builder-lib/src/macPackager.ts:108:20
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/rrosen/dev/filing/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/rrosen/dev/filing/node_modules/app-builder-lib/src/packager.ts:375:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.doBuild (/Users/rrosen/dev/filing/node_modules/app-builder-lib/src/packager.ts:343:39)
    at /Users/rrosen/dev/filing/node_modules/app-builder-lib/src/packager.ts:313:57
    at Generator.next (<anonymous>)
    at /Users/rrosen/dev/filing/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/rrosen/dev/filing/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/rrosen/dev/filing/node_modules/app-builder-lib/src/packager.ts:284:133)
    at /Users/rrosen/dev/filing/node_modules/app-builder-lib/src/packager.ts:280:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/Users/rrosen/dev/filing/node_modules/app-builder-lib/src/packager.ts:237:14)
    at build (/Users/rrosen/dev/filing/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/rrosen/dev/filing/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/rrosen/dev/filing/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
```

### Config for mas build
```
$cat dist_masdev/builder-effective-config.yaml

directories:
  output: dist_masdev
  buildResources: build
appId: com.k2companyllc.filesimple
productName: FileSimple
compression: normal
artifactName: '${productName}-${version}.${ext}'
files:
  - filter:
      - dist/
      - '!**/.DS_Store'
mac:
  icon: build/icon.icns
  category: public.app-category.productivity
  target:
    - mas-dev
  entitlements: build/entitlements.mac.plist
  entitlementsInherit: build/entitlements.mac.inherit.plist
  type: development
  minimumSystemVersion: '10.13'
  provisioningProfile: build/Mac_Dev__iMac_and_vBox_181010.provisionprofile
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mas:
  type: distribution
  binaries:
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_bisect.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_bz2.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_codecs_cn.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_codecs_hk.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_codecs_iso2022.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_codecs_jp.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_codecs_kr.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_codecs_tw.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_ctypes.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_datetime.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_decimal.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_hashlib.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_heapq.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_json.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_lzma.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_md5.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_multibytecodec.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_multiprocessing.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_opcode.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_pickle.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_posixsubprocess.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_random.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_scproxy.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_sha1.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_sha256.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_sha512.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_socket.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_ssl.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/_struct.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/.Python
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/array.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/binascii.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/fcntl.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/FileSimpleServer
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/gevent._semaphore.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/gevent.ares.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/gevent.corecext.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/greenlet.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/grp.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/libcrypto.1.0.0.dylib
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/liblzma.5.dylib
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/libreadline.7.dylib
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/libssl.1.0.0.dylib
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/markupsafe._speedups.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/math.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/mmap.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/persistent._timestamp.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/persistent.cPersistence.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/persistent.cPickleCache.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/pyexpat.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/readline.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/resource.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/select.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/simplejson._speedups.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/termios.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/unicodedata.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/zlib.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/zodbpickle._pickle.so
    - /Users/rrosen/dev/filing/dist_masdev/mas-dev/FileSimple.app/Contents/Resources/FileSimpleServer/zope.interface._zope_interface_coptimizations.so
win:
  icon: build/icon.ico
  extraResources:
    - from: app/Resources/win
      to: ''
      filter:
        - '**/*'
extraResources:
  - to: ''
    filter:
      - '**/*'
    from: app/python/dist_darwin_10.14
  - from: app/static
    to: static
    filter:
      - testdata/**/*
      - GIT_REV_INFO.json
electronDownload:
  mirror: 'http://0.0.0.0:8000/'
  cache: /Users/rrosen/dev/filing/electron/electron-gn/src/out/cache
  customDir: .
electronVersion: 4.0.0-beta.6
```
