### ISSUE TITLE
Unable to publish assets to Github (ReleaseAsset asset_already_exists)

### ISSUE THREAD

**Issue by mrfelton** [electron-userland/electron-builder#3559]
* **Version**: 20.38.4

* **Target**: mac/windows/linux

Since updating from 20.38.2 -> 20.38.4 electron-build has been unable to publish assets to a github release page. Downgrading to 20.38.2 resolves the issue.

It fails on publishing every asset from every os.

Here is an example:
https://travis-ci.org/LN-Zap/zap-desktop/jobs/469993385#L2805

```
2018-12-19T13:21:03.988Z electron-builder Response: 422 Unprocessable Entity, request options: {
  "hostname": "uploads.github.com",
  "path": "/repos/LN-Zap/zap-desktop/releases/13734557/assets?name=ZapDesktop-linux-i386-v0.3.0-beta.deb",
  "method": "POST",
  "headers": {
    "accept": "application/vnd.github.v3+json",
    "Content-Type": "application/octet-stream",
    "Content-Length": 52382742,
    "authorization": "<stripped sensitive data>",
    "User-Agent": "electron-builder",
    "Cache-Control": "no-cache"
  }
}
  • async task error error=
                       422 Unprocessable Entity
                       {
                         "message": "Validation Failed",
                         "request_id": "E166:5EBB:2E3AE0:33E8F0:5C1A45BF",
                         "documentation_url": "https://developer.github.com/v3",
                         "errors": [
                           {
                             "resource": "ReleaseAsset",
                             "code": "already_exists",
                             "field": "name"
                           }
                         ]
                       }
                       Headers: {
                         "cache-control": "no-cache",
                         "content-length": "211",
                         "content-security-policy": "default-src 'none'",
                         "content-type": "application/json; charset=utf-8",
                         "strict-transport-security": "max-age=31557600",
                         "x-accepted-oauth-scopes": "repo",
                         "x-content-type-options": "nosniff",
                         "x-frame-options": "deny",
                         "x-github-media-type": "github.v3; format=json",
                         "x-oauth-scopes": "public_repo",
                         "x-xss-protection": "1; mode=block",
                         "date": "Wed, 19 Dec 2018 13:21:04 GMT",
                         "connection": "close",
                         "x-github-request-id": "E166:5EBB:2E3AE0:33E8F0:5C1A45BF"
                       }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zap-desktop@0.3.0-beta package: `npm run build && npm run fetch-lnd && build "--publish" "onTagOrDraft" "--linux"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zap-desktop@0.3.0-beta package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-12-19T13_21_04_026Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Script failed with status 1
failed to deploy
```

If I delete the existing assets from the draft github release and try again then it works, but only the first time. Every subsequent attempt fails with the same error ^.

Here are some other similar issues where this was reported in the past:

- https://github.com/electron-userland/electron-builder/issues/2396
- https://github.com/electron-userland/electron-builder/issues/2094
- https://github.com/electron-userland/electron-builder/issues/2337

**Comment by TrevorSayre** [comment]
I'm getting the same issue on 20.38.3, downgrading to 20.38.2 resolved this for me

**Comment by SupremeTechnopriest** [comment]
@mrfelton @TrevorSayre This isn't a bug.  The release you are trying to push already exists on github.  You either have to bump your `package.json` version or delete the old release from github to overwrite the version.

**Comment by SupremeTechnopriest** [comment]
You don't have to create the draft. It's creates automatically. =)

**Comment by SupremeTechnopriest** [comment]
That's probably why you are having issues.

**Comment by mrfelton** [comment]
Interesting. Is that a recent change?

**Comment by SupremeTechnopriest** [comment]
No idea, just started using electron. I know the docs are wrong.

**Comment by pgebheim** [comment]
There's definitely something buggy here -- the process of being able to update draft releases is how you can do -snapshot releases (as described in that section of the docs).

If we need to we could script deleting the old releases first in CI, but that's a regression and I don't see anything stating that was an intended change. Also, the fact that we get a 422 means that the code is now sending a different API request -- its not like electron-builder is just checking for the existence of a release and skipping it with good messaging.

**Comment by hacdias** [comment]
> @SupremeTechnopriest in my case, the release only existed as a draft release. In the past this has always worked and I thought this was the standard process.
> 
> 1. Create a draft release
> 2. Every build will upload new assets to the draft release, replacing those of prior builds
> 3. Publish the draft when you are ready to release.
> 
> Has this changed?

That's what we were expecting. But since we upgraded to the latest release, it broke. Any updates on this @pgebheim?

**Comment by SupremeTechnopriest** [comment]
I guess something did change because you can't have the draft release
created beforehand now. Electron builder creates it for you.

**Comment by mrfelton** [comment]
```
Recommended GitHub Releases Workflow¶
Draft a new release. Set the “Tag version” to the value of version in your application package.json, and prefix it with v. “Release title” can be anything you want.

For example, if your application package.json version is 1.0, your draft’s “Tag version” would be v1.0.

Push some commits. Every CI build will update the artifacts attached to this draft.

Once you are done, publish the release. GitHub will tag the latest commit for you.
The benefit of this workflow is that it allows you to always have the latest artifacts, and the release can be published once it is ready.
```

Something is clearly wrong here.

You are supposed to create the draft yourself, and electron-builder is supposed to publish to the draft only if it exists. Electron Builder isn't supposed to be creating the draft releases for you when you are using the `onTagOrDraft` setting.

**Comment by hacdias** [comment]
Any updates on this? @develar

**Comment by polarathene** [comment]
@mrfelton not exactly a solution for everyone else here, but in regards to Travis CI and Github releases, why not use their `releases`(Github) deploy provider? You can build prior to deploy step this way, works well for me.

```YAML
# Only build on code commits, not when tags are added(eg upon publishing a draft release)
if: tag IS blank

# Two build jobs, one on macOS, another on Linux with Docker to build Linux + Windows binaries
matrix:
  include:
    - name: "macOS"
      os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - name: "Windows + Linux"
      os: linux
      services: docker
      language: generic

# Clear out any cached files here
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
  
# Keep files in these directories
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

# Actual build command/script for the two jobs in the matrix above to use (could probably move these into each one?)
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn dist --linux --win"
    else
      yarn dist
    fi

# Workaround for bug in Travis deploy logic, `tag_name` isn't used for draft releases,
# Specify the tag to target in draft release instead for now via $TRAVIS_TAG
before_deploy:
  - export TRAVIS_TAG="preview"

# Deploy to Github Releases as draft release or update the existing one with the above `tag_name` value(any existing files will be overwritten)
deploy:
  provider: releases
  api_key: $OAUTH_TOKEN
  skip_cleanup: true
  draft: true
  overwrite: true
  file_glob: true
  file:
    - dist/**/*.exe
    - dist/**/*.zip
    - dist/**/*.dmg
    - dist/**/*.snap
    - dist/**/*.AppImage
```

More details [here](https://github.com/travis-ci/travis-ci/issues/10230#issuecomment-474267634).

The above `.travis.yml` will let you draft a release with the tag you want to use(you don't need to add a tag to a commit and can let the publish of the release assign a tag to a commit instead), with the example it works best as a placeholder tag and you adjust that to the actual tag you want to use when you manually publish a release. You could use a script instead to make that dynamic and say use the version from `package.json`.

This approach has a drawback in that as it deploys an update to the draft release each commit instead of when a commit is tagged(see alternate version in link provided), when the version is changed in the `package.json`, assuming your filees are appending that version to their filename, you'll need to discard the previous files that get added to the draft release when you bump the package.json version. The quoted workflow would supposedly run into the same issue though anyhow.
