### ISSUE TITLE
Error Autoupdating from Private GitHuB Repo

### ISSUE THREAD

**Issue by apurvaSynerzip** [electron-userland/electron-builder#3563]
Electron Builder Version : 20.38.3

getting following in Log file while Autoupdating from Private Github Repo:

```
[13:12:2018][19:47:55:187]New version 1.3.0 has been downloaded to /Users/Library/Application Support/Caches/project1-updater/pending/update.zip
[13:12:2018][19:47:55:236]/ requested
[13:12:2018][19:47:55:242]/1544710675192-8651.zip requested
[13:12:2018][19:47:55:242]/1544710675192-8651.zip requested by Squirrel.Mac, pipe /Users/Library/Application Support/Caches/project1-updater/pending/update.zip
[13:12:2018][19:47:55:673]Error: ditto: Couldn't read PKZip signature

[13:12:2018][19:47:55:674]Error: Error: ditto: Couldn't read PKZip signature
[13:12:2018][19:47:55:674]Error: ditto: Couldn't read PKZip signature

[13:12:2018][19:48:00:541]Proxy server for native Squirrel.Mac is closed (was started to download https://api.github.com/repos/Jarfus/project1/releases/assets/10112663)
```

**Comment by apurvaSynerzip** [comment]
@develar Can you Please help?

**Comment by muhzi4u** [comment]
@apurvaSynerzip Did you able to fix this issue?

**Comment by ApurvaB** [comment]
@muhzi4u Nope. Are you getting the same issue? Or you got the fix?

**Comment by muhzi4u** [comment]
@ApurvaB  Yup

**Comment by muhzi4u** [comment]
@ApurvaB Could you please share the build script in `package.json`?

**Comment by ApurvaB** [comment]
This is my electron-builder.yml

```
asar: true

directories:
  output: dist/

files:
  - package.json
  - main.js
  - build/
  - node_modules/

dmg:
  contents:
    - type: link
      path: /Applications
      x: 410
      y: 150
    - type: file
      x: 130
      y: 150
  publish:
    provider: github
    private: true
    token: "{my token value}"

mac:
  category: public.app-category.tools

win:
  target: nsis
nsis:
  oneClick: true
  deleteAppDataOnUninstall: true
  publish:
    provider: github
    private: true
    token: "{my token value}"

linux:
  target:
    - deb
    - AppImage
```

My autoupdater.js

```
const {app, dialog} = require('electron');
const {autoUpdater} = require('electron-updater');
const log = require('electron-log');
var os = require('os');

autoUpdater.logger = log;
autoUpdater.logger.transports.file.level = 'info';
autoUpdater.autoInstallOnAppQuit = false;


const server = '{HEROKU URL}'
var releaseUrl = `${server}/update/${process.platform}/${app.getVersion()}`;

    function appUpdater() {
    autoUpdater.setFeedURL({
             provider: 'generic',
              url: releaseUrl,
              private: true,
              token: '{token from heroku}'
    });
      //autoUpdater.setFeedURL(releaseUrl);
      autoUpdater.on('error', err => log.info(err));
      autoUpdater.on('checking-for-update', () => log.info('checking-for-update'));
      autoUpdater.on('update-available', () => log.info('update-available'));
      autoUpdater.on('update-not-available', () => log.info('update-not-available'));

      // Ask the user if update is available
      autoUpdater.on('update-downloaded', (event, releaseNotes, releaseName) => {
        let message = `${app.getName() } ${ event && event.releaseName } is now available. It will be installed the next time you restart the application.`;
        if (releaseNotes) {
          const splitNotes = releaseNotes.split(/[^\r]\n/);
          message += '\n\nRelease notes:\n';
          splitNotes.forEach(notes => {
            message += `${notes }\n\n`;
          });
        }
        // Ask user to update the app
        dialog.showMessageBox({
          type: 'question',
          buttons: ['Install and Relaunch', 'Later'],
          cancelId: 1,
          message: `A new version of ${ app.getName() } has been downloaded`,
          detail: message
        }, response => {
          log.info('response', response);
          if (response === 0) {
            setTimeout(() => autoUpdater.quitAndInstall(), 1);
          }

        });
      });
      // init for updates
      autoUpdater.checkForUpdatesAndNotify();
    }

exports = module.exports = {
  appUpdater
};
```

my main.js chunk

```
 const checkOS = isWindowsOrmacOS();
 if (checkOS) {
   appUpdater();
}
```
