### ISSUE TITLE
RequireAdministrator level not working on portable 

### ISSUE THREAD

**Issue by xiaoxiangmoe** [electron-userland/electron-builder#3738]
* Electron builder version: 20.24.5:
* Node version: v11.6.0
* NPM version: 6.5.0
* Target: Windows portable

config file:

```
"build": {
	"appId": "your.id",
	"win": { 
		"requestedExecutionLevel": "requireAdministrator",
		"target": [
			{
			    "target": "portable"
			}
		]
	}
}
```
The exported output doesn't have admin privileges.

**Comment by xiaoxiangmoe** [comment]
Use it instead

```yaml
win:
  target:
    - target: portable
      arch:
        - ia32
portable:
  requestExecutionLevel: admin
```
