### ISSUE TITLE
[Feature] Cross-platform multiple shortcuts support

### ISSUE THREAD

**Issue by Rudedog9d** [electron-userland/electron-builder#3752]
* **Version**: electron-builder@20.38.4
* **Target**: Windows and Linux

Have you considered adding support in the configuration file for multiple desktop/start menu shortcuts with different command line options? With Windows, this can be achieved with a custom NSIS macro. 

It'd be great if there was cross platform support for creating multiple shortcuts. A possible example:

```yaml
shortcuts:
  - icon: "public/images/sandbox-icon.png"
    action: "app.exe --sandbox"
    name: "App Sandbox"
  - icon: "public/images/icon.png"
    action: "app.exe"
    name: "App"
```
