### ISSUE TITLE
Question: Looking for sample Travis file/package.json to build mac image on Travis CI

### ISSUE THREAD

**Issue by kenlassesen** [electron-userland/electron-builder#3848]
Using  "electron-builder": "^20.39.0"
Target: MacOs

I get a "Done. Your build exited with 1."  #3 failed. Log does not indicate why.
[Travislog.txt](https://github.com/electron-userland/electron-builder/files/3104249/Travislog.txt)

.travis.yml File
```
os:
 - osx
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
cache:
  directories:
    - node_modules
    - "$HOME/.electron" 

script:
  - yarn release
     
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"`
```
Package Json
```
{
  "name": "sona",
  "version": "0.0.2",
  "description": "Azure Usage Analysis",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "pack": "build --dir",
    "dist": "build"
  },
  "build": {
    "appId": "com.lassesen.dpapi.sona",
    "productName": "Sona - Azure Usage",
    "mac": {
      "target": "dmg",
      "icon": "build/icon.png"
    },
    "files": [
      "*.js",
      "*.html",
      "*.css"
    ]
  }, 
  "dmg": {
    "internetEnabled" : true
  }, 
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^4.1.4",
    "electron-builder": "^20.39.0"
  },
  "dependencies": {
    "dataframe-js": "^1.4.1",
    "datejs": "^1.0.0-rc3",
    "lokijs": "^1.5.6",
    "xlsx": "^0.14.2"
  }
}
```
