### ISSUE TITLE
App doesn't start on Debian

### ISSUE THREAD

**Issue by zbynekbotlo** [electron-userland/electron-builder#3946]
* **Version**: 20.40.2

* **Target**: deb

1. Fork the minimal Electron app [electron-quick-start](https://github.com/electron/electron-quick-start)

2. Pack it using `electron-builder --linux --x64`

Here's my electron-builder.yml:
```
appId: electron.test
productName: "Electron Test"

files:
  - index.html
  - main.js
  - package.json

linux:
  target:
    - deb
  maintainer: "a@b.c"
```

It's installed correctly but nothing happens when the application is started on Debian:
- no window or error
- works just fine on Ubuntu
