### ISSUE TITLE
App Doesn't start on Windows (NSIS) (Previously working with no config changes)

### ISSUE THREAD

**Issue by darrenangle** [electron-userland/electron-builder#3947]
* **Version: 20.39.0**: 

N/A electron- updater

* **Target: NSIS Windows**: 

When building with `wine`, which points the docker image to latest by default(?): 

`FROM electronuserland/builder:latest`

The application builds an exe but trying to open after installation does nothing. Same for 32bit and 64. No errors. 

Nothing about our config has changed.

This is the command we use in the build step:

` - docker run --rm --env-file <(env | grep '=' | grep -iE 'CSC_') -v ${PWD}:/project electronuserland/builder:wine /bin/bash -c "npx electron-builder build --win --ia32 --config electron-config.yml";`

here's the relevant portion of our config: 

```
npmRebuild: false
win:
  appId: App.Name
  icon: icons/win/icon.png.ico
  publisherName: Company
  target:
    - msi
    - nsis
nsis:
  oneClick: false
  perMachine: false
allowToChangeInstallationDirectory: true
```

Donated! 💸
