### ISSUE TITLE
Why my nsis installer just 12MB after packaged it?

### ISSUE THREAD

**Issue by TongDaDa** [electron-userland/electron-builder#4087]
* **Version**: Latest

* **Target**:  win32

Below is my config of electron-builder.
```
  nsis:
    artifactName: '${productName} Setup ${version}.${ext}'
    script: nsisScripts/index.nsi
    allowElevation: true
    warningsAsErrors: false
    installerIcon: app/static/installer_icon.ico
    uninstallerIcon: app/static/installer_icon.ico
    multiLanguageInstaller: true
    packElevateHelper: true
```

In my project, I usually package my application to ./dist/win-unpackaged the directory, Its size about is 100M, but when I use the 'nsis' of target to package it, the installer just is 12M
