### ISSUE TITLE
Support GITHUB_TOKEN provided by GitHub Actions

### ISSUE THREAD

**Issue by nathany** [electron-userland/electron-builder#4176]
* **Version**:  21.2.0
* **Target**: macOS

I'm attempting to build an Electron app using GitHub Actions. A [GITHUB_TOKEN is provided](https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret) which could possibly be used instead of creating a personal access token.

```
- name: Publish release
  run: npm run release
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

However, the following error occurs:

> Error: GitHub Personal Access Token ("***") contains invalid characters, please check env "GH_TOKEN"
> at new GitHubPublisher (/Users/runner/runners/2.157.0/work/tailboard-electron/tailboard-electron/node_modules/electron-publish/src/gitHubPublisher.ts:53:15)

**Comment by judge2020** [comment]
I encoded it into hex to be able to extract the integration token from the output (they block base64-based exfiltration though) and the format is `v1.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`; the part after `v1.` is 40 characters long, the same length as regular personal access tokens. However, after some testing, you can't use this token without the `v1.` in front of it without getting 401 unauthorized.

The regex needs to be updated to allow the period.

https://github.com/electron-userland/electron-builder/blob/ebbd9f796e2d8d5b0720b2b699ba24dc159ee692/packages/builder-util/src/util.ts#L267

**Comment by judge2020** [comment]
For a temporary, cross-platform fix, a step like this should allow the new token format to work. Since sed exits with code `0` even if no replacement occurred, this won't break when the PR is merged.

```yml
      - name: Temporarily fix electron-builder
        run: |
          sed -i 's/\^\[\\w/\^\[.\\w/g' node_modules/builder-util/out/util.js
        shell: bash
```

**Comment by nathany** [comment]
thanks

**Comment by stephan-nordnes-eriksen** [comment]
@judge2020 :

On MacOS you need the following syntax for sed to work

```yaml
- name: Temporarily fix electron-builder
  run: |
    sed -i '' 's/\^\[\\w/\^\[.\\w/g' node_modules/builder-util/out/util.js
  shell: bash
```
