### ISSUE TITLE
Electron-builder ignoring package.json build tag.

### ISSUE THREAD

**Issue by davimello28** [electron-userland/electron-builder#4180]
* **Version**: 21.2.0
* **Target**: win, portable
* **OS**: Linux Debian 10 (I think this is important). 

I was unable to use the `"build"` tag on my package.json. It is important to mention that `electron-builder -w portable` works as expected. 

Here is my `package.json`:
```json
{
 ...
  "scripts": {
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "postinstall": "electron-builder install-app-deps"
  },
  "build": {
    "appId": "nonames.sad",
    "productName": "noluck",
    "win": {
      "target": [
        "portable"
      ]
    }
  }
}
```
...which wrongly produces:
```
  • packaging       platform=linux arch=x64 electron=6.0.2 appOutDir=dist/linux-unpacked
  • building        target=snap arch=x64 file=dist/emissor-boletos_1.0.0_amd64.snap
  • building        target=AppImage arch=x64 file=dist/noluck-1.0.0.AppImage
```

I've tried to search for this issues and found some others having similar problems. 

#4075, #3612, #1410

#3543 - I've tested with some other builds included (Ex: `nsis`). It does not work also. 

Curiously, the `builder-effective-config.yaml` seems to be interpreted correctly:
```yml
directories:
  output: dist
  buildResources: build
appId: nonames.sad
productName: noluck
win:
  target: portable
electronVersion: 6.0.2
```
and the DEBUG shows me exactly the line that is passing the wrong argument:

```
• spawning        command=.../node_modules/app-builder-bin/linux/x64/app-builder unpack-electron --configuration [{"platform":"linux","arch":"x64","version":"6.0.2"}] --output .../dist/linux-unpacked --distMacOsAppName Electron.app
```

Here is the full debug:
```
  • electron-builder  version=21.2.0 os=4.19.0-5-amd64
  • loaded configuration  file=package.json ("build" field)
  • effective config  config=
                        directories:
                          output: dist
                          buildResources: build
                        appId: nonames.sad
                        productName: noluck
                        win:
                          target: portable
                        
  • writing effective config  file=dist/builder-effective-config.yaml
  • spawning        command=[...]/node_modules/app-builder-bin/linux/x64/app-builder node-dep-tree --dir [...]
  • exited          command=app-builder code=0 pid=4527 out=[]
  • spawning        command=[...]/node_modules/app-builder-bin/linux/x64/app-builder rebuild-node-modules cwd=[...]
  • no native dependencies  
  • exited          command=app-builder code=0 pid=4532
  • packaging       platform=linux arch=x64 electron=6.0.2 appOutDir=dist/linux-unpacked
  • spawning        command=[...]/node_modules/app-builder-bin/linux/x64/app-builder unpack-electron --configuration [{"platform":"linux","arch":"x64","version":"6.0.2"}] --output [...]/dist/linux-unpacked --distMacOsAppName Electron.app
```

## Things I've tested

I spent my day full on this issue:

- Providing a YML file instead of JSON.
- Inputing more than one tag.

**Comment by davimello28** [comment]
Another test that I did was extracting the `builder-effective-config.yaml` from `/tests` inside the repo and use it to run as my `electron-builder.yml`.

Here is the `builder-effective-config.yaml` exported from:
```bash
TEST_FILES="portableTest"
node ./test/out/helpers/runTests.js
```

```yaml
directories:
  output: dist
  buildResources: build
electronVersion: 6.0.0
appId: org.electron-builder.testApp
compression: store
npmRebuild: false
mac:
  category: your.app.category.type
  identity: null
linux:
  category: Development
deb:
  packageCategory: devel
squirrelWindows:
  iconUrl: 'https://raw.githubusercontent.com/szwacz/electron-boilerplate/master/resources/windows/icon.ico'
nsis:
  artifactName: '${productName}Installer.${version}.${ext}'
  installerIcon: foo test space.ico
portable:
  requestExecutionLevel: admin
  artifactName: '${productName}Portable.${version}.${ext}'
```
 
And again...this was the result:
```
  • electron-builder  version=21.2.0 os=4.19.0-5-amd64
  • loaded configuration  file=[...]/electron-builder.yml
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=linux arch=x64 electron=6.0.0 appOutDir=dist/linux-unpacked
  • building        target=snap arch=x64 file=dist/emissor-boletos_1.0.0_amd64.snap
  • building        target=AppImage arch=x64 file=dist/emissor-boletos-1.0.0.AppImage

```
