### ISSUE TITLE
Electron builder ignores Cache directory

### ISSUE THREAD

**Issue by arkaydeus** [electron-userland/electron-builder#4267]
* **Version**: ^21.2.0
* **Target**: Windows

ELECTRON_BUILDER_CACHE has been set. I also have a cache folder in my project and used the local app data cache folder. Despite the fact that winCodeSign-2.5.0.7z has been downloaded there, is unpacked and both the 7z and unpacked contents are also ina  folder called winCodeSign in the cache folders, the builder still tries (and fails) to download from github and then falls over.

I've behind a proxy, but I have setup proxy environment variables HTTPS_PROXY, which seem to be ignored.

**Comment by dantevisser** [comment]
Had the same or similar issue, spent quite some time trying to make it work.

I think this code https://github.com/develar/app-builder/blob/c87157ae504895a7e9e1329437293846b8e57beb/pkg/download/artifactDownloader.go#L195
isn't getting the env vars `ELECTRON_BUILDER_CACHE` & `ELECTRON_CACHE` and then it falls back on the code in above method to determine a cache dir.

Not sure if it's got something to do with how app-builder is being executed.

Anyway, the actual caching itself does seem to work when I set both variables above and also set the config option in electron-builder.json (probably not needed but w/e):
```
  "electronDownload": {
    "cache":"${env.ELECTRON_CACHE}"
  }
```

Might not be related to your scenario, but maybe it helps someone. If you build in a container you can do something early on in the dockerfile like:
```
COPY package.json package-lock.json /app/
RUN npm install && npx electron-builder build --windows --x64 --ia32 || true
```

It's pretty hacky but electron-builder will download all its binaries before it fails and they'll get saved in that layer.

If you change package.json it's invalidated again, but still saves quite a lot of time for me.

**Comment by AxelTerizaki** [comment]
I happen to have the same problem but without proxy, from a gitlab-runner CI.

I've put this in my gitlab-ci.yml file : 

```YAML 
cache:
  key: km-app-${CI_COMMIT_REF_SLUG}
  paths:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
```

Inside the step I'm using electron-builder in 👍 
```YAML
  variables:
    ELECTRON_CACHE: ~/.cache/electron
    ELETCRON_BUILDER_CACHE: ~/.cache/electron-builder
```

I tried $HOME instead of ~ there but it didn't change anything. 

For some reason electron-builder redownloads its binaries every time.

Is there any way to fix this?

**Comment by GeneralUltra758** [comment]
same issue with gitlab CI
even tried setting them globally in gitlab ci variables.
keep getting
```
 Creating cache default...
 node_modules/: found 7038 matching files           
 WARNING: /root/.cache/electron/: no matching files 
 WARNING: /root/.cache/electron-builder/: no matching files 
```

**Comment by GeneralUltra758** [comment]
@AxelTerizaki i may have found a solution here, it appeard that gitlab ci doesnt "see" those folders for some reasson?
so i tried setting
```yml
variables:
  ELECTRON_CACHE: ".cache/electron"
  ELECTRON_BUILDER_CACHE: ".cache/electron-builder"
```
which would put the cache at working directory (same as node_modules) which caches fine for me

and then set the cache to:
```yml
cache:
  paths:
    - node_modules/
    - .cache/electron/
    - .cache/electron-builder/
```
which finally showed me 

```
Creating cache default...
 node_modules/: found 7038 matching files           
 .cache/electron/: found 4 matching files           
 .cache/electron-builder/: found 698 matching files 
```
