### ISSUE TITLE
GH_Token 

### ISSUE THREAD

**Issue by Ludea** [electron-userland/electron-builder#4549]
* **Version**: 
22.1.0

* **Target**: 
Windows

Hello,
I have an app into public GH repo.
I would like to use Appveyor as ci. 
I use this yaml :
```
image: Visual Studio 2019

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 10

cache:
  - '%LOCALAPPDATA%/Yarn'
  - node_modules
  - app/node_modules
  - flow-typed
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - yarn

test_script:
  - yarn package-ci
  #- yarn lint
  # - yarn flow
  #- yarn test
  - yarn build-e2e
  # - yarn test-e2e


```
I also set this variable into `package.json`
```
"build": {
  "publish": {
      "provider": "github",
      "owner": "Ludea",
      "repo": "myrepo",
      "private": false
    }
  },
```

It's from https://github.com/electron-react-boilerplate/electron-react-boilerplate. 
Command `yarn package-ci` is : `yarn postinstall && yarn build && electron-builder --publish always`.
But ci fail because I don't set GH_TOKEN. So I can not release my app to GH.
Public GH repo need GH_TOKEN too ?
