### ISSUE TITLE
Add parts to snapcraft.yaml

### ISSUE THREAD

**Issue by Guilain** [electron-userland/electron-builder#4595]
* **Version**:  20.44.4

* **Target**: linux snap

Hello,

I try to make a kiosk app using https://tutorials.ubuntu.com/tutorial/electron-kiosk running under Ubuntu Core.

Questions are : 
1. How to add parts ?
```yaml
    desktop-gtk3:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: gtk
        plugin: make
        make-parameters: ["FLAVOR=gtk3"]
        build-packages:
            - build-essential
            - libgtk-3-dev
        stage-packages:
            - libxkbcommon0  # XKB_CONFIG_ROOT
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - adwaita-icon-theme
            - gnome-themes-standard
            - shared-mime-info
            - libgtk-3-0
            - libgdk-pixbuf2.0-0
            - libglib2.0-bin
            - libgtk-3-bin
            - unity-gtk3-module
            - libappindicator3-1
            - locales-all
            - xdg-user-dirs
            - ibus-gtk3
            - libibus-1.0-5

    xwayland-kiosk-helper:
        plugin: cmake
        source: https://github.com/MirServer/xwayland-kiosk-helper.git
        build-packages: [ build-essential ]
        stage-packages: [ xwayland, i3, libegl1-mesa, libgl1-mesa-glx ]
```
2. How to change and add "apps" ?
```yaml
apps:
    electron-hello-world-kiosk:
        command: desktop-launch xwayland-kiosk-launch "$SNAP/electron-helloworld/electron-quick-start" "--no-sandbox"

    daemon:
        daemon: simple
        restart-condition: always
        command: desktop-launch xwayland-kiosk-launch "$SNAP/electron-helloworld/electron-quick-start" "--no-sandbox"
```

Maybe i should use snapcraft manually ?
Thanks for your help :)
