### ISSUE TITLE
electron-builder silently exits when building on Windows

### ISSUE THREAD

**Issue by mattstrom** [electron-userland/electron-builder#4859]
* **Version**: 22.4.1

* **Electron Version**: 8.0.1
* **Electron Type (current, beta, nightly)**: current
Which version of electron-updater are you using (if applicable)? 4.2.0

* **Target**: AppX

When I attempt to build my Electron app for Appx, which has to be done on a Windows machine, `electron-builder` will silently exit when the _electron-builder.js_ file is present in the project directory. Furthermore, when I run the command `npx electron-builder` from within VS Code on Windows (Powershell terminal), curiously Windows asks which application I would like to use to edit the file. After choosing "VS Code", VS Code will open the _electron-builder.js_ file for editing.

The only remedy that I have found so far is to rename _electron-builder.js_ to another name, such as _electron-builder.win.js_ and run `electron-builder` with an explicit configuration file. The file must be renamed; duplicating _electron-builder.js_ so that it still exists will cause the command to still fail silently.

I have tried this on both a physical Windows 10 machine and on Azure Pipelines with a Windows 10 image. For your convenience, I included my pipelines configuration file below.

```
# azure-pipelines.yml

trigger:
  tags:
    include:
      - "*"

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm run build
    displayName: 'Build code'

  # Possible bug with electron-builder: command silently exits when electron-builder.js exists
  - script: |
      ren electron-builder.js electron-builder.win.js
      npx electron-builder --win=appx --config=electron-builder.win.js --publish=onTag
    displayName: 'Build and publish Electron'
```
