### ISSUE TITLE
How to check new version from Github and download from Amazon s3 bucket?

### ISSUE THREAD

**Issue by ZaneCQ** [electron-userland/electron-builder#4876]
* **Version**: 
    "electron": "5.0.10",
    "electron-builder": "^21.2.0",
    "electron-updater": "^4.0.6",

* **Target**: 
    - dmg
    - zip
    - nsis
    - deb
    - appImage

Hi.
I am working on Electron-builder, and I published my application to both Github and Amazon S3. Now, I want to make the auto-updater check the latest version of my app from Gitub, and download the artifact from my S3 bucket to auto update. How can I make it works?
My config is :
```
publish:
  - provider: s3
    bucket: <My bucket >
    region: us-west-2
    acl: public-read
    path: /releases/${version}/
  - provider: github
    owner: <owner>
    repo: <repo>
```
