### ISSUE TITLE
Travis CI build for linux, macOS and Windows not working

### ISSUE THREAD

**Issue by futurelucas4502** [electron-userland/electron-builder#4882]
* **Version**: 22.4.1

* **Electron Version**: 12 but the .travis.yml uses 10
* **Electron Type (current, beta, nightly)**: current

* **Target**: all

So I'm on windows and want to build for Windows, Linux and macOS at once and came across Travis CI and made an account and used the following configuration but get an error about `docker: poorly formatted environment: variable has white spaces.` however i fixed this using [this](https://github.com/electron-userland/electron-builder/issues/2450#issuecomment-421586518) however now when it runs it fails with `yarn release` not being a command but I'm using the template so can someone fix this?

https://www.electron.build/multi-platform-build#sample-travisyml-to-build-electron-app-for-macos-linux-and-windows

How can I fix this/build for all using windows?

**Comment by Markkop** [comment]
Same here. My workaround was setting docker env with `-e GH_TOKEN=$GH_TOKEN` such as in
```
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -e GH_TOKEN=$GH_TOKEN \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn release"
    else
      echo 'other build method'
    fi
```

**Comment by futurelucas4502** [comment]
I ended up just building for MacOS and windows as I had issues about the snapstore I use this code:
```
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "12"

script:
  - npm install
  - npm run win-mac
  - cd dist
  - rm -rf win-unpacked
  - rm -rf mac
  - cd ..
  - find dist -type f -exec curl --ftp-create-dirs -T {} ftp://$FTP_USER:$FTP_PASS@$FTP_SERVER/public_html/release/ \;

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
```
