### ISSUE TITLE
Can't build on Github Actions

### ISSUE THREAD

**Issue by hmt** [electron-userland/electron-builder#4883]
* **Version**: 22.5.1

* **Electron Version**: 8.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS, Linux and Windows

When building via GH Action the script exits with a build failure, the last message says:

      ⨯ GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"

It used to work before on GH Actions (if that information helps :S ) and it still works locally on my Mac.

My repo with said action is here: https://github.com/hmt/bangbib/runs/595956659

**Comment by MrCandle** [comment]
Same here with a windows agent.

**Comment by EpohSiEreht** [comment]
I'm having the same issue as well, but on multiple different versions of electron-builder and electron. All of my electron apps were previously working and allowed me to publish the release to Github, but it stopped working after I updated to macOS 10.15.4.

I've tried resolving it with the solutions from these previous issues, but none of them work.

- https://github.com/electron-userland/electron-builder/issues/3792
- https://github.com/electron-userland/electron-builder/issues/2785

**Comment by gordonpn** [comment]
A temporary workaround that I'm using for my Electron app is adding the token to the publish step:

```
- name: Publish
  run: |
    npm run dist
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by b-zurg** [comment]
> A temporary workaround that I'm using for my Electron app is adding the token to the publish step:
> 
> ```
> - name: Publish
>   run: |
>     npm run dist
>   env:
>     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> ```

If I'm not incorrect this isn't a temporary workaround but the proper way of setting environment variables for github actions.

**Comment by b-zurg** [comment]
May I also point your attention to this cool action that someone created: https://github.com/marketplace/actions/electron-builder-action

It should allow for what you need, though I haven't tried it yet

**Comment by varkao** [comment]
## If your project is private (requires GH_TOKEN)

1. Generate a new [Personal access token](https://github.com/settings/tokens).
2. Create a repository secret from your repository settings with the name **GH_TOKEN** and the value being your token.
![image](https://github.com/electron-userland/electron-builder/assets/69709927/f5387345-e007-4d37-b53b-41dc3e3f6325)

3. Use the following commands sequentially in your workflow YAML file to set environment variables:
```yaml
- run: |
    npm run publish
  env:
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
```

## Using GITHUB_TOKEN

If your project is public or you have appropriate permissions, you can use **GITHUB_TOKEN** directly. GitHub automatically creates this token for you.

```yaml
- run: |
    npm run publish
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## Example Workflow

This workflow is designed to work for all releases. It is organized to run only one command, which can perform any necessary actions. This approach simplifies the workflow and enables the use of conditions and other functions easily.

```yaml
name: Publish release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: |
        npm run publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
```
