### ISSUE TITLE
Notarization works for .dmg not .pkg

### ISSUE THREAD

**Issue by stevenroussey-privicy** [electron-userland/electron-builder#5103]
"electron": "^9.0.5",
    "electron-builder": "^22.7.0",
    "electron-notarize": "^1.0.0",

MacOS .pkg

I have electron-builder creating and notarizing just fine... for `XXXX.dmg` files. On the same build, the `XXXX.pkg` files give the "XXXX can’t be opened because Apple cannot check it for malicious software. .... This software needs to be updated. Contact the developer for more information."

```yml
mac:
  category: public.app-category.utilities
  hardenedRuntime: true
  icon: ./resources/AppIcon.icns
  entitlements: ./resources/entitlements.mac.inherit.plist
  entitlementsInherit: ./resources/entitlements.mac.inherit.plist
  target:
    - dmg
    - zip
    - pkg
mas:
  type: distribution
  hardenedRuntime: false
  provisioningProfile: ./resources/embedded.provisionprofile
  entitlements: ./resources/entitlements.mas.plist
  entitlementsInherit: ./resources/entitlements.mas.inherit.plist
  asarUnpack:
    - '**/*.node'
masDev:
  type: development
  provisioningProfile: ./resources/MASDevelopment.provisionprofile
dmg:
  contents:
    - x: 140
      y: 180
      type: file
    - x: 490
      y: 180
      type: link
      path: /Applications
```

and later:

```
npx electron-builder build --mac --publish always
npx electron-builder build --mac mas --publish never
```
