### ISSUE TITLE
AutoUpdate Incorrectly Defaulting To GitHub Repo For Updates

### ISSUE THREAD

**Issue by cheynewallace** [electron-userland/electron-builder#5117]
* **Version**:  22.7.0
* **Electron Version**: 6.1.11
* **Target**:  Linux  x64 AppImage

I'm having an issue with automatic updates and Linux AppImage builds where by the electron-updater is trying to use GitHub as the automatic update source, however i've never used GitHub as the source, nor have I ever configured it, yet it still has information about the repo and attempts to pull updates, resulting in endless errors being triggered by my exception tracking tool, as it just fails on the GET request. 

I used Digital Ocean spaces as my publish endpoint. When building apps, everything is published fine to the correct bucket etc.  The latest.yml also looks fine to me. 

The error im getting is: 
```
HttpError/tmp/.mount_vuepilygpRBz/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:84
404 Not Found "method: GET url: https://github.com/<repo removed>/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.... (rest is cut off)
```

The doco [here](https://www.electron.build/auto-update#private-github-update-repo) mentions something about the *GH_TOKEN* var being set triggers this behaviour but I dont have this set anywhere, and I build my apps inside of the `electronuserland/builder:wine` Docker containers. 

Im not sure, but I think that started after upgrading to the most recent electron builder.

My configuration is using the *electron-builder.yml* file,  here's the relevant section

```
linux:
    artifactName: vuepilot-${arch}.${ext}
    maintainer: VuePilot
    category: Utility
    icon: build/icons/icon.png
    desktop:
        Name: VuePilot
        Type: Application
        GenericName: VuePilot
    target:
        - target: appImage
          arch:
              - x64
              - armv7l

appImage:
    desktop:
        name: VuePilot
        icon: build/icons/icon.png
    publish:
        provider: spaces
        name: vuepilot-data
        region: sfo2
        channel: latest
        acl: public-read
        path: /downloads/linux
```

The latest.yml looks ok to me?
```
version: 2.1.13
files:
  - url: vuepilot-x86_64.AppImage
    sha512: ts4VorFUGgWvlBUlSpxOJY7RkOKFXKLPu2tUcpe+oljai7J1xWNWS+sBVqBJbgNGKR/nCg4tmj5i4eNanDvbhg==
    size: 72259539
    blockMapSize: 75751
path: vuepilot-x86_64.AppImage
sha512: ts4VorFUGgWvlBUlSpxOJY7RkOKFXKLPu2tUcpe+oljai7J1xWNWS+sBVqBJbgNGKR/nCg4tmj5i4eNanDvbhg==
releaseDate: '2020-07-03T07:40:16.037Z'
```

What am I missing here?  
It seems to completely ignore my publish settings and keep searching for a private GitHub repo.  Im not even sure how it knows the path to my github repo (it's correct) 

Here's the rest of the stacktrace

```
HttpError 404 Not Found
"method: GET url: https://github.com/<repo removed>/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "40",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Fri, 03 Jul 2020 07:36:33 GMT",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "server": "GitHub.com",
  "set-cookie": [
    "_gh_sess=rzpmnXLP1h6ylivMzqOg9fMjzqL75eGCKlf%2BFynP%2FKTHZCthX6d%2Fnn3eSYUNAQ34OfQwyzwNghG181Wf6Rrt29%2F0%2BFaXwHjq19q%2BhH5Xa1KCtdnyRN9KHNak7iUuY8vIchLw61VkCWHAjmolPXOWh1QmrhYHU1AqdDfb2s2vvoPD1GjKImLH%2BkEaVmE8rKiA7xskFdbrJvQyQBJQrJyhUuzP1sxTWQ2ASKuIsnIqPn7Ij3ScxZTPLke9DvUFON9d%2FL%2F1qVPGXQ%2FkI7a93gKvLQ%3D%3D--BH2YqQisNF9MYvcK--6iGNqr3zAA3DaAlnBFuZJA%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",
    "_octo=GH1.1.1336461769.1593761793; Path=/; Domain=github.com; Expires=Sat, 03 Jul 2021 07:36:33 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Sat, 03 Jul 2021 07:36:33 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "status": "404 Not Found",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "B90A:1358:3F52ED:75FE15:5EFEE001",
  "x-xss-protection": "1; mode=block"
} 
    /tmp/.mount_vuepilygpRBz/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:84:10 createHttpError
    /tmp/.mount_vuepilygpRBz/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:169:14 ElectronHttpExecutor.handleResponse
    /tmp/.mount_vuepilygpRBz/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:134:16 ClientRequest.<anonymous>
    events.js:200:13 ClientRequest.emit
    domain.js:471:20 ClientRequest.EventEmitter.emit
    /tmp/.mount_vuepilygpRBz/resources/electron.asar/browser/api/net.js:221:18 URLRequest.<anonymous>
    events.js:200:13 URLRequest.emit
    domain.js:471:20 URLRequest.EventEmitter.emit
    domain.js:126:23 URLRequest.topLevelDomainCallback
```
