### ISSUE TITLE
Is it possible to separate the build and publishing steps?

### ISSUE THREAD

**Issue by wmhilton** [electron-userland/electron-builder#5192]
I've read through https://github.com/electron-userland/electron-builder/issues/1102#issuecomment-271845854 and https://www.electron.build/#pack-only-in-a-distributable-format but it's still clear as dirt to me. What I want is a 3-step CI workflow like this:

```yaml
jobs:
  - build                # Step 1: make .exe, .dmg, etc and save as CircleCI artifacts and / or cache them
  - allow_publish:       # Step 2: QA tests out .exe, .dmg and approves them
      type: approval
      requires: [build]
  - publish:             # Step 3: the .exe, .dmg, etc from the `build` step get published.
      requires: [allow_publish]
```

But I don't see how to run `electron-builder --publish` so that it re-uses the already built .exe, .dmg, etc.
