### ISSUE TITLE
YAMLException: unknown tag !<?>

### ISSUE THREAD

**Issue by rasgo-cc** [electron-userland/electron-builder#5234]
* **Version**: 4.3.4

* **Electron Version**: 9.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  win

Im getting this error when starting a packed app on Windows and I have no idea where to look for. 
Screenshot: http://prntscr.com/u1hxpo
```
Unhandled Promise Rejection
YAMLException: unknown tag !<?> at line 1, column 9:
    provider: spaces
            ^
```

All yaml configurations look fine (local and the update ones sent to the provider - spaces). I'm using spaces from Digital Ocean and I'm using a JS file for configuration.

```
$ touch electron-builder.js

const dayjs = require("dayjs");

module.exports = {
  appId: "APPID",
  productName: "APP",
  buildVersion: dayjs().format("YYYYMMDD"),
  directories: {
    app: "./build/",
    output: "./dist/",
  },
  nsis: {
    oneClick: false,
    allowToChangeInstallationDirectory: true,
    installerIcon: "icon.ico",
    installerHeaderIcon: "icon.ico",
    artifactName: "${productName} Setup ${buildVersion}.${ext}",
  },
  publish: {
    provider: "spaces",
    region: "fra1",
    name: "asd",
    path: "app/v2/beta",
    channel: "beta",
  },
};
```

Same results when using a similar configuration (just without the buildVersion field), using the `package.json`.

`app-update.yml` is as follows:
```
provider: spaces
region: fra1
name: asd
path: /app/v2/beta
updaterCacheDirName: app-updater
publisherName:
  - MyOwnName
```

`builder-effective-config.yaml`
```
directories:
  output: ./dist/
  buildResources: build
  app: ./build/
appId: APPID
productName: APP
nsis:
  installerIcon: icon.ico
  installerHeaderIcon: icon.ico
  artifactName: '${productName} Setup ${buildVersion}.${ext}'
publish:
  provider: spaces
  region: fra1
  name: asd
  path: /app/v2/beta
electronVersion: 9.2.0

```
I'm using webpack to bundle my electron app, in case that matters.

Any ideas what might be happening?
