### ISSUE TITLE
nsis vs squirrel exe sizes

### ISSUE THREAD

**Issue by noririco** [electron-userland/electron-builder#5251]
* **Electron Version**:
* **Electron Type (current, beta, nightly)**:

* **Version**: 
```
  "dependencies": {
   ...
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
   ...
    "electron": "^7.3.2",
    "electron-builder": "^22.8.0",
    "electron-packager": "^14.2.1",
    "electron-reload": "^1.4.0",
    "electron-updater": "^4.3.4",
    "electron-winstaller": "^3.0.4",
```

* **Target**: 
NSIS / SQUIRELL

my electron-builder.yml
```yml
appId: "com.electron.ssw"
files:
  - "ssw-electron/main.js"
  - "dist/**/*"
  
directories:
  buildResources: "dist"
  output: "ssw-electron-release/"

# Windows configuration
win:
  artifactName: ${name}-${version}-${arch}.${ext}
  verifyUpdateCodeSignature: false
  icon: "src/sswicon255.ico"
  target:
    - "nsis"

# Config for the windows installer
nsis:
  oneClick: false
  perMachine: false
```

couple of issues:

`npm run electron:dist` outputs:

  • packaging       platform=win32 arch=x64 electron=7.3.2 appOutDir=ssw-electron-release\win-unpacked
  • building        target=nsis file=ssw-electron-release\ssw-0.0.86.exe archs=x64 oneClick=false perMachine=false
  • **building block map  blockMapFile=ssw-electron-release\ssw-0.0.86.exe.blockmap**

### 2. the final .exe size is around 1.7G (!!!!) -- is this normal for "nsis"  ? 

just for comparison if I use my old build with squirell the final .exe is around 500MB (!!!)

my old build uses `electron-packager` and `electron-winstaller`
package.json
```
...
"electron-package": "electron-packager . --platform=win32 --ignore=installers --icon=./src/sswicon.ico --asar --prune=false --overwrite",
"electron-installer": "node installers/windows/createinstaller.js",
"electron-setup": "npm run electron-prod && npm run electron-package && npm run electron-installer",
"electron:pack": "electron-builder --dir",
"electron:dist": "electron-builder",
```
`createinstaller` will use squirrel 

I would love for any suggestion related to any part of my code, I just try to refine my electron build process and this library seems to be the future..

Thanks.
