### ISSUE TITLE
Getting issue with better-sqlite3 

### ISSUE THREAD

**Issue by csgour** [electron-userland/electron-builder#5317]
I am new to electron development so i need help

Following versions of dependencies i am using and also tried latest versions:
```
"electron-builder": "^22.8.0",
"better-sqlite3": "^7.1.0",
"electron": "^9.0.4",
"electron-updater": "^4.3.5",
```

Targeting Window and tried below scripts in package.json

```
  "scripts": {   
     "rebuild": "electron-rebuild -f -w better-sqlite3",
    "build": "electron-builder --config=electron-builder.yml build --win --x64 --ia32 --publish never",
    "testBuild": "electron-builder --config=electron-builder.yml build --win --x64 --publish never",
    "deploy": "electron-builder --config=electron-builder.yml build --win --x64 --ia32 --publish always",
    "postinstall": "electron-builder install-app-deps"
  },

"dependencies": {
    "@progress/kendo-ui": "^2020.2.617",
    "@syncfusion/ej2": "^18.1.59",
    "ajv": "^6.12.3",
    "axios": "^0.19.2",
    "better-sqlite3": "^7.1.1",
    "electron-json-storage": "^4.2.0",
    "electron-squirrel-startup": "^1.0.0",
    "electron-updater": "^4.3.5",
    "is-online": "^8.4.0",
    "jquery": "^3.5.1",
    "jsrender": "^1.0.6",
    "material-datetime-picker": "^2.4.0",
    "materialize-css": "^1.0.0-rc.2"
  },
  "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.52",
    "@electron-forge/maker-deb": "^6.0.0-beta.51",
    "@electron-forge/maker-rpm": "^6.0.0-beta.51",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.51",
    "@electron-forge/maker-zip": "^6.0.0-beta.51",
    "electron": "^9.0.4",
    "electron-builder": "^22.8.0",
    "electron-wix-msi": "^2.2.0"
  }
```
electron-builder.yml : 

```
appId: com.example.myTestApp
directories:
  output: dist
  buildResources: build

nsis:
  allowToChangeInstallationDirectory: true
  oneClick: false
  perMachine: false

win:
  target:   
    - target: nsis
  icon: ./icons/logo.png   
  
mac:
  icon: ./icons/icon.icns
  target:
    - target: dmg
    - target: zip

  hardenedRuntime: true
  gatekeeperAssess: false
  entitlements: build/macos/entitlements.mac.plist
  entitlementsInherit: build/macos/entitlements.mac.plist

dmg:
  sign: false

linux:  
  target:
    - target: deb
    - target: tar.gz
    - target: snap

asar: true

publish:
  provider: github
  token: xxxxxxxxx
```

Error i am getting while packaging the app for windows 
```
rebuilding native dependencies  dependencies=better-sqlite3@7.1.1 platform=win32 arch=x64
install prebuilt binary  name=better-sqlite3 version=7.1.1 platform=win32 arch=x64
build native dependency from sources  name=better-sqlite3
                                          version=7.1.1
                                          platform=win32
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.5
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ C:\Users\AppData\Roaming\npm-cache\_prebuilds\b9e817-better-sqlite3-v7.1.1-electron-v80-win32-x64.tar.gz
    prebuild-install http request GET https://github.com/JoshuaWise/better-sqlite3/releases/download/v7.1.1/better-sqlite3-v7.1.1-electron-v80-win32-x64.tar.gz
    prebuild-install http 404 https://github.com/JoshuaWise/better-sqlite3/releases/download/v7.1.1/better-sqlite3-v7.1.1-electron-v80-win32-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=9.3.1 runtime=electron arch=x64 libc= platform=win32)
```

database error when open the app[Please check the image available on url]

https://www.dropbox.com/s/0e5nxq736h27tu1/sqliteError.png?dl=0[](url)
