### ISSUE TITLE
How to deliver packages from server

### ISSUE THREAD

**Issue by pedro-surf** [electron-userland/electron-builder#5334]
* **Version**: 22.2.0
* **Electron Version**: 9.2.0
**Electron-Updater**: (not implemented)

* **Target**:  Mac, nsis-web (windows --ia32 and --x64)

Can I serve installer packages remotely from a server, just like in autoUpdater? If yes, perhaps I didn't find it on docs.

After building, my build directory looks like this:

- 1 small (620kb) .exe file 
- 2 .nsis files which are about 200MB each 
-  latest.yml

![image](https://user-images.githubusercontent.com/40304742/95401318-48635580-08e3-11eb-894b-067e2b29724c.png)

Ideally, you'd like users to download/get only this tiny setup EXE.
 
Is it already possible to configure latest.yml to fetch these files from a CDN or any server?

My latest.yml looks like this:

```
version: 2.0.0
files:
  - url: Mysoftware.exe
    sha512: ... 
path: Mysoftware.exe
sha512: ...
packages:
  x64:
    size: ..
    sha512: ...
    blockMapSize: 221961
    path: mysoftware-2.0.0-x64.nsis.7z
    file: mysoftware-2.0.0-x64.nsis.7z
releaseDate: '2020-10-08T00:00:08.688Z'

```

Inside packages, I want to replace path (pkgs > path) for an URL and be able to fetch.
Thanks for this great lib!
