### ISSUE TITLE
[Snap]: can not specify slot details

### ISSUE THREAD

**Issue by feugy** [electron-userland/electron-builder#5339]
* **Version**: 22.8.1
* **Electron Version**: 10.1.2
* **Electron Type (current, beta, nightly)**: current
* **Target**: Linux Snap

An application can use the [MediaMetadata](https://developer.mozilla.org/en-US/docs/Web/API/MediaMetadata) JavaScript API for the OS so wire the media controls of keyboards (play, next, previous) and to display current media information (image, name, description) in OS notification area.

When running the snap in devmode or with classic confinement, Linux can interact with the player controls.
But when using strict confinement, Linux can not.
The snappy-debug tool spot the issue pretty quickly:
```
= AppArmor =
Time: Sep 26 20:57:04
Log: apparmor="DENIED" operation="dbus_bind"  bus="session" name="org.mpris.MediaPlayer2.chromium.instance38417" mask="bind" pid=38417 label="snap.melodie.melodie"
DBus access
Suggestion:
* use 'mpris' slot (https://github.com/snapcore/snapd/wiki/Interfaces#mpris)
```

The correct definition in snap file should be:
```yaml
apps:
  sep:
    plugs: []
    # electron-builder already gives control on this part
    slots: [mpris]
  # electron-builder does not support slot details.
  slots: 
    mpris:
      interface: mpris
      name: chromium
```

Electron-builder let users specify slot names (mpris), however they can not specify slot details (interface/name) as they can do for plugs.
