### ISSUE TITLE
Codesign issue preventing development mac builds from opening unless re-signed

### ISSUE THREAD

**Issue by fbcouch** [electron-userland/electron-builder#5347]
* **Version**: 22.9.1

* **Electron Version**: 10.1.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac

For the following configuration:
```yaml
appId: "com.myapp.staging"
productName: "MyApp Staging"
icon: ./build/icon.png
directories:
  output: dist
  buildResources: build
  app: .

mac:
  provisioningProfile: build/MyApp_Staging_macOS_Development.provisionprofile
  type: development
  identity: Jami Couch
  gatekeeperAssess: false
  target:
    - dmg
```

Building as such:

```
$ yarn electron-builder --config=electron-builder.staging.dev.yml -m
yarn run v1.22.4
$ /Users/jami/projects/my-app/my-app-electron/node_modules/.bin/electron-builder --config=electron-builder.staging.dev.yml -m
  • electron-builder  version=22.9.1 os=19.6.0
  • loaded configuration  file=/Users/jami/projects/my-app/my-app-electron/electron-builder.staging.dev.yml
  • Specified application directory equals to project dir — superfluous or wrong configuration  appDirectory=.
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=10.1.3 appOutDir=dist/mac
  • signing         file=dist/mac/MyApp Staging.app identityName=Mac Developer: Jami Couch (SGNM3S8YVK) identityHash=6CE0F33FFA0CF359662F1533EAE194FE5C9DE22F provisioningProfile=build/MyApp_Staging_macOS_Development.provisionprofile
  • building        target=DMG arch=x64 file=dist/MyApp Staging-1.0.1.dmg
  • building block map  blockMapFile=dist/MyApp Staging-1.0.1.dmg.blockmap
✨  Done in 45.31s.
```

Double clicking on `MyApp Staging.app` results in the app appearing to start opening (icon bouncing in doc), then closing with no errors/feedback at all (exit code 0).

However, if I re-sign the app as such:

```
yarn electron-osx-sign "dist/mac/MyApp Staging.app" --identity="Jami Couch" --verbose --type=development --provisioning-profile=build/MyApp_Staging_macOS_Development.provisionprofile --no-gatekeeper-assess
```

Double clicking on `MyApp Staging.app` opens the app as expected.
