### ISSUE TITLE
Auto update broken after electron update: Error: Cannot parse update info from latest.yml: YAMLException: unknown tag

### ISSUE THREAD

**Issue by thisismydesign** [electron-userland/electron-builder#5366]
* **Version**: 20.44.4 or 22.9.1

* **Electron Version**: 10.1.4
* **Electron Type (current, beta, nightly)**: current

* **electron-updater Version**: 4.0.14 or 4.3.5

* **Target**: win nsis

I updated electron from 5.0.6 to 10.1.4, didn't touch electron-builder dependencies. Now auto-update is broken:

```
[2020-10-25 16:07:29.413] [info] Checking for update
[2020-10-25 16:07:32.263] [error] Error: Error: Cannot parse update info from latest.yml in the latest release artifacts (https://github.com/<>/<>/releases/download/v1.16.2/latest.yml): YAMLException: unknown tag !<?> at line 1, column 8:
    version: 1.16.2
           ^
```

The `latest.yml` looks perfectly normal to me:
```
version: 1.16.2
files:
  - url: setup.exe
    sha512: xSfDoyNDgKhme82lnAGoKSL8jkn6Ebu0l1sd3WPoI8Q8ikkOAGsY0nYL6b55zLeZs1mlThLsx87lfE7gA4YiQg==
    size: 71629371
path: setup.exe
sha512: xSfDoyNDgKhme82lnAGoKSL8jkn6Ebu0l1sd3WPoI8Q8ikkOAGsY0nYL6b55zLeZs1mlThLsx87lfE7gA4YiQg==
releaseDate: '2020-10-25T12:10:02.288Z'
```

Tried with latest versions `"electron-updater": "^4.3.5"` and `"electron-builder": "^22.9.1"` but the result is the same.
