### ISSUE TITLE
Windows Auto update with Amazon s3

### ISSUE THREAD

**Issue by jngbng** [electron-userland/electron-builder#5412]
* **Version**:  22.9.1
* **Electron Version**: 10.1.5
* **Electron Type (current, beta, nightly)**: current
* **Target**: MacOS(dmg), Windows (NSIS)

I build my package for MacOS (DMG) and Windows (NSIS)
and publish them to S3 (auto update target) and Github (for tracking).
I also use channel as guided on [tutorial](https://www.electron.build/tutorials/release-using-channels).

Following is snippet of my package.json:

```json
{
  "build": {
    "generateUpdatesFilesForAllChannels": true,
    "win": {
      "target": "nsis",
      "icon": "./build/icon.ico"
    },
    "nsis": {},
    "publish": [
      {
        "provider": "s3",
        "acl": "public-read"
      },
      {
        "provider": "github",
      }
    ]
  }
}
```

I published using the following command:
```
electron-builder --mac --windows --publish always
```

Auto update for Mac works well, but not for Windows.
auto-update modules can detect a new update, but cannot download actual binary file. 

The problem is inconsistent filename handling for windows build. (specifically `latest.yml > files > url` field.)

The generated binary file name for Windows is like: **'${productName} Setup ${version}.${ext}'** ([default nsis setting](https://www.electron.build/configuration/nsis)).

Binary files on S3 bucket is the same as above: (spaces in filename)

<img width="549" alt="publish-s3" src="https://user-images.githubusercontent.com/552977/98689546-61ae6480-23af-11eb-8826-e89cf8f7fb0b.png">

However, generated contents of `beta.yml` seems tricky:
```
version: 0.4.5-beta
files:
  - url: BoxHero-Setup-0.4.5-beta.exe          <---------- ?!?!
    sha512: [blah]
    size: 54756560
path: BoxHero Setup 0.4.5-beta.exe
sha512: [blah]
releaseDate: '2020-11-10T13:40:07.128Z'
```

`files[0].url` is **dash-joined** instead of **space-joined**.
According to a log file, auto update module seems use that value to download file.
```
Error: Cannot download "https://....amazonaws.com/BoxHero-Setup-0.4.5-beta.exe", status 403: Forbidden
```
It should be **space-joined**.

By the way, on the Github release page, all filenames and references are **dash-joined**.
![publish-github](https://user-images.githubusercontent.com/552977/98691917-e306f680-23b1-11eb-92ba-88af16832383.png)

contents of `latest.yml` seems good as well:

```
version: 0.4.5-beta
files:
  - url: BoxHero-Setup-0.4.5-beta.exe
    sha512: YUPNo1KqDtNSxG+TRMKbe0YrsKtQ2pNGXITp2whY5oM7R1FeOpViGWiuq0tF74xQqokjM5gW9VjPMmuFVBK1PQ==
    size: 54756560
path: BoxHero-Setup-0.4.5-beta.exe
sha512: YUPNo1KqDtNSxG+TRMKbe0YrsKtQ2pNGXITp2whY5oM7R1FeOpViGWiuq0tF74xQqokjM5gW9VjPMmuFVBK1PQ==
releaseDate: '2020-11-10T13:40:07.128Z'
```

The filename here is `latest.yml` instead of `beta.yml`. (maybe correct?)

I will override `artifactName` field for NSIS til this issue is resolved.

Thanks.
