### ISSUE TITLE
Put into release win-unpacked folder as zip

### ISSUE THREAD

**Issue by JumpAttacker** [electron-userland/electron-builder#5455]
Hi!
Is it possible in publish change installer.exe for win-unpacked folder? or mb put all files into single exe file

**Comment by JumpAttacker** [comment]
nvm, i did it with git actions
```
name: CI
on:
  push:
    branches:
      # this will run on the electron branch
#      - feature/git
      - main
#  push:
#    tags:
#      - 'v*'
jobs:
  release-project:
    name: Release unpacked version of app
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    needs: build-project
    steps:
      - name: Download content
        uses: actions/download-artifact@v2
        with:
          name: my-app-win

      - name: Archive content
        uses: thedoctor0/zip-release@master
        with:
          filename: app.zip

      - name: View content
        run: ls -R

      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release V${{ github.run_number }}

      - name: Upload to github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: 'app.zip'
          asset_name: app-v.${{ github.run_number }}.zip
          asset_content_type: application/zip

  build-project:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: false

      - name: Upload Win Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: my-app-win
          path: release/win-unpacked
          retention-days: 1

      - name: see directory
        run: ls -R

```
