### ISSUE TITLE
macOS default architecture

### ISSUE THREAD

**Issue by lutzroeder** [electron-userland/electron-builder#5495]
* **Version**: 22.10.4

Pre-Apple Silicon, macOS `x64` target names default to shorter `App-X.X.X.dmg` or `App-X.X.X-mac.zip` names not including an architecture. With the addition of `arm64` and `universal` there is now code to special case these names for `x64`. Given the planned transition from `x64` to `universal` to `arm64` the default architecture is going to change and naming conflicts or workarounds are more likely to happen. For example, to transition from `x64` to `universal` the naming overrides below are needed to avoid breaking `electron-updater`:

```
dmg:
  artifactName: ${productName}-${version}.${ext}
  title: "${productName} ${version}"
mac:
  artifactName: ${productName}-${version}-mac.${ext}
```

**Proposal**

Add a `defaultArch` setting to `MacConfiguration` that specifies which default architecture is using the shorter names. If not set it will default to `x64`.

For example, `"defaultArch": "universal"` would result in `universal` targets using `App-X.X.X.dmg` or `App-X.X.X-mac.zip` while `x64` targets would be called `App-X.X.X-x64.dmg` or `App-X.X.X-x64-mac.zip`.
