### ISSUE TITLE
Updater is not generating a file for each mac architecture

### ISSUE THREAD

**Issue by 0xdeafcafe** [electron-userland/electron-builder#5548]
* **Version**: 22.10.4

* **Electron Version**: 11.1.1
* **Electron Type (current, beta, nightly)**: current
* **Electron Updater**: 4.3.5

* **Target**: mac (x64, arm), windows (ia32, x64)

I've just set up electron-builder to work with electron-updater to get auto updating working on an app I'm working on, however I'm struggling with something around updates and architecture. Note; my package.json version is currently set to `1.0.0-alpha`.

### Publishing

When the publisher runs, it creates 1 yml file for mac `alpha-mac.yml` (_full file content can be found at bottom of issue_). This file mentions all the built artefacts (zip and dmg for both x64 and arm) and then seems to reference one of them as the main file(?). My understanding is that two yml files should be generated `alpha-mac.yml` and `alpha-mac-arm.yml`, so the updater knows which one to read from? Either my assumption is incorrect (v possible), I have misconfigured the builder, or as silicon is new this issue hasn't popped up before.

### Updating

Again I'm not sure if this is an issue or if I have just mis-read the docs surrounding this, but until my app leaves alpha the version won't change from `1.0.0-alpha`. If a new build is published, my assumption would be that if the version changes, or the release date changes, then the update process is started - however I can't replicate this. If this just isn't possible, is there a way I can hook into the updating code and handling this additional logic myself?

Thanks!

<details>
  <summary>alpha-mac.yml</summary>

```
version: 1.0.0-alpha
files:
  - url: Beak-1.0.0-alpha-mac.zip
    sha512: J8QdWRCoxecPjm0g2mBZxJIX0Li99qyGpgi+TjmZV6XnVWIuDweLSBOTGZMccepYRZf/q55tuti49koe6KdgqA==
    size: 91044705
    blockMapSize: 97185
  - url: Beak-1.0.0-alpha-arm64-mac.zip
    sha512: +pL0cg8vvAnK+g+q/hT+SHxQKm4G39O3fKCLdvLFkU6OXUcc55rf50hbMMVKo45pdYZ11FRkxCq7G9cKpVEQzg==
    size: 91692105
    blockMapSize: 95997
  - url: Beak-1.0.0-alpha.dmg
    sha512: M5z8dZiKpkhtiTUqchsCKL/mHLJS/MatvSGlKEbw+eYBtr3lYewZ/eJM6UHgemElOcuWe3cdO7feJI/cFzEquA==
    size: 94878999
  - url: Beak-1.0.0-alpha-arm64.dmg
    sha512: D8rfjbLBf7blVRaSCc/7AaITlVTGoELOdynA8DiAEJM+Hdy7snzwna5sutpcnZG7sjoOJBpvY6eHOI2gsV/xLQ==
    size: 95781682
path: Beak-1.0.0-alpha-mac.zip
sha512: J8QdWRCoxecPjm0g2mBZxJIX0Li99qyGpgi+TjmZV6XnVWIuDweLSBOTGZMccepYRZf/q55tuti49koe6KdgqA==
releaseDate: '2021-01-15T19:25:52.451Z'
```
</details>
