### ISSUE TITLE
No valid export — Error with electron-builder 22.10.5

### ISSUE THREAD

**Issue by yceballost** [electron-userland/electron-builder#5641]
* **22.10.5**: 

* **9.2.0**:

I updated electron-builder dependency but now the build through this error

```
• electron-builder  version=22.10.5 os=20.3.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  ⨯ No valid exports main found for '/Users/iceballos/GitHub/mistica-manager/node_modules/js-yaml'  stackTrace=Error: No valid exports main found for '/Users/iceballos/GitHub/mistica-manager/node_modules/js-yaml'
at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
at applyExports (internal/modules/cjs/loader.js:502:14)
at resolveExports (internal/modules/cjs/loader.js:551:12)
at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
at Function.Module._load (internal/modules/cjs/loader.js:855:27)
at Module.require (internal/modules/cjs/loader.js:1033:19)
at require (internal/modules/cjs/helpers.js:72:18)
at _jsYaml (/Users/iceballos/GitHub/mistica-manager/node_modules/builder-util/src/util.ts:8:1)
at serializeToYaml (/Users/iceballos/GitHub/mistica-manager/node_modules/builder-util/src/util.ts:32:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mmaietta** [comment]
@yceballost I can get right on this.
Any chance you could share the builder-effective-config you're using? Maybe I can cover a test for this too

**Comment by yceballost** [comment]
Do you refer to this?

```
directories:
  output: dist
  buildResources: build
appId: mistica
afterSign: ./afterSignHook.js
mac:
  category: com.mistica.app
  hardenedRuntime: true
  entitlements: ./build/entitlements.mac.plist
electronVersion: 9.2.1
```
