### ISSUE TITLE
Bitbucket pipeline wine is required

### ISSUE THREAD

**Issue by theArina** [electron-userland/electron-builder#5665]
* **Version**: 22.9.1

* **Electron Version**: 11.0.0
* **Electron Type (current, beta, nightly)**: current

* **electron-updater version**: 4.2.0

* **Target**: Windows

Suddenly I got an error when I tried to run my usual pipeline on Bitbucket:

`⨯ wine is required, please see https://electron.build/multi-platform-build#linux`
`⨯ /opt/atlassian/pipelines/agent/build/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE`

The last successful result I got on 29th of December 2020. I didn't run any builds ever since until now.

My pipeline configuration looks like this:

```
image: electronuserland/builder:wine

definitions:
  steps:
    - step: &make-build
        name: Create Build
        script:
          - npm i
          - electron-builder -w
        artifacts:
          - dist/*
pipelines:
  branches:
    master:
      - step: *make-build
```

I also tried to debug the error on local machine [using docker](https://www.electron.build/multi-platform-build.html#build-electron-app-using-docker-on-a-local-machine), but got the successful results without any errors. 
I assume that Bitbucket changed something. Any clues appreciated.
