### ISSUE TITLE
Programmatic use example

### ISSUE THREAD

**Issue by fitness23** [electron-userland/electron-builder#5738]
I'm attempting to use the following to build a singe exe via the programmatic approach:

```
builder.build({
        targets: Platform.MAC.createTarget(),
        config: {
            "appId": "Test",
            "extraFiles": {
              "from": "../game/src",
              "to": "../game/madeExe"
            },
            "win": {
              "icon" : "build/images/icon.ico",
              "target": ["portable"]
            },
            "linux": {
              "icon" : "build/images/icon.png",
              "target": ["pacman"]
            }
        }
      })
        .then(() => {
            res.json({
                sucess: true
            });
        })
        .catch((error) => {
          // handle error
        })
```

It doesn't error but it doesn't make the exe either.
Is there a way to turn on error messages? And is there anything I'm missing in the config which would cause it to error?

**Comment by mmaietta** [comment]
Hi there!

Re: error logs programmatically, add: `process.env.DEBUG = 'electron-*'`

For building an exe, you have the incorrect target in your config above. It should be `targets: Platform.WINDOWS.createTarget()`. Alternatively, if you're on a Windows build machine, you could also use `Platform.current()`

**Comment by fitness23** [comment]
Hi @mmaietta ,

Thanks so much for your reply.
I changed all my code to:

```
process.env.DEBUG = 'electron-*';

    builder.build({
        targets: Platform.WINDOWS.createTarget(),
        config: {
            "appId": "Test",
            "extraFiles": {
              "from": "../game/src",
              "to": "../game/madeExe"
            },
            "win": {
              "icon" : "../game/ico/win.ico",
              "target": ["portable"]
            }
        }
      })
        .then(() => {
            res.json({
                sucess: true
            });
        })
        .catch((error) => {
          // handle error
        })
```

However it still doesn't build the exe nor does it show any debug error messages.

All it gives me is the following in the command prompt:

```
• electron-builder  version=22.10.5 os=10.0.19042
  • effective config  config=
                        directories:
                          output: dist
                          buildResources: build
                        appId: Test
                        extraFiles:
                          - from: ../game/src
                            to: ../game/madeExe
                        win:
                          icon: ../game/ico/win.ico
                          target:
                            - portable
```
