### ISSUE TITLE
Native addon not being linked/packed correctly

### ISSUE THREAD

**Issue by mithusingh32** [electron-userland/electron-builder#5745]
* **Version**: 22.3.6

* **Electron Version**: 11.2.3
* **Electron Type (current, beta, nightly)**: current

* **Target**: Linux

Mu native addon is not being packed. When I try to execute the application after building it fails to load the .node file. 
Here is the package.json file:
```
  "build": {
    "productName": "ElectronReact",
    "appId": "org.erb.ElectronReact",
    "files": [
      "audio-processor/build/Release/addon.node",
      "dist/",
      "node_modules/",
      "index.html",
      "main.prod.js",
      "main.prod.js.map",
    ],
    
    "asar": false,
```

builder-effectice-config.yam;l
```
directories:
  output: release
  buildResources: assets
  app: src
productName: ElectronReact
appId: org.erb.ElectronReact
files:
  - filter:
      - audio-processor/build/Release/*.node
      - dist/
      - node_modules/
      - index.html
      - main.prod.js
      - main.prod.js.map
asar: false
afterSign: .erb/scripts/Notarize.js
mac:
  target:
    - dmg
  type: distribution
  hardenedRuntime: true
  entitlements: assets/entitlements.mac.plist
  entitlementsInherit: assets/entitlements.mac.plist
  gatekeeperAssess: false
dmg:
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
win:
  target:
    - nsis
linux:
  target:
    - AppImage
  category: Development
extraResources:
  - filter:
      - ./assets/**
publish:
  provider: github
  owner: electron-react-boilerplate
  repo: electron-react-boilerplate
electronVersion: 11.2.3
```
