### ISSUE TITLE
MSI Build failure on Travis-CI

### ISSUE THREAD

**Issue by GeekCornerGH** [electron-userland/electron-builder#5769]
* **Version**: 22.10.5

* **Electron Version**: 12.0.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: 
Windows

So I want to build on Travis-CI to make a MSI File. I have the following Travis config:
```yml
matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      language: node_js
      node_js: "14"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true
        - CSC_IDENTITY_AUTO_DISCOVERY=false

    - os: linux
      services: docker
      language: node_js
      node_js: "14"
      mono:
        - latest
      env:
        - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ENVS=`env | grep -iE '(DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_)' | sed -n '/^[^\t]/s/=.*//p' | sed '/^$/d' | sed 's/^/-e /g' | tr '\n' ' '`
      docker run $ENVS --rm \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "node -v && npm ci && npm run cilinux"
    else
      npm run cidarwin
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
```
I have also the following electron builder file:
```js
const builder = require('electron-builder')
const Platform = builder.Platform

function getCurrentPlatform(){
    switch(process.platform){
        case 'win32':
            return Platform.WINDOWS
        case 'darwin':
            return Platform.MAC
        case 'linux':
            return Platform.linux
        default:
            console.error('Cannot resolve current platform!')
            return undefined
    }
}

builder.build({
    targets: (process.argv[2] != null && Platform[process.argv[2]] != null ? Platform[process.argv[2]] : getCurrentPlatform()).createTarget(),
    config: {
        appId: 'Galaxiat RPC',
        productName: 'GalaxiatRPC',
        artifactName: '${productName}-${version}.${ext}',
        copyright: 'Copyright © 2018-2021 GeekCorner',
        directories: {
            buildResources: 'build',
            output: 'dist'
        },
        win: {
            target: [
                {
                    target: 'msi',
                    arch: ['x64', 'ia32']
                }
            ]
        },
        msi: {
            artifactName:'${productName}-${version}-setup-${arch}.${ext}'
        },
        compression: 'maximum',
        files: [
            '!{dist,.gitignore,.vscode,docs,dev-app-update.yml,.travis.yml,.nvmrc,.eslintrc.json,build.js}'
        ],
        extraResources: [
            'libraries'
        ],
        asar: true
    }
}).then(() => {
    console.log('Build complete!')
}).catch(err => {
    console.error('Error during build!', err)
})
```
On Travis-CI console, I got the following:
```console
  • electron-builder  version=22.10.5 os=4.15.0-1077-gcp

  • artifacts will be published if draft release exists  reason=CI detected

  • packaging       platform=win32 arch=x64 electron=12.0.2 appOutDir=dist/win-unpacked

  • Unpacking electron zip  zipPath=undefined

  • downloading     url=https://github.com/electron/electron/releases/download/v12.0.2/electron-v12.0.2-win32-x64.zip size=83 MB parts=4

  • downloaded      url=https://github.com/electron/electron/releases/download/v12.0.2/electron-v12.0.2-win32-x64.zip duration=1.061s

  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1

  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=423ms

  • building        target=MSI arch=x64 file=dist/GalaxiatRPC-1.0.0-setup-x64.msi

  • packaging       platform=win32 arch=ia32 electron=12.0.2 appOutDir=dist/win-ia32-unpacked

  • Unpacking electron zip  zipPath=undefined

  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/wix-4.0.0.5512.2/wix-4.0.0.5512.2.7z size=2.2 MB parts=1

  • downloading     url=https://github.com/electron/electron/releases/download/v12.0.2/electron-v12.0.2-win32-ia32.zip size=78 MB parts=4

  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/wix-4.0.0.5512.2/wix-4.0.0.5512.2.7z duration=420ms

  • downloaded      url=https://github.com/electron/electron/releases/download/v12.0.2/electron-v12.0.2-win32-ia32.zip duration=1.474s

  • building        target=MSI arch=ia32 file=dist/GalaxiatRPC-1.0.0-setup-ia32.msi


  ⨯ cannot execute  cause=exit status 255

                    errorOut=002d:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed

                    command=wine 'Z:\home\travis\.cache\electron-builder\wix\wix-4.0.0.5512.2\candle.exe' -arch x86 '-dappDir=Z:\project\dist\win-ia32-unpacked' -pedantic -wx project.wxs

                    workingDir=

  ⨯ cannot execute  cause=exit status 255

                    errorOut=000d:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found

    000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).

    0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed

    

                    command=wine 'Z:\home\travis\.cache\electron-builder\wix\wix-4.0.0.5512.2\candle.exe' -arch x64 '-dappDir=Z:\project\dist\win-unpacked' -pedantic -wx project.wxs
```
Thank you in advance for your answer
Have a good day
