### ISSUE TITLE
mas pkg rejected in app store when using 22.10.4, works fine in 22.9.1

### ISSUE THREAD

**Issue by sangeeth96** [electron-userland/electron-builder#5801]
* **Version**: 22.10.4/22.10.5

* **Electron Version**: 12.0.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: `mas-dev`, `mas`, `zip`, `dmg`

There seems to be a problem with `mas` builds with 22.10.(4|5) which results in private APIs getting included in the framework. The build works fine in 22.9.1 and gives a proper pkg.

We recently bumped electron to v12 and bumped builder also in the process from 22.9.1 to 22.10.4. When we tried to submit the built pkg to the app store, we got rejected with the reason that we were using private APIs. The APIs listed is similar to the one over at electron/electron#28600. We verified it by running `otool -Iv Electron\ Framework` and we found the private APIs listed even though we didn't change any other configuration. Same with 22.10.5.

The builder configuration part for `mac` is as follows:

```yml
mac:
  category: public.app-category.productivity
  icon: App.icns
  artifactName: "${productName}-mac.${ext}"
  type: distribution
  gatekeeperAssess: false
  hardenedRuntime: true
  entitlements: "build/entitlements.mac.plist"
  entitlementsInherit: "build/entitlements.mac.plist"
  electronLanguages:
    - en
  extendInfo:
    CFBundleLocalizations:
      - en
    NSCameraUsageDescription: "To enable the video during the Video Call"
    NSMicrophoneUsageDescription: "To enable the audio during the Video Call"
    NSRequiresAquaSystemAppearance: false
  target:
  - zip
  - dmg
  - mas
  - mas-dev
```

and the command used to build for all the mac targets is:

```sh
yarn run electron-builder --mac -c.extraMetadata.version=$VER -c.buildVersion="$VER"
```

Here's part of the output from 22.10.4 which seems to indicate the issue. It seems to use `platform=darwin` instead of `platform=mas` for `mas` target:

```
...
• packaging platform=darwin arch=x64 electron=12.0.4 appOutDir=dist/mac
• packaging platform=darwin arch=x64 electron=12.0.4 appOutDir=dist/mas
...
```

Here's the same when we downgraded to 22.9.1 which is correct:

```
...
• packaging platform=darwin arch=x64 electron=12.0.4 appOutDir=dist/mac
• packaging platform=mas arch=x64 electron=12.0.4 appOutDir=dist/mas
...
```

We also verified with `otool` and the 22.9.1 dist doesn't have the private APIs listed. So, this seems like a bug in 22.10.(4|5) (and possibly all 22.10.x)
