### ISSUE TITLE
Duplicate fields in latest.yml output when building Windows

### ISSUE THREAD

**Issue by achou11** [electron-userland/electron-builder#6002]
* **Version**:  22.11.7

* **Electron Version**: 9.4.4
* **Electron Type (current, beta, nightly)**: current

- **electron-updater version**: 4.3.1

* **Target**: Windows (NSIS 32 and 64 bit)

Running the build step via `electron-builder --win --config ./builder.config.js` with the following windows-specific config is producing a `latest.yml` file with duplicate fields (see example output below).

```js
  // omitted the rest of the config for brevity but let me know if there are other relevant fields to include
  win: {
    target: [{ target: 'nsis', arch: ['x64', 'ia32'] }],
    artifactName: 'SOME_APP_NAME_${os}-${arch}.${ext}',
    ...
  },
```

output:

```yml
version: ...
files:
  - url: SOME_APP_NAME_win.exe
    sha512: ...
    size: ...
  - url: SOME_APP_NAME_win-x64.exe
    sha512: ...
    size: ...
  - url: SOME_APP_NAME_win-x64.exe
    sha512: ...
    size: ...
  - url: SOME_APP_NAME_win-x64.exe
    sha512: ...
    size: ...
  - url: SOME_APP_NAME_win-ia32.exe
    sha512: ...
    size: ...
  - url: SOME_APP_NAME_win-ia32.exe
    sha512: ...
    size: ...
  - url: SOME_APP_NAME_win-ia32.exe
    sha512: ...
    size: ...
path: SOME_APP_NAME_win.exe
sha512: ...
releaseDate: ...
```

You'll notice 3 occurrences of the `ia32` and `x64` metadata, each of which have matching hashes and size values for their corresponding arch. This application uses `electron-updater` and I haven't tested whether or not this affects autoupdate functionality (my hope is that it doesn't)
