### ISSUE TITLE
Hidden files (`.env`) not copied to build, regardless of glob pattern settings

### ISSUE THREAD

**Issue by zaneclaes** [electron-userland/electron-builder#6036]
* **Electron-Builder Version**:  22.11.7
* **Node Version**: 16.4.0

* **Electron Version**: 13.1.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: MacOS, Linux, Windows

Similar to https://github.com/electron-userland/electron-builder/issues/733.

My `files` configuration:
```
files:
- from: "../bin/Dist"
  to: "./"
  filter:
    "**/*"
# .env file, for runtime configuration
- from: "../"
  to: "./"
  filter:
  - "**/*.env"
  - ".env"
```

Those `.env` settings should match two files from the parent directory: `maker.env` and `.env`. However, the build output only contains the former, but omits the latter (hidden) file.

I have also tried placing the env files directly within the `../bin/Dist` folder and omitting the second file setting. In every case, the hidden file is omitted.

This is problematic for applications which rely upon **dotenv** style configuration, which uses the hidden filename by convention and cannot be changed.
