### ISSUE TITLE
building arm64 deb with gitlab ci using electronuserland/builder:wine image

### ISSUE THREAD

**Issue by charithreddyv** [electron-userland/electron-builder#6279]
* **Electron-Builder Version**: 22.8.0

* **Node Version**: app uses v13.5.0 not sure which version electronuserland/builder:wine uses or configurable.

* **Electron Version**:  ^8.2.0
* **Electron Type (current, beta, nightly)**: current!
 

* **Target**: linux, arm64, deb 

Hai There, 
i am trying to create a ci pipleline on gitlab to create arm64 deb build, i am currently using electronuserland/builder:wine image . before this i used to directly build on a arm 64 using fpm  `v1.10.2` and setting env variable `USE_SYSTEM_FPM="true"` and command like `electron-builder --linux --arm64 --config staging.json` this used to build the debs fine.
now i created a .gitlab-ci.yml file to do the same when i set `USE_SYSTEM_FPM="true"` it fails somehow,  without that the built arm images does not execute properly.
I need help in 
1. using fpm version that worked for me earlier
2. configuring node version if possible 
3. create a deb file that works on arm64 arch 
below is my pipeline yaml file 
```
image: electronuserland/builder:wine

stages:
  - build

package_staging_prod_arm:
  stage: build
  script:
    - npm install
    - npm run package-staging
  only:
    refs:
      - nightly
      - merge_requests
  artifacts:
    expire_in: 30 days
    paths:
      - ./release/*.deb
  cache:
    key: "node modules cache"
    paths:
      - node_modules
 ```

 `npm run package-staging` -> ` electron-builder --linux --arm64 --config staging.json`
 the current setup builds the dev files but they dont work when installed .
 from the logs of pipeline i can see the following fpm modules being downloaded 

```
       • building        target=deb arch=arm64 file=release/<my_app>_1.0.20_arm64.deb
        • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z size=5.0 MB parts=1
        • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z duration=350ms
```
Thanks in advance :smile:
