### ISSUE TITLE
ECHOLORD

### ISSUE THREAD

**Issue by Echo4F** [electron-userland/electron-builder#6375]
I use docker to build it.
````
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true
  displayName: 'Install Node.js'



- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker run --rm  -v ${PWD}:/project -w /project electronuserland/builder npm run dist:linux' # use your cmd
````

_Originally posted by @yynmsl in https://github.com/electron-userland/electron-builder/issues/2986#issuecomment-952550573_
