### ISSUE TITLE
Missing files from `stagePackages` in Snap packaging.

### ISSUE THREAD

**Issue by twang2218** [electron-userland/electron-builder#6424]
* **Electron-Builder Version**: `22.11.7`

* **Node Version**: `12`

* **Electron Version**: `13`
* **Electron Type (current, beta, nightly)**:

* **Target**: `snap`

As my app depends on the `ffmpeg` tools, we use `stagePackages` in `package.json` to add the dependences for `electron-builder` to explicitly specify that we need the package.

```yaml
...
    "snap": {
      "summary": "A Linux IM client for QQ and more",
      "environment": {
        "HOME": "$SNAP_REAL_HOME",
        "XDG_CONFIG_HOME": "$SNAP_USER_DATA/.config",
        "XDG_CACHE_HOME": "$SNAP_USER_DATA/.cache",
        "XDG_DATA_HOME": "$SNAP_USER_DATA/.local/share"
      },
      "stagePackages": [
        "default",
        "ffmpeg"
      ]
    },
...
```

By checking the building log, the `ffmpeg` package was indeed installed in the `snapcraft` section:

```js
Run sg lxd -c 'yarn build:electron --pd unpacked -l snap -p never'
  • electron-builder  version=22.11.7 os=5.11.0-1020-azure
  • loaded configuration  file=package.json ("build" field)
  • building        target=snap arch=x64 file=build/icalingua_2.4.3_amd64.snap
Launching a container.
Waiting for container to be ready
To start your first instance, try: lxc launch ubuntu:20.04

...

snapd 2.52.1 from Canonical* installed
"snapd" switched to the "latest/stable" channel

core18 20211015 from Canonical* installed
"core18" switched to the "latest/stable" channel

snapcraft 5.0 from Canonical* installed
"snapcraft" switched to the "latest/stable" channel

snapd is not logged in, snap install commands will use sudo
snap "core18" has no updates available
snapd is not logged in, snap install commands will use sudo
gnome-3-28-1804 3.28.0-19-g98f9e67.98f9e67 from Canonical* installed
snapd is not logged in, snap install commands will use sudo
gtk-common-themes 0.1-59-g7bca6ae from Canonical* installed

...

Get:1 ffmpeg_3.4.8-0ubuntu0.2_amd64.deb [1587 kB]                               
Fetched 1587 kB in 0s (0 B/s)                                                   

...

Pulling app 
+ snapcraftctl pull
Pulling app-files 
+ snapcraftctl pull
Pulling gnome-platform-empty-dirs 
+ snapcraftctl pull
Pulling launch-scripts 
+ snapcraftctl pull
Building app 
+ snapcraftctl build
Building app-files 
+ snapcraftctl build
Building gnome-platform-empty-dirs 
+ mkdir -p /root/parts/gnome-platform-empty-dirs/install/data-dir/themes mkdir -p /root/parts/gnome-platform-empty-dirs/install/data-dir/icons mkdir -p /root/parts/gnome-platform-empty-dirs/install/data-dir/sounds mkdir /root/parts/gnome-platform-empty-dirs/install/gnome-platform
Building launch-scripts 
+ snapcraftctl build
Staging app 
+ snapcraftctl stage
Staging app-files 
+ snapcraftctl stage
Staging gnome-platform-empty-dirs 
+ snapcraftctl stage
Staging launch-scripts 
+ snapcraftctl stage
Priming app 
+ snapcraftctl prime
This part is missing libraries that cannot be satisfied with any available stage-packages known to snapcraft:
- libGLU.so.1
- libglut.so.3
- libslang.so.2
These dependencies can be satisfied via additional parts or content sharing. Consider validating configured filesets if this dependency was built.
Priming app-files 
+ snapcraftctl prime
Priming gnome-platform-empty-dirs 
+ snapcraftctl prime
Priming launch-scripts 
+ snapcraftctl prime
CVE-2020-27348: A potentially empty LD_LIBRARY_PATH has been set for environment in 'icalingua'. The current working directory will be added to the library path if empty. This can cause unexpected libraries to be loaded.
Snapping...
Snapped out.snap
```

However, when launch the electron app, the error of missing `ffmpeg` showed up in the log:

```json
...
{"message":{"errname":"Error","errMsg":"Cannot find ffmpeg","e":"Error: Cannot find ffmpeg"},"level":"error","service":"eqq-service"}
...
```

And it's missing from the final snap package, it can be verified in the command:

```js
➜ find /snap/icalingua/current/ | grep ffmpeg
/snap/icalingua/current/app/libffmpeg.so
```

Is this caused by the default `appPartStage`? 

> https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/snap/snapcraft.yaml#L37
```yaml
...
  app:
    plugin: "nil"
      # cd ~ && rm -rf ~/squashfs-root && unsquashfs /media/psf/ramdisk/electron-builder-test/dist/__snap-x64/se-wo-template_1.1.0_amd64.snap
      # comm -12 <(ls ~/squashfs-root/usr/lib/x86_64-linux-gnu/) <(ls /snap/gnome-3-28-1804/current/usr/lib/x86_64-linux-gnu/) > /media/psf/Home/f.txt
      # run snap-exclude-list.js
    stage:
...
      - '-usr/share'
...
      - '-usr/bin'
...
```

`ffmpeg` package provides at least following important files in the `/usr/bin/` and `/usr/share`:

```shell
/usr/bin/ffmpeg
/usr/bin/ffplay
/usr/bin/ffprobe
/usr/bin/qt-faststart
...
/usr/share/ffmpeg/ffprobe.xsd
/usr/share/ffmpeg/libvpx-1080p.ffpreset
/usr/share/ffmpeg/libvpx-1080p50_60.ffpreset
/usr/share/ffmpeg/libvpx-360p.ffpreset
/usr/share/ffmpeg/libvpx-720p.ffpreset
/usr/share/ffmpeg/libvpx-720p50_60.ffpreset
/usr/share/lintian/overrides/ffmpeg
```
