### ISSUE TITLE
Unclear Snap "parts" Configuration

### ISSUE THREAD

**Issue by Zenkylo** [electron-userland/electron-builder#6444]
* **Electron-Builder Version**: 22.13.1

* **Node Version**: v14.18.1

* **Electron Version**: 16.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  Snap

It's unclear to me after reading the provided [Snap target configuration](https://www.electron.build/configuration/snap) how one might provide Snap "parts". The link to the parts documentation on Snapcraft (https://snapcraft.io/docs/reference/parts) from the electron-builder documentation no longer works.

Snapcraft documentation: [https://snapcraft.io/docs/adding-parts](https://snapcraft.io/docs/adding-parts)
Sample `snapcraft.yml`:
```yaml
name: sample-app
version: 1
confinement: strict
summary: Some sample app summary
description: Some sample app description
parts:
  nmcli:
    plugin: nil
    stage-packages:
      - network-manager
    organize:
      usr/bin/nmcli: bin/nmcli
```
