### ISSUE TITLE
dmg-license is an optional dependency, so building fails caused by 'npm ci --no-audit --no-optional'

### ISSUE THREAD

**Issue by ThomasHalwax** [electron-userland/electron-builder#6489]
* **Electron-Builder Version**:  22.14.5
* **Node Version**: 16.13.1
* **Electron Version**: 16.0.4
* **Electron Type (current, beta, nightly)**: current
* **Target**: OS-X

We are building our application by making use of Github Actions. The steps are:

```sh
npm ci --no-audit --no-optional // <<-- no-optional skips dmg-license
npm run webpack:production
electron-builder --mac
```

The last command fails with 

```sh
⨯ Cannot find module 'dmg-license'
```

After inspecting the package.json of electron-builder/packages/dmg-builder I found ```dmg-license``` to be declared optional.

```json
"optionalDependencies": {
  "dmg-license": "^1.0.9"
}
```

If electron-builder depends on dmg-license can you please move it to the _dependencies_ section?

Thanks!

**Comment by mmaietta** [comment]
It's not possible to move it to dependencies option because `dmg-license` can't be installed on windows/linux build systems IIRC. Due to the configuration of the monorepo with `dmg-builder`, `dmg-license` must remain in the `optionalDependencies` section.
An alternative idea is for you to have `dmg-license` directly added as a `devDependency` to your project?

**Comment by asd56400** [comment]
I have also encountered this problem. The dependency of dmg-license seems to be added after electron-buider@20.39.0. The dmg-license is not used in version 20.39.0, which can avoid this problem. For normal applications, it should be Doesn't need a license

**Comment by CPSO** [comment]
For anyone coming across this, i solved my problem with selecting macos 10.15 `macos-10.15` and by adding a extra step in the build process.

``` 
name: install dmg-license 
run: npm i dmg-license
``` 
My build.yml for mac looks like this
```
 build_on_mac:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
      with:
        node-version: 16.14.2
    - name: install dependencies
      run: npm install
    - name: install dmg-license
      run: npm i dmg-license
    - name: build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run electron:build --macos
```
