### ISSUE TITLE
Support universal arch for NSIS

### ISSUE THREAD

**Issue by ocavue** [electron-userland/electron-builder#6571]
* **Electron-Builder Version**:  22.14.5

* **Node Version**: 17.3.0

* **Electron Version**: 16.0.7
* **Electron Type (current, beta, nightly)**: current 

* **Target**:  windows

---

I want to only get one big `.exe` file that supports both x64 and arm64. Currently, I will get three `.exe` files if I config `{ target: "nsis", arch: ["x64", "arm64"] }`. Based on the file size, I guess the bigger `.exe` file is what I want. However, since all three `.exe` files are recorded in `latest.yml`, and I'm not sure how electron-updater works, it seems to be a bad idea to only upload one `.exe` file to the server (see also https://github.com/electron-userland/electron-builder/issues/6536). 

I propose to add a new Arch "universal" for NSIS, e.g. `{ target: "nsis", arch: "universal" }`. Like the way how "universal" works for macOS now, it will only output one file `Rino-v0.40.0-win-universal.exe`. `latest.yml` should only contain this file. 

---

I'm using the following config for electron-builder:

```js
const config = {
    artifactName: "${productName}-v${version}-${os}-${arch}.${ext}",

    win: {
        target: [{ target: "nsis", arch: ["x64", "arm64"] }],
    },

    mac: {
        target: [
            { target: "zip", arch: "universal" },
            { target: "dmg", arch: "universal" },
        ],
    },
}
```

And I get the following files after build:

```
151M Rino-v0.40.0-mac-universal.zip
156M Rino-v0.40.0-mac-universal.dmg
 65M Rino-v0.40.0-win-arm64.exe
 64M Rino-v0.40.0-win-x64.exe
128M Rino-v0.40.0-win.exe
```

*By the way, the filename `Rino-v0.40.0-win.exe` doesn't match the `artifactName` config. `${arch}` is missing here. Not sure why.*

```yaml
# latest.yml                                                                                                         
version: 0.40.0
files:
  - url: Rino-v0.40.0-win.exe
    sha512: wj30f0V842Q6Tuvijq8/KzXraWcxuzCIRwV0MdOq9HDFuFCt3rLft6riJ7tgu160MDyMJsGDtjdwq50/yQRy5w==
    size: 134679080
  - url: Rino-v0.40.0-win-x64.exe
    sha512: r+3vIetJFYL3eHWaDi0OptaBW1ECTC1+jarRVM1C3lMB67WyO7qfxI5ZasJoUt8WuW8aeeIwr1EcUUpYeFts7A==
    size: 67354192
  - url: Rino-v0.40.0-win-arm64.exe
    sha512: WToUBza2kpkr0g+Ui8QaiGIF7vgvlb9RN9P6v4CiVx6IIjTdOf6EdJq94PtCVvNzbAHCIZ6JAURb1E49F99uPw==
    size: 67870816
path: Rino-v0.40.0-win.exe
sha512: wj30f0V842Q6Tuvijq8/KzXraWcxuzCIRwV0MdOq9HDFuFCt3rLft6riJ7tgu160MDyMJsGDtjdwq50/yQRy5w==
releaseDate: '2022-01-22T17:40:35.735Z'
```

```yaml
# latest-mac.yml
version: 0.40.0
files:
  - url: Rino-v0.40.0-mac-universal.zip
    sha512: vmCSDkzABJl3cpCkjjosAlVoGa32zLe7bv3CHEix7ZQHfP1gO4eB5stP05deVbcyX77vPM7QkBCY8NBNSKcipA==
    size: 158308696
  - url: Rino-v0.40.0-mac-universal.dmg
    sha512: l/Bn7wfeWpzM4ihKTMu8T5jW1k0EBXgZeRwvCQoc8FjYfbIGZBFzQaI8PdD2F2TxND59+scamHf1iSQNyKFXmw==
    size: 163972537
path: Rino-v0.40.0-mac-universal.zip
sha512: vmCSDkzABJl3cpCkjjosAlVoGa32zLe7bv3CHEix7ZQHfP1gO4eB5stP05deVbcyX77vPM7QkBCY8NBNSKcipA==
releaseDate: '2022-01-22T17:40:35.735Z'
```

---
