### ISSUE TITLE
AppImage build seems corrupted

### ISSUE THREAD

**Issue by mscharley** [electron-userland/electron-builder#6624]
* **Electron-Builder Version**: 23.0.0-alpha.2

* **Node Version**: 16.13.1

* **Electron Version**: 17.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: AppImage

I'm using the alpha version because I was running into #6563 .

This seems to be an issue with electron 17.x, if I roll back to 16.0.8 then it builds and runs fine. I'm building on Arch Linux targeting AppImage. The build runs fine, but when I try to run it I get the following output:

```
$ electron-builder --publish never

  • electron-builder  version=23.0.0-alpha.2 os=5.15.19-1-lts
  • loaded configuration  file=/home/mscharley/Code/mscharley/app/electron-builder.yml
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=17.0.0 appOutDir=dist/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/app-0.1.0.AppImage
  • default Electron icon is used  reason=application icon is not set

$ ./dist/app-0.1.0.AppImage
Squashfs image uses (null) compression, this version supports only xz, zlib.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage
if you run it with the --appimage-extract option.
See https://github.com/AppImage/AppImageKit/wiki/FUSE
for more information
open dir error: No such file or directory
```

**Comment by mmaietta** [comment]
Could you please post your snap configuration for electron-builder?

We upgraded to enable `lzo` compression for snap as the default in https://github.com/electron-userland/electron-builder/pull/6201
In your snap options, try setting `compression: 'xz'`

**Comment by mscharley** [comment]
No change with the compression option added.

My `build-effective-config.yaml`:

```yaml
directories:
  output: dist
  buildResources: build
appId: com.github.mscharley.app
files:
  - filter:
      - '**/*'
      - '!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme}'
      - '!**/node_modules/*/{test,__tests__,tests,powered-test,example,examples}'
      - '!**/node_modules/*.d.ts'
      - '!**/node_modules/.bin'
      - '!**/*.{iml,o,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,xproj}'
      - '!.editorconfig'
      - '!**/._*'
      - '!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,.gitignore,.gitattributes}'
      - '!**/{__pycache__,thumbs.db,.flowconfig,.idea,.vs,.nyc_output}'
      - '!**/{appveyor.yml,.travis.yml,circle.yml}'
      - '!**/{npm-debug.log,yarn.lock,.yarn-integrity,.yarn-metadata.json}'
linux:
  target: AppImage
  category: Utility
snap:
  compression: "xz"
publish:
  - github
electronVersion: 17.0.0
```
