### ISSUE TITLE
example config to show you how to support build for Mac M1

### ISSUE THREAD

**Issue by cnmade** [electron-userland/electron-builder#6674]
I would like to show somebody if looking for how to let electron-builder to support build for Mac M1 
# your electron-builder.yml
```
asar: false


files:
  - "./app/bundle.js"
  - "./app/index.css"
  - "./app/index.html"
  - "./app/math.js"
  - "./app/main.js"
  - "./package.json"

mac:
  target: 
   - target: dmg
     arch:
        - arm64
        - x64
        
win:
  target:
    - target: nsis
      arch:
        - ia32

nsis:
  oneClick: false

directories:
  buildResources: "resources"
  output: "release"

publish: null

```

# to use

```bash
electron-builder -mw
```
