### ISSUE TITLE
macOS Intel installs ARM on auto-update

### ISSUE THREAD

**Issue by lostdesign** [electron-userland/electron-builder#6694]
* **Electron-Builder Version**: 22.11.4
* **Electron-Updater Version**: 4.6.5

* **Node Version**: v16.13.2

* **Electron Version**: 17.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  macos

This issue was reported before, saying that 4.3.7 would have resolved the issue made me upgrade to 4.6.5 for electron-updater. I tried building locally and updating it which initially worked but testing it from an official release broke the app yet again.

What else could I try to fix this issue? The repo is lostdesign/linked

Thanks in advance!

**Comment by mmaietta** [comment]
Just curious, why not use `arch: 'universal'` for a single build?

**Comment by lostdesign** [comment]
> Just curious, why not use `arch: 'universal'` for a single build?

What does that do?

**Comment by mmaietta** [comment]
What do these return on your mac that is incorrectly installing an ARM update?
```
sysctl sysctl.proc_translated 
```
```
uname -a
```
Alternatively, can you add more logging for the auto updater?
https://www.electron.build/auto-update#debugging

**Comment by lostdesign** [comment]
```
➜  code sysctl sysctl.proc_translated
sysctl: unknown oid 'sysctl.proc_translated'
```

```
Darwin lostdesign-mbp.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
```

And yes, I will add more logging to the autoupdater to check locally. Should have done that in the first place..

**Comment by sivkoff** [comment]
We have a similar issue, the only difference it updates the ARM version to Intel. We have a different order in the `arch` though (`['x64', 'arm64']`), so my hypothesis is it takes the first URL in the list and downloads it.

**Comment by currentoor** [comment]
> We have a similar issue, the only difference it updates the ARM version to Intel. We have a different order in the `arch` though (`['x64', 'arm64']`), so my hypothesis is it takes the first URL in the `latest-mac.yml` and downloads it.

I have the same issue too. My `latest-mac.yml` looks like this
```
version: 5.0.6
files:
  - url: mutesync-5.0.6-mac.zip
    sha512: nHsY/tA0KMRNJNCweNFAF2/4BDp/IN5rBb01LaQihq4Kyr6EnjBjouMIKNnIiQJ9ENTNJj8m1MkCoZ1Y0oG+Lg==
    size: 91497931
  - url: mutesync-5.0.6.dmg
    sha512: 4TW/O1W3b3V8bIhlzXLDVhhVBlq4XBmtXUPyS/I3dcqgZ28rrDR35x3s8rhq73N0FNg6OEadYD/oGIBEJpCYLg==
    size: 94820970
  - url: mutesync-5.0.6.dmg
    sha512: 4TW/O1W3b3V8bIhlzXLDVhhVBlq4XBmtXUPyS/I3dcqgZ28rrDR35x3s8rhq73N0FNg6OEadYD/oGIBEJpCYLg==
    size: 94820970
  - url: mutesync-5.0.6.dmg
    sha512: 4TW/O1W3b3V8bIhlzXLDVhhVBlq4XBmtXUPyS/I3dcqgZ28rrDR35x3s8rhq73N0FNg6OEadYD/oGIBEJpCYLg==
    size: 94820970
path: mutesync-5.0.6-mac.zip
sha512: nHsY/tA0KMRNJNCweNFAF2/4BDp/IN5rBb01LaQihq4Kyr6EnjBjouMIKNnIiQJ9ENTNJj8m1MkCoZ1Y0oG+Lg==
releaseDate: '2022-02-23T17:51:37.930Z'
```

In `package.json` I have
```
      "target": [
        {
          "target": "default"
        }
      ]
```

To publish I use
```
yarn electron-builder build -m -p always --arm64
yarn electron-builder build -m -p always --x64
```

But I did notice the `arm64` build is uploaded correctly. I can't use a universal build because my app has a lot of native code that needs to be built individually for each architecture.
