### ISSUE TITLE
checksum does not look correct 

### ISSUE THREAD

**Issue by hovancik** [electron-userland/electron-builder#6717]
* **Electron-Builder Version**: "^22.14.13"

* **Node Version**: 16.13.0

* **Electron Version**: ^17.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: Any

Values that `electron-builder` puts for sha sums looks incorrect: 

```
sha512: BSePTAZqxRpilzDsBx6ryJ2/B3WZLniW8cTnOF5FI9zy0BfAmhu+DwjUpMPj4UAOK6hTAKs3fYR2A7wbtLF8cw==
size: 112589616
```

`sha512sum file`

```
05278f4c066ac51a629730ec071eabc89dbf0775992e7896f1c4e7385e4523dcf2d017c09a1bbe0f08d4a4c3e3e1400e2ba85300ab377d847603bc1bb4b17c73
```

I've tried with 2 apps that use electron builder with same results: 
https://github.com/hovancik/stretchly/releases/tag/v1.10.0
https://github.com/vercel/hyper/releases/tag/v3.2.0

**Comment by mmaietta** [comment]
The checksums I see being used in the code are sha1, sha2, and sha256

**Comment by hovancik** [comment]
Here's the generated file: 

```
version: 3.2.0
files:
  - url: Hyper-3.2.0.AppImage
    sha512: tXzMY556mNkFryHKFQjDb3oy5ov3BVwz4ZFQjuhFamfPzyzLW4cTDqZjpF0gQ87QT5NakeVzKnV5bjjYlULT5Q==
    size: 133853528
    blockMapSize: 139628
path: Hyper-3.2.0.AppImage
sha512: tXzMY556mNkFryHKFQjDb3oy5ov3BVwz4ZFQjuhFamfPzyzLW4cTDqZjpF0gQ87QT5NakeVzKnV5bjjYlULT5Q==
releaseDate: '2022-02-04T09:42:00.008Z'

```

It says `sha512`
