### ISSUE TITLE
Sharp library is not being unpacked

### ISSUE THREAD

**Issue by andirsun** [electron-userland/electron-builder#6880]
* **Electron-Builder Version**: 
version=23.0.9

* **Node Version**: 
 v14.19.0

* **Electron Version**:
^18.1.0
* **Electron Type (current, beta, nightly)**:
Current

* **Target**: 
Mac / Linux / Windows

I am using the sharp library and the library is being unpacked correctly on windows and mac os builds but I have to manually unpack the library on linux with this code 
```
linux:
  category: Graphics
  # Linux fix to use sharp library
  asarUnpack:
    - "**/node_modules/sharp/**"
```
