### ISSUE TITLE
Change the default update cache folder and default installation folder location

### ISSUE THREAD

**Issue by Tarrowren** [electron-userland/electron-builder#6899]
* **Electron-Builder Version**: 22.14.13

* **Node Version**: 16.15.0

* **Electron Version**: 19.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows, linux

The default folder name uses the package.json name, I want to be able to simply configure it using the api, using the `appId`or a separate field

**Comment by burgil** [comment]
Try to use `allowToChangeInstallationDirectory`: https://www.electron.build/configuration/nsis#:~:text=allowToChangeInstallationDirectory

on your package.json or `electron-builder.yml`,

Example for the yml file:

```yml
# Windows Installer configuration - https://www.electron.build/configuration/nsis
nsis:
  artifactName: "${productName}-${version}-${arch}-macos-installer.${ext}"
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
```

**Comment by Tarrowren** [comment]
I release a development version, a test version and a production version for my application, and the software tester installs them all at the same time. They often forget to change the path resulting in an overwrite installation. Even if they are installed to different paths, they share the same update cache folder

**Comment by burgil** [comment]
Maybe, just maybe, this will set the cache directory, Worth the try:
https://www.electron.build/configuration/configuration.html#:~:text=The%20cache%20location.
![image](https://user-images.githubusercontent.com/41600149/172080214-55498363-0247-4ebf-aaa4-55437d621251.png)

Also found this resource:
https://github.com/electron-userland/electron-builder/issues/4267

This answers on stackoverflow:
- Impossible +PR : https://stackoverflow.com/questions/59533019/change-cache-path-for-electron-js-application
- No answers + comments : https://stackoverflow.com/questions/64723304/how-can-i-cache-files-for-electron-builder
- Maybe an actual solution: https://stackoverflow.com/a/64397368
- How to clear the cache manually using code: https://stackoverflow.com/questions/31446782/how-to-clear-the-cache-data-in-electronatom-shell

Good luck please let me know if anything worked!

**Comment by Tarrowren** [comment]
Sorry I didn't make myself clear, the update cache is the cache used by `autoUpdater` during incremental updates, the directory is usually under `%AppData%/Local/${name}-updater`

**Comment by Tarrowren** [comment]
I checked the source code:

> appInfo.ts
```typescript
...
  get sanitizedName(): string {
    return sanitizeFileName(this.name)
  }
  get updaterCacheDirName(): string {
    return this.sanitizedName.toLowerCase() + "-updater"
  }
...
```
`this.name` is taken from the metadata, which in turn is obtained from package.json. I want to modify the metadata data

**Comment by burgil** [comment]
@Tarrowren 
Check this out, a file named `app-update.yml`, generated by electron-builder, for updating purposes, it's location is near the asar file, and it's content contains a `cache` folder name, see if that helps maybe you can also set the path there, lemme know :)
![image](https://user-images.githubusercontent.com/41600149/172187755-e93c2d7a-3135-4827-83e1-1969d760710a.png)

**Comment by Tarrowren** [comment]
I found the `beforePack` hook function and I changed the value of the metadata and it took effect. I don't know if there are any side effects though.
```js
beforePack: (context) => {
  context.packager.info.metadata.name = "hello";
},
```

> app-update.yml
```yml
provider: generic
url: http://127.0.0.1:8080
useMultipleRangeRequest: false
updaterCacheDirName: hello-updater
```
