### ISSUE TITLE
WIN_CSC_LINK error on GitHub Action CI

### ISSUE THREAD

**Issue by AdrianoFerrari** [electron-userland/electron-builder#6921]
* **Electron-Builder Version**: 23.0.3

* **Node Version**: 16

* **Electron Version**: 18.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

With both base64 and Dropbox direct download link, I get the following error when running my Github action:

```
 ⨯ Env WIN_CSC_LINK is not correct, cannot resolve: D:\a\myreponame\myreponame\*** doesn't exist
```

The env variable is set in my Github secrets, and I verified the download link. It's possible that there's an issue with the certificate itself, but the thing that's confusing me is the `D:\...` stuff and `doesn't exist`, which makes it seem like the file wasn't downloaded correctly.

Here is the line the error message is coming from:
https://github.com/electron-userland/electron-builder/blob/e6312cb54e5d957289d5c07b506491fcaea9e334/packages/app-builder-lib/src/winPackager.ts#L73

 I've gone up and down the function definitions, but I can't find a way to get more info about this error. Any help or ideas on what I can try next?

**Comment by mmaietta** [comment]
I've always been able to use that env var by passing in the base64 string. AFAIK, it's not possible for electron-builder to download the cert file. I just have mine encrypted and stored in my private repo.

**Comment by robertpatrick** [comment]
@AdrianoFerrari As Mike is suggesting, try using a [GitHub Action Secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets) to store the certificate.

**Comment by AdrianoFerrari** [comment]
Thanks. That was my initial attempt, but it was too long for base64.
I'll just go ahead and include it (encrypted) in the repo, and add the decrypt passphrase as an Action secret.

However, for the benefit of others, wouldn't it be prudent to either fix the certificate downloading issue, or to update the documentation? As it stands currently, it seems that we *should* be able to download certificates, so many others might be trying and failing to do so...

If I were better able to pinpoint why it's not downloading, I could give it a shot.

**Comment by AdrianoFerrari** [comment]
**UPDATE** : My mistake!

It downloads correctly (from a DropBox direct-download link).

I just had forgotten to set the env properly, like so, in my Action:
```
    env:
      GH_TOKEN: ${{ secrets.github_token }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
      WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
```
