### ISSUE TITLE
Electron builder not letting me add unplugged yarn 3 modules 🔢 👍 👎 💯 🥇 🅰️ 😮‍💨 😵‍💫 

### ISSUE THREAD

**Issue by burgil** [electron-userland/electron-builder#6926]
* **Electron-Builder Version**: v23.0.3

* **Node Version**: v17.9.0

* **Electron Version**: 19.0.3
* **Electron Type (current, beta, nightly)**: beta but unrelated

* **Target**: windows

## Electron builder not letting me add unplugged yarn 3 modules

Before pack:
![image](https://user-images.githubusercontent.com/41600149/172040139-666ce7e3-4e21-448f-82f3-34f9b14be05d.png)

After pack:
![image](https://user-images.githubusercontent.com/41600149/172040096-5f237e38-d551-4d4d-84e7-e8f8f17505d3.png)

## feat: Yarn 2&3 Compatibility Configuration #6924 

Which will expose the following configuration option: (`includeYarnSubNodeModules`)
![image](https://user-images.githubusercontent.com/41600149/172040165-58542979-f46f-4308-a4de-4c1f39828806.png)

I tried every possible combination you can think of for days, I've made my own `beforePackHook` and `afterPackHook` files and tried everything to copy the required modules into the `asar` files,

I did managed to include them only when I set `includeSubNodeModules` to `true`, But, it modified the package.json of some `unplugged` folders, rendering the `includeSubNodeModules` option useless in that scenario.

I tried everything, I also made a `temp-build` folder and copied everything 1 by 1 and even that fails to copy them, I even tried to make a `temp-yarn` which then copies to `.yarn` using the `from` and `to` fields, the list is really too big of the amount of things I tried,
![image](https://user-images.githubusercontent.com/41600149/172040370-a1221f43-043e-4923-bcad-e25247f7f2f1.png)
(one of the trials)
and I narrowed it down to the fact `unplugged` plugins have a `node_modules` folder which is being excluded hard-coded, and if you `includeSubNodeModules` like mentioned above it will rewrite them causing my code protection algorithm to fail checking the file hashes.. and nevertheless it's a hacky solution to do all that, instead with a simple switch I can disable those `.yarn` exclusions and `node_modules` irrelevancy in that case which causes `unplugged` modules to not be included in yarn 3.

So it's like:

`project\.yarn\unplugged\package1.0.0-4kj3m43\node_modules\package1.0.0\**UniqueFiles**`

and that blocks it:

`'!**/node_modules'`

so yeah checkout my pull request (feat: Yarn 2&3 Compatibility Configuration #6924)

## Unplugged path examples

![image](https://user-images.githubusercontent.com/41600149/172068769-f46e4e4a-5fe1-4614-bb8b-d0774f044e54.png)
![image](https://user-images.githubusercontent.com/41600149/172068770-edb6d80c-33a2-4893-8871-973bca8978d0.png)

## How I narrowed it down?

Using the debug file: `builder-debug.yml`

I noticed it blocks `'!**/node_modules'` while on **yarn we don't have those**, instead on the `./yarn/unplugged` folder we have modules that don't support PNP yet.. ignore that just modules that can't be zipped, anywho and they just sit in `./yarn/unplugged` as folders with their name, But, they live inside inside a `node_modules` folder, which gets excluded by force:

```yml
x64:
  firstOrDefaultFilePatterns:
    - '**/*'
    - '!**/node_modules'
    - '!build{,/**/*}'
    - '!WinRelease{,/**/*}'
    - '!**/*'
    - '!**/*.{iml,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,suo,xproj,cc,d.ts,pdb}'
    - '!**/._*'
    - '!**/electron-builder.{yaml,yml,json,json5,toml}'
    - '!**/{.git,.hg,.svn,CVS,RCS,SCCS,__pycache__,.DS_Store,thumbs.db,.gitignore,.gitkeep,.gitattributes,.npmignore,.idea,.vs,.flowconfig,.jshintrc,.eslintrc,.circleci,.yarn-integrity,.yarn-metadata.json,yarn-error.log,yarn.lock,package-lock.json,npm-debug.log,appveyor.yml,.travis.yml,circle.yml,.nyc_output}'
    - '!.yarn{,/**/*}'
    - '!.editorconfig'
    - '!.yarnrc.yml'
  nodeModuleFilePatterns:
    - '**/*'
    - '!**/*'
```

## Please forgive my English as I am not a native English speaker 👍 

_Please, let's be a little flexible, for me, for yarn, for everybody that will have this issue like me, we need to control every byte in that asar file sometimes_

If you guys don't know how to work with Yarn 3 yet feel free to ask me and I will send you a short code-guide I wrote here
