### ISSUE TITLE
Packaged windows app looking in the wrong directory for node_modules

### ISSUE THREAD

**Issue by niteshbalusu11** [electron-userland/electron-builder#6928]
When I'm building my app for windows and later opening the package, it's throwing the following error. 

Such a directory does not exist and I'm not sure why it trying to look there, any help, please? 

![image](https://user-images.githubusercontent.com/84944042/172058241-3037b4d9-ab3a-4892-81d9-58ee744a243f.jpeg)

**Comment by burgil** [comment]
try to enable `includeSubNodeModules` in the `electron-builder.yml` or your `package.json` respectively
Beware of the large file size afterwards, you can manually include files using the `beforePackHook` file and it's appropite configuration option.

**Comment by burgil** [comment]
Also try to package your app without `asar: true`, make it `asar: false`, and see if you can now make sense of the errors. you can directly work on the app build directory all the source files should be there and you should be able to easily identify the issue like this, example from my `electron-builder.yml` file:
```yml
# App Info
appId: "com.example.app"
copyright: "Copyright © 2022 example"

# Package electron code into a asar archive. Set to false to debug issues.
asar: false
includeSubNodeModules: true
```
