### ISSUE TITLE
[RPM] Newline escape sequences in the description field breaks rpm build

### ISSUE THREAD

**Issue by asger-finding** [electron-userland/electron-builder#7009]
* **Electron-Builder Version**: v23.1.0

* **Node Version**: v16.15.0 (also tested on node v12)

* **Electron Version**: v10.4.7
* **Electron Type (current, beta, nightly)**: current

* **Target**: rpm

When building an application for rpm (deb, snap is untested) and the `description` field in your electron-builder files uses the `\n` newline sequence, the application will not install. (see screenshots 1 and 2)  
When using a `\r` newline sequence, the application will install, but the synopsis will get replaced by the description (see screenshots 3 and 4)

The application was installed with GNOME Software

## electron-builder.yml

```yaml
appId: asgerfinding.electron

files:
  - src/**/*
  - package.json
directories:
  output: dist

forceCodeSigning: false
artifactName: asgerfinding-${os}-${arch}.${ext}

linux:
  target:
    - target: rpm
      arch: [x64]
  synopsis: This is a synopsis
  # description: "This is a multi\nline description using \\n."
  # description: "This is a multi\rline description using \\r."

```

## Before install, using `\n`

![image](https://user-images.githubusercontent.com/49583904/179862820-38a0cb6d-4796-4aff-bb84-29b692f97f1c.png)

## After install, using `\n`

*Note that the "Open" button is missing, and that the application is nowhere to be found installed.*

![image](https://user-images.githubusercontent.com/49583904/179862908-a33cfc31-3a90-4b0f-ada4-7d5fbb606803.png)

## Before install, using `\r`

![image](https://user-images.githubusercontent.com/49583904/179863378-23ceb6a3-abe6-4a8f-9856-f4c15832e6b6.png)

## After install, using `\r`

*Note the synopsis. The icon was set properly upon re-opening the rpm in GNOME Software. The broken synopsis, however, remained.*

![image](https://user-images.githubusercontent.com/49583904/179863426-075a6ca6-47cd-4b1e-a891-373b0a879c0b.png)
