### ISSUE TITLE
Cannot read properties of undefined (reading 'Chromium Framework')

### ISSUE THREAD

**Issue by RayJason** [electron-userland/electron-builder#7182]
* **Electron-Builder Version**:  23.3.3

* **Node Version**: v16.17.0

* **Electron Version**: 20.1.1

* **Electron Type (current, beta, nightly)**: current

* **Target**: mac os universal dmg

* **Env**: Mac OS 12.6 / Apple M1 Pro

I tried to install chromium and chrome, both no avail.  Recently I can only build x64.

```yml
mac:
  target:
    - target: dmg
      arch:
        - universal # failed
 ```

![image](https://user-images.githubusercontent.com/15711610/194745387-fa21e57c-029d-46ec-909c-ff9eac02c5bd.png)

full config:
```yaml
asar: true
directories:
  buildResources: resources
  output: release/${version}

files:
  - dist

artifactName: ${productName}-${version}.${ext}
icon: 'resources/icon.ico'

mac:
  target:
    - target: dmg
      arch:
        - universal

win:
  target:
    - target: nsis
      arch:
        - x64

dmg:
  contents:
    - x: 410
      y: 150
      type: 'link'
      path: '/Applications'

    - x: 130
      y: 150
      type: 'file'

nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
```
