### ISSUE TITLE
NSMicrophoneUsageDescription appears twice in Info.plist app is being rejected by apple

### ISSUE THREAD

**Issue by ahmedmukhtar1133** [electron-userland/electron-builder#7514]
* **Electron-Builder Version**:  23.6.0

* **Node Version**:  16

* **Electron Version**: 22.1.0
* **Electron Version**: 5.3.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Mac & Mas

I'm using electron-builder.yml file for building Mac and Mas Build:
```
mac:
  entitlementsInherit: build/entitlements.mac.plist
  extendInfo:
    - NSMicrophoneUsageDescription: Tali needs to have access to your machine microphone to transcribe your voice to medical text.
  provisioningProfile: embedded.provisionprofile
  icon: build/icon.icns
  target: mas

mas:
  hardenedRuntime: false
  type: distribution
  entitlements: build/entitlements.mas.plist
  entitlementsInherit: build/entitlements.mas.inherit.plist
  extendInfo:
    - NSMicrophoneUsageDescription: Tali needs to have access to your machine microphone to transcribe your voice to medical text.

```
But apple rejects the MAS build saying:
- We noticed that your app requests the user’s consent to access the microphone, but doesn’t sufficiently explain the use of the microphone in the purpose string
- Please revise the purpose string in your app’s Info.plist file for microphone to explain why your app needs access and include an example of how the user's data will be used.
On debugging I found that generated Info.plist contain 2 keys for `NSMicrophoneUsageDescription` for both MAC and MAS Builds:
```
<plist version="1.0">
  <dict>
    <key>0</key>
    <dict>
      <key>NSMicrophoneUsageDescription</key>
      <string>Tali needs to have access to your machine microphone to transcribe your voice to medical text.</string>
    </dict>
    <key>CFBundleDisplayName</key>
    <string>Tali</string>    
    <key>NSCameraUsageDescription</key>
    <string>This app needs access to the camera</string>
  </dict>
</plist>
```
