### ISSUE TITLE
Setup for Auto Updating using a Windows Developer Certificate

### ISSUE THREAD

**Issue by jcharnley** [electron-userland/electron-builder#7616]
* **Electron-Builder Version**: 
24.2.1

* **Node Version**: 
* 18

* **Electron Version**:
 25.0.1
* **Electron Type (current, beta, nightly)**:
current
* **Target**: 
* Window and Linux redhat

## Summary

Hi, I am using the electron react boilerplate template for a project of mine that is using Electron-builder, I have it all setup and is working as expected however, I am unsure how to trigger the auto updating via the pipeline.

I have a windows developer's certificate bought from GlobalSign, I have created the CSR on Azure Key Vault and now have a validate certificate. My question is, do I need to host this somewhere for the pipeline to pull and sign the code via the pipeline, 

In the publish yaml file it looking for.

  CSC_LINK: ${{ secrets.CSC_LINK }}
  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

The CSC link is the URL where the certificate is hosted correct?  which can be inputted into GitHub secrets. However, am unclear on how to host this correctly to use a password to access it. It is signed using a non-integrated certificate provider.

Is the CSC_KEY_PASSWORD. My password that is used to access and download the certificate from the provider? or is that a password to access to pubic. Private url storage point.

What are my options here? 

If I keep it on Azure I think i will need to auth so that request to access to certificate. I have also seen people put the cert on Dropbox as a public link.

Any help would be appreciated as this process is new to me

YAML FILE

```
name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'electron-react-boilerplate' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win --mac --linux
```
