### ISSUE TITLE
Windows build fail since the icon.ico at wrong position.

### ISSUE THREAD

**Issue by asika32764** [electron-userland/electron-builder#7711]
* **Electron-Builder Version**:  24.6.3

* **Node Version**: v16.20.0

* **Electron Version**: 25.3.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: win portable

Windows build will fail because the icon.ico will put to `${version}/.icon-ico/` dir, not `x.x.x/.icon-ico/` dir.

![p-001-2023-08-04-01-03-28](https://github.com/electron-userland/electron-builder/assets/1639206/f18e8b98-7c1c-48a2-9d27-d7610a231c17)

Error message

> Error output:
Error while loading icon from "E:\...\release\0.0.0\.icon-ico\icon.ico": can't open file
  failedTask=build stackTrace=Error: C:\Users\xxx\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

The config file:

```yaml
appId: xxx
asar: false
directories:
    output: release/${version}

files:
    - dist
    - electron

icon: public/editor-icon.png

win:
    target:
        - target: portable
          arch:
              - x64
    artifactName: "${productName}_${version}.${ext}"
```

NOTE: Building in MacOS works well, only fail in Windows.
