### ISSUE TITLE
Auto Updater EPERM Issues

### ISSUE THREAD

**Issue by ThatKawaiiSam** [electron-userland/electron-builder#7784]
* **Electron-Builder Version**: 24.6.4

* **Node Version**: 18.15.0

* **Electron Version**:  25.3.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows, macOS, Linux

We have Sentry enabled throughout our Application and have noticed a considerable amount of errors with the Auto Updater in regards to some update files operations not being permitted. 

<img width="1207" alt="Screenshot 2023-09-16 at 11 44 29 pm" src="https://github.com/electron-userland/electron-builder/assets/9959338/1ea45e17-de96-4105-ac67-26f1019a77fc">

We do not modify any of the core functionality of the updater and use it mostly out of the box with a few additions around when `quitAndInstall()` is called ensuring that we don't update when in the dock.

Happy to provide any additional context if needed.

**Comment by mmaietta** [comment]
Are you distributing both `portable` and `nsis` targets? Can you please post your electron-builder config?

**Comment by okkidev01** [comment]
@mmaietta  I had the same issue, my sentry log is like that:
Electron-Builder Version: 23.6.0
Node Version: 16.17.1
Electron Version: 19.0.0
Electron Type (current, beta, nightly): current
Target: Windows, macOS
![image](https://github.com/electron-userland/electron-builder/assets/144433227/bc2e74be-fe27-49ea-bdd6-c60511166742)

all of this error happened on Windows
![image](https://github.com/electron-userland/electron-builder/assets/144433227/61455d42-0027-4879-a9cd-a72bb829534d)

my packaging config is blow:
"nsis": {
    "oneClick": false,
    "perMachine": false,
    "allowToChangeInstallationDirectory": true,
    "shortcutName": `OKKI${ENV_NAME}`,
    "include": "./scripts/installer.nsh",
    "differentialPackage": false,
    "packElevateHelper": true,
    "guid": `OKKI${ENV_NAME}`
  },
  "win": {
    "target": [
      {
        "target": "nsis",
        "arch": [
          "ia32",
          "x64"
        ]
      }
    ],
    "signingHashAlgorithms":['sha1', 'sha256'],
    "sign": "./scripts/signWin.js",
    "verifyUpdateCodeSignature": false,
    "signDlls": true,
    "timeStampServer": "http://timestamp.digicert.com"
  },

**Comment by ThatKawaiiSam** [comment]
> Are you distributing both `portable` and `nsis` targets? Can you please post your electron-builder config?

Here is the `builder-effective-config.yaml`

```
directories:
  output: release
  buildResources: build
generateUpdatesFilesForAllChannels: true
appId: com.moonsworth.client
extraMetadata:
  version: 3.1.0
productName: Lunar Client
files:
  - filter:
      - build/**/*
      - dist/**/*
      - dist-electron/**/*
      - '!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme}'
      - '!**/node_modules/*/{test,__tests__,tests,powered-test,example,examples}'
      - '!**/node_modules/*.d.ts'
      - '!**/node_modules/.bin'
      - '!**/*.{iml,o,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,xproj}'
      - '!.editorconfig'
      - '!**/._*'
      - '!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,.gitignore,.gitattributes}'
      - '!**/{__pycache__,thumbs.db,.flowconfig,.idea,.vs,.nyc_output}'
      - '!**/{appveyor.yml,.travis.yml,circle.yml}'
      - '!**/{npm-debug.log,yarn.lock,.yarn-integrity,.yarn-metadata.json}'
      - '!**/node_modules/typescript/**/*'
      - '!**/node_modules/register-scheme/**/*'
protocols:
  - name: lunarclient
    schemes:
      - lunarclient
win:
  target: nsis-web
  icon: build/icon.png
  signingHashAlgorithms:
    - sha256
  sign: ./winSign.js
mac:
  category: public.app-category.games
  hardenedRuntime: true
  artifactName: ${productName} v${version}.${ext}
  entitlements: build/entitlements.plist
  entitlementsInherit: build/entitlements.plist
  target:
    - dmg
    - zip
  icon: build/icon-macos.png
  notarize: {}
linux:
  target: AppImage
dmg:
  title: Lunar Client
  writeUpdateInfo: false
  window:
    width: 1000
    height: 776
  iconSize: 120
  contents:
    - x: 296
      'y': 496
    - x: 704
      'y': 496
      type: link
      name: Applications
      path: /Applications
nsisWeb:
  oneClick: true
  perMachine: false
  license: build/license_en.txt
  artifactName: ${productName} v${version}.${ext}
  installerIcon: build/icon-installer.ico
  uninstallerIcon: build/icon-uninstaller.ico
  installerHeaderIcon: build/icon.ico
  uninstallDisplayName: Uninstall ${productName}
  installerSidebar: build/sidebar.bmp
  uninstallerSidebar: build/sidebar.bmp
  differentialPackage: false
publish:
  - provider: generic
    url: https://launcherupdates.lunarclientcdn.com
    publishAutoUpdate: true
    useMultipleRangeRequest: false
electronVersion: 25.3.0
```
