### ISSUE TITLE
Failed to uninstall old application  files on windows11

### ISSUE THREAD

**Issue by lichangwei123** [electron-userland/electron-builder#7865]
It fails halfway through the update, and various approaches have been tried many times
![img_v2_958f09ae-9ae1-476d-a703-3f85e997b69g](https://github.com/electron-userland/electron-builder/assets/46671582/3bdad896-afb7-4acc-95a6-69351329dbdb)
![img_v2_4cfeb187-a0af-4d20-b2e9-6038f7ebcb1g](https://github.com/electron-userland/electron-builder/assets/46671582/bb0b280b-cb84-4f7d-84db-24945fdffdbf)
![img_v2_3ad29b3b-13db-4474-a964-5edc0af487eg](https://github.com/electron-userland/electron-builder/assets/46671582/3943abb2-a86b-4e88-990f-b2524b16e0da)
```
"devDependencies": {
    "electron": "^27.0.3",
    "electron-builder": "^24.6.4",
  },
  "dependencies": {
    "electron-builder-squirrel-windows": "^24.8.0",
    "electron-log": "^5.0.0",
    "electron-updater": "^6.1.4"
  }
```

**Comment by lichangwei123** [comment]
electron-builder.yml


```
appId: cn.tiven.app
productName: electron-test2
copyright: Copyright © 2023 ${author}
asar: false
directories:
  buildResources: build
  output: dist
files:
  - '!**/.vscode/*'
  - '!dist2/*'
  - '!node_modules/*'
  - '!electron.vite.config.{js,ts,mjs,cjs}'
  - '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,[CHANGELOG.md](http://changelog.md/),[README.md](http://readme.md/)}'
  - '!{.env,.env.*,.npmrc,pnpm-lock.yaml}'
asarUnpack:
  - resources/**
win:
  certificateFile: build/北京新橙科技有限公司.pfx
  certificatePassword: iCourt123456
  executableName: electron-test2
  icon: resources/icon.ico
  publisherName: tiven
  verifyUpdateCodeSignature: false
  requestedExecutionLevel: highestAvailable #// 权限
  signingHashAlgorithms: [sha256]
  signDlls: true #// dll文件是否签名
  rfc3161TimeStampServer: http://timestamp.digicert.com/ #http://timestamp.comodoca.com/rfc3161 #// 时间戳"http://timestamp.globalsign.com/scripts/timestamp.dll"  "http://timestamp.digicert.com/" "http://timestamp.comodoca.com/rfc3161" "http://sha256timestamp.ws.symantec.com/sha256/timestamp"

  target:
    - nsis
    - squirrel
nsis:
  oneClick: false
  allowElevation: true
  artifactName: ${name}-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
  perMachine: false
  allowToChangeInstallationDirectory: true

squirrelWindows: #此处不可缺少
  loadingGif: resources/111.gif
  iconUrl: https://tiven.cn/static/img/net-stats.ico
mac:
  category: public.app-category.developer-tools
  entitlementsInherit: build/entitlements.mac.plist
  extendInfo:
    - NSCameraUsageDescription: Application requests access to the device's camera.
    - NSMicrophoneUsageDescription: Application requests access to the device's microphone.
    - NSDocumentsFolderUsageDescription: Application requests access to the user's Documents folder.
    - NSDownloadsFolderUsageDescription: Application requests access to the user's Downloads folder.
dmg:
  artifactName: ${name}-${version}.${ext}
linux:
  target:
    - AppImage
    - snap
    - deb
  maintainer: [electronjs.org](http://electronjs.org/)
  category: Utility
appImage:
  artifactName: ${name}-${version}.${ext}
npmRebuild: false
publish:
  provider: generic
  url: https://lawdawn-download.oss-cn-beijing.aliyuncs.com/win-2023-11-04-1/
```
