### ISSUE TITLE
How to supply Team ID when Signing

### ISSUE THREAD

**Issue by MadEddieFFS** [electron-userland/electron-builder#7873]
* **Electron-Builder Version** : 24.8.1

* **Node Version**: 20.5.0

* **Electron Version**: 25.0.1
* **Electron Type (current, beta, nightly)**: stable

* **Electron-updater**: 6.1.7

* **Target**: mac

Could anyone help - I can't find where to supply the Team ID for signing? **Please note I have obfuscated company name, Team ID and user in path** - am running
**electron-builder --mac** and receive the following:
```
electron-builder --mac

  • electron-builder  version=24.8.1 os=22.5.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=packages/test/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=25.9.4 appOutDir=packages/test/mac
  • signing         file=packages/test/mac/MyApp.app identityName=Developer ID Application: Company Name (TEAMID) identityHash=************************** provisioningProfile=none

  ⨯ Cannot destructure property 'teamId' of 'options' as it is undefined.  failedTask=build stackTrace=TypeError: Cannot destructure property 'teamId' of 'options' as it is undefined.

    at MacPackager.generateNotarizeOptions (/Users/*****/src/electron/node_modules/app-builder-lib/src/macPackager.ts:517:13)
    at MacPackager.notarizeIfProvided (/Users/*******/src/electron/node_modules/app-builder-lib/src/macPackager.ts:502:26)
    at MacPackager.sign (/Users/******/src/electron/node_modules/app-builder-lib/src/macPackager.ts:335:18)
    at /Users/******/src/electron/node_modules/app-builder-lib/src/macPackager.ts:465:11
From previous event:
    at processImmediate (node:internal/timers:478:21)
From previous event:
    at readDirectoryAndSign (/Users/********/src/electron/node_modules/app-builder-lib/src/macPackager.ts:463:29)
    at MacPackager.signApp (/Users/*********/src/electron/node_modules/app-builder-lib/src/macPackager.ts:473:11)
    at MacPackager.doSignAfterPack (/Users/***********/src/electron/node_modules/app-builder-lib/src/platformPackager.ts:332:21)
    at MacPackager.doPack (/Users/*********/src/electron/node_modules/app-builder-lib/src/platformPackager.ts:317:7)
    at MacPackager.pack (/Users/********/src/electron/node_modules/app-builder-lib/src/macPackager.ts:188:9)
    at Packager.doBuild (/Users/********/src/electron/node_modules/app-builder-lib/src/packager.ts:442:9)
    at executeFinally (/Users/**********/src/electron/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/**********/src/electron/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/*************/src/electron/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/Users/************/src/electron/node_modules/builder-util/src/promise.ts:12:14)

```
My package.json contains
```
"build": {
 "appId": *************,
 "productName":****************,
 "copyright": ********,
 "aftersign" : "./aftersignHook.js",
 "files" : *****
```

Would it be within the "notarize" section of "mac" ? I didn't do this because the notarize is handled within my afterSignHook.js

**Comment by mmaietta** [comment]
Try explicitly setting `notarize: false` in your config since it looks like some env vars are being read by electron-builder to run its own notarization process

**Comment by dombarnes** [comment]
This seems to happen for MAS builds too, which afaik do not need notarizing as this is done by Apple.
Event with `notarize: false` in my options this doesn't get picked up.
```yml
mas:
  hardenedRuntime: true
  provisioningProfile: build/MAS.provisionprofile
  category: public.app-category.utilities
  entitlements: build/entitlements.mas.plist
  entitlementsInherit: build/entitlements.mas.inherit.plist
  gatekeeperAssess: false
  type: distribution
  icon: build/Icon.icns
  bundleVersion: '49'
  identity: 'Apple Distribution: My Org'
  extendInfo: 'NO'
  notarize: false
  target:
    - target: mas
      arch:
      - universal
```
Electron Builder: v24.9.0
