### ISSUE TITLE
Unable to find app-update.yml in node_modeules/electron/dist/resources when cloned repository

### ISSUE THREAD

**Issue by franvico55** [electron-userland/electron-builder#7943]
* **Electron-Builder Version**: 24.9.1 or 17.10 (something strange, explained below)

* **Node Version**: v20.9.0

* **Electron Version**: 27.1.3
* **Electron Type (current, beta, nightly)**: current

* **Electron Updater Version**: 6.1.7

* **Target**: nsis

Hi!!

I am having trouble with electron-updater in my angular project.

In the main project I have been using everything works fine, but when I clone it from mi gitlab repository I get the error:
`11:42:59.482 > Checking for update`
`11:42:59.522 > Error: Error: ENOENT: no such file or directory, open 'D:\...\fuse-template\node_modules\electron\dist\resources\app-update.yml'`
`11:42:59.523 > Error in auto-updater.`

I have no idea why it isn't generating this file, I guess something to see with .gitignore??

I also have observed that in the run messages, I get this version of electron-builder: 
`electron-builder  version=24.9.1 os=10.0.22621`
but if I do `npm ls | select-string electron` I get `electron-builder@17.10.0`

I have checked builder-effective-config-yaml and didn't find anythins suspicious.

Appreciate any possible help you can lend me
Thx!!!

**Comment by franvico55** [comment]
To bring up some more context, I think this info from _builder-effective-config.yaml_

```
directories:
  output: dist/fuse/
  buildResources: build

files:
  - filter:
      - '!.angular'
      - build/**
      - '!src'
      - app.js
      - package.json
```

My _outputPath_ for angular.json is "build" in order to separate angular build and electron-builder one.
