### ISSUE TITLE
Unable to sign NSIS

### ISSUE THREAD

**Issue by idoodler** [electron-userland/electron-builder#7973]
* **Electron-Builder Version**: 24.11.0

* **Node Version**: 19.8.2

* **Electron Version**: 28.1.4
* **Electron Type (current, beta, nightly)**: current

* **Target**: nsis (x64)

I am tryingg to build our Windows app in Docker, however I am always getting the following signing error:
```
⨯ Exit code: 255. Command failed: /root/.cache/electron-builder/winCodeSign/winCodeSign-2.6.0/linux/osslsigncode -in **REDACTED**E.exe -out **REDACTED**-signed-sha256.exe -t http://timestamp.digicert.com -pkcs12 ./build/**REDACTED**.p12 -h sha256 -n **REDACTED** -i **REDACTED** -nest -pass **REDACTED** (sha256 hash) to extract existing signature in -nest mode
```

We are using gitlab, here is the part ofthe `.gitlab.yml`
```yml
Windows:
    stage: build
    tags:
        - docker
    image: electronuserland/builder:wine
    script:
        - yarn
        - yarn run gsf:download --secretId 6 -o apps/raptor-electron # downloads the electron-builder.env
        - yarn workspace @**REDACTED**/raptor-electron run compile -w # Here it stops with the exception
        - mv 'apps/raptor-electron/dist/**REDACTED**.exe' './'
        - mv 'apps/raptor-electron/dist/**REDACTED**.exe.blockmap' './'
        - yarn workspace @**REDACTED**/raptor-electron run compile:appx
        - mv 'apps/raptor-electron/dist/**REDACTED**.appxbundle' './'
    artifacts:
        paths:
            - **REDACTED**.exe
            - **REDACTED**.exe.blockmap
            - **REDACTED**.appxbundle
    rules:
        - if: $NIGHTLY =~ /raptor/
          when: on_success
        - changes:
              - apps/raptor/**/*
              - apps/raptor-electron/**/*
          when: on_success
```

I first thought that the password of the Certificate file is wrong, but it is verified and correct. We are using the `electron-builder.env` file in the projects root directory which is downloaded by the build script. As a key for the Certificate File I am using `WIN_CSC_KEY_PASSWORD`

The job is executed on a Debian Machine
