### ISSUE TITLE
bug:The next button style of the installation package is abnormal

### ISSUE THREAD

**Issue by fly-bue** [electron-userland/electron-builder#8003]
* **Electron-Builder Version Version**: 23.6.0
* **Electron Version**: 23.3.13
* **Node Version**: 16.15.1
* **Target**: Windows 11
Hi, I am new to electron and electron-builder. I have this config (see below). when I open my application,The next button style of the installation package is abnormal.Can someone help me on this? Thank you in advance.

```
win:
  icon: resources/icons/WindowsLauncherIcon/SugonRI.ico
  target:
    - nsis
  publish:
    provider: generic
    url: ""
    useMultipleRangeRequest: false
nsis:
  warningsAsErrors: false
  menuCategory: true
  oneClick: false
  perMachine: false
  installerHeaderIcon: resources/icons/WindowsLauncherIcon/SugonRI.ico
  installerIcon: resources/icons/WindowsLauncherIcon/SugonRI.ico
  uninstallerIcon: resources/icons/WindowsLauncherIcon/SugonRI.ico
  installerSidebar: resources/icons/InstallerSidebarImage/164-314Windows.bmp
  uninstallerSidebar: resources/icons/InstallerSidebarImage/164-314Windows.bmp
  allowToChangeInstallationDirectory: true
  runAfterFinish: false
  artifactName: ${productName} Setup.${ext}
  license: LICENSE
  include: resources/installer.nsh
```
![image](https://github.com/electron-userland/electron-builder/assets/54001753/c2b83894-b688-464e-8dd0-0a2fb8a420a5)
