### ISSUE TITLE
App dependency not being packaged in app.asar (node_modules folder empty)

### ISSUE THREAD

**Issue by lbssousa** [electron-userland/electron-builder#801]
- **Version**: 7.11.2

- **Target**: Windows (7z, nsis), Linux (AppImage, deb)

I'm trying to package an app which has runtime dependency on `electron-localshortcut`. I've declared `"electron-localshortcut": "^0.6.1"` in both `"devDependencies"` (at development `package.json` file) and `"dependencies"` (at application `package.json` file).

However, when I try to launch the app, it gives me an error message telling that `electron-localshortcut` module was not found. Investigating the contents of `dist/*-unpacked/resources/app.asar`, it seems that folder `node_modules` remains empty after building.

**Comment by develar** [comment]
Could you please provide sample project? Are you sure that `electron-localshortcut` is not in the devDependencies of app package.json? And installed (electron-builder doesn't install dependencies).

**Comment by lbssousa** [comment]
Let me describe better my current setup:

* I have only `"dependencies"`in my application `package.json` file.
* I'm building my app in a clean environment (Docker comtainer). My current `docker-compose.yml` has the following contents:

```
app:
  build: .
  command: sh -c "rm -rf dist*; npm cache clear; npm install; npm update; npm prune; npm run dist"
  volumes:
    - ~/.electron:/root/.electron:Z
    - .:/project:Z
    - app-node-modules:/project/node_modules:Z
```

* My development `package.json` contains the following scripts:

```
"scripts": {
    "start": "npm install && electron ./app",
    "pack": "build --dir",
    "dist": "npm install && build -wl --x64 --ia32",
    "dist:linux": "npm install && build -l --x64 --ia32",
    "dist:win": "npm install && build -w --x64 --ia32",
    "release": "build"
  }
```

Should I have to run `cd ./app && npm install` somewhere in my scripts?
