### ISSUE TITLE
Mac build for both x64 and arm64 leads to duplicates in yaml file

### ISSUE THREAD

**Issue by MuhKuh7** [electron-userland/electron-builder#8039]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 20.11.0

* **Electron Version**: 28.2.0
* **Electron Type (current, beta, nightly)**:

* **Target**: dmg mac x64 and arm64

I am running `electron-builder --mac --x64 --arm64 --publish never` to simultaneously build x64 and arm64. The resulting yaml files however somehow list the arm64 version 3 times.

Resulting `latest-mac.yml`
```
version: 1.7.0
files:
  - url: MyApp-1.7.0.dmg
    sha512: fcc+w/bEp3j2JIQqfl/+S7JpJGwm+5kgdYpQfAImK22yGGhX/ubvoeJimYIGywMOvc/6o7HuCM6C9TAuPiUIGQ==
    size: 207777121
  - url: MyApp-1.7.0-arm64.dmg
    sha512: CCVENWspW5Kef/x5ul2yzHoTtTdkLr+qJbeL1qZPnfPeQxS+xo62KVOLm78z6hwXKt6QNSu6WLRmJDVPMwTGmQ==
    size: 202708519
  - url: MyApp-1.7.0-arm64.dmg
    sha512: CCVENWspW5Kef/x5ul2yzHoTtTdkLr+qJbeL1qZPnfPeQxS+xo62KVOLm78z6hwXKt6QNSu6WLRmJDVPMwTGmQ==
    size: 202708519
  - url: MyApp-1.7.0-arm64.dmg
    sha512: CCVENWspW5Kef/x5ul2yzHoTtTdkLr+qJbeL1qZPnfPeQxS+xo62KVOLm78z6hwXKt6QNSu6WLRmJDVPMwTGmQ==
    size: 202708519
path: MyApp-1.7.0.dmg
sha512: fcc+w/bEp3j2JIQqfl/+S7JpJGwm+5kgdYpQfAImK22yGGhX/ubvoeJimYIGywMOvc/6o7HuCM6C9TAuPiUIGQ==
releaseDate: '2024-02-07T19:55:42.847Z'
```
