### ISSUE TITLE
GitHub release not created  reason=existing type not compatible with publishing

### ISSUE THREAD

**Issue by Thatoo** [electron-userland/electron-builder#8179]
I'm sorry, I'm completely new to electron. I'll try to explain as well as I can my issue.
I'm trying to make Github action build and publish an appimage when I create a new release.

When it comes to `npm run build -d -- --linux`, it doesn't end on error but it says : 
```
  • GitHub release not created  reason=existing type not compatible with publishing type tag=v0.0.1 version=0.0.1 existingType=release publishingType=draft
  • skipped publishing  file=Accolades-Linux-0.0.1.AppImage reason=existing type not compatible with publishing type tag=v0.0.1 version=0.0.1 existingType=release publishingType=draft
  • skipped publishing  file=latest-linux.yml reason=existing type not compatible with publishing type tag=v0.0.1 version=0.0.1 existingType=release publishingType=draft
```

My .github/workflows/npm-publish-github-packages.yml file is as follow : 

```
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build -d -- --linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

It succeed but then I don't find any .appimage file in `Releases` not in `Pachages`.
If it helps, here is my repo : https://github.com/Thatoo/nextcloud-electron/tree/Thatoo-patch-1
(I didn't touch to master branch to make github action work)

Thank you for your help.
