### ISSUE TITLE
Enable Bitbucket Access Token Authentication for Electron Builder

### ISSUE THREAD

**Issue by cek61** [electron-userland/electron-builder#8204]
* **Electron-Builder Version**: 24.9.1

* **Node Version**: 21.7.1

* **Electron Version**: 28.2.0
* **Electron Type (current, beta, nightly)**: current

* **Electron Updater Version**: 6.1.7

* **Target**: all

**Issue:**
When using Bitbucket as provider for publishing it is only possible to authenticate via username and token. I would like to use a repository access token for authentication. It looks like it is not possible because the BitbucketPublisher always creates a Basic Authentication header.

Current configuration needs to be like this:
```yml
publish:
    provider: bitbucket
    owner: <owner> 
    slug: <slug>
    username: <bitbucket-username> # optional, if username != owner
    token: <bitbucket-app-password>
```

**Why do I need this:**
My Bitbucket repository is a private repository with multiple contributors. The pipeline needs to build and publish my app. I don't want to use my personal username and app password neither I want to create a technical user.

**Solution:**
Bitbucket provides the option to use access tokens. We would need to figure out how to pass an access token to the publish config. It should be treated as Bearer Token and not as Basic Authentication. 

**Approach:**
Introduce a new config value named "accessToken" for new authentication method. If it is provided then always try to use it as Bearer Token. 

I would like to configure the provider like this:
```yml
publish:
    provider: bitbucket
    owner: <owner> 
    slug: <slug>
    accessToken: <bitbucket-access-token>
```
    
The access token then needs to be in the request header as Bearer token. Using this method I don't need to pass a username.
