### ISSUE TITLE
Keygen provider not working with target 'nsis-web'

### ISSUE THREAD

**Issue by vincaslt** [electron-userland/electron-builder#8231]
* **Electron-Builder Version**: 24.13.3

* **Node Version**: v20.11.1

* **Electron Version**: 30.0.6
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows nsis-web

Keygen provider is not working with nsis-web target, the publishing process throws:

```
⨯ Not supported provider: keygen  failedTask=build stackTrace=Error: Not 
supported provider: keygen
```

Looking at the source code, it seems like keygen.sh provider is treated as S3-like download in `computeDownloadUrl`, but the actual base path resolution only supports "s3" and "spaces" providers: https://github.com/electron-userland/electron-builder/blob/77f977435c99247d5db395895618b150f5006e8f/packages/builder-util-runtime/src/publishOptions.ts#L384C3-L389C4

@ezekg would you know if keygen.sh is supposed to support nsis-web targets?

The electron-builder.yml file:
```
win:
  executableName: XXX
  target:
    - nsis-web
nsisWeb:
  artifactName: ${productName}-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
  oneClick: false
  allowToChangeInstallationDirectory: true
publish:
  provider: 'keygen'
  account: '123'
  product: '123'
  channel: 'stable'
```
