### ISSUE TITLE
GitHubProvider: Doesn't use custom channel that was set in the electron-builder config

### ISSUE THREAD

**Issue by jermy-c** [electron-userland/electron-builder#8388]
* **Electron-Builder Version**: 24.13.3

* **Node Version**: v20.15.0

* **Electron Version**: 25.9.8
* **Electron Type (current, beta, nightly)**: current

* **Target**: Mac OS X arm64

**Reproduction**

1. Set `electron-builder.yml` with the following settings:
```yml
publish:
  - provider: github
    protocol: https
    releaseType: release
    channel: customChannel
```

**Actual Result**

1. The build generates a `customChannel-mac.yml`
2. The executable from the build still tries to fetch `latest-mac.yml` and gives an error

**Expected Result**

1. The build generates a `customChannel-mac.yml`
2. The executable from the build still tries to fetch `customChannel-mac.yml`
3. Use the `customChannel` name as the latest channel

**Question**

1. Is there a way to have the executable fetch `customChannel-mac.yml` as the update metadata?
