### ISSUE TITLE
Semantic Versioning Compare Error

### ISSUE THREAD

**Issue by RonnieLincoln** [electron-userland/electron-builder#8416]
* **Electron-Builder Version**: 
22.13.1

* **Node Version**: 
v20.12.2

* **Electron Version**:
27.0.2
* **Electron Type (current, beta, nightly)**:

6.2.1

* **Target**: 
nsis

Hi, 
current is `"version": "4.2.0"`,
and the latest.yml file:

```
version: 4.1.33
files:
  - url: xxx.exe
    sha512: 7xVnasfGiPFOUtD8S3F6G9Y3ImtvhgxC/MKD8Pi0+1jCufVqMRl+ZXEj5Jx5ojAzgkrIT65Mynglc0JaVQszSA==
    size: 118694382
path: xxx.exe
sha512: 7xVnasfGiPFOUtD8S3F6G9Y3ImtvhgxC/MKD8Pi0+1jCufVqMRl+ZXEj5Jx5ojAzgkrIT65Mynglc0JaVQszSA==
releaseDate: '2024-08-14T09:41:12.729Z'
```

when I checkForUpdates, the event `update-available` is triggered.
