### ISSUE TITLE
app-builder.exe (x64) crashes when fetching electron mirror

### ISSUE THREAD

**Issue by ErickRodrCodes** [electron-userland/electron-builder#8522]
* **Electron-Builder Version**:  25.0.5

* **Node Version**:   20.17.0

* **Electron Version**: 31.3.1
* **Electron Type (current, beta, nightly)**: current

* **Target**:  windows

OS: Windows 11 22H2

Problems started today when publishing. Not sure if there was a change when I updated electron builder from 24.13.3 to 25.0.5. Before I was able to build properly files without no inconvenient. It seems that the process to download the mirror fails:

![image](https://github.com/user-attachments/assets/26957ac1-0f04-495d-a4ba-f795f363bfab)

The exit code is being produced by the app-builder.exe file

The yaml configuration for my project provided all needed options, and even by removing  `electronDownload` section, the github link still fails.

```yaml
appId: frontend.electron.app
productName: frontend
directories:
  buildResources: build
files:
  - '!**/*'
  - 'dist/apps/frontend'
  - '!dist/apps/frontend/package.json'
  - 'dist/apps/frontend-electron'
  - 'dist/apps/frontend-electron-icons'
asarUnpack:
  - resources/**
win:
  executableName: frontend
  icon: dist/apps/frontend-electron-icons/icon.ico
  publisherName: 'Erick Rodriguez'
  # Uncomment the following lines if you will include certification
  # information on this file (change accordingly):
  # certificateFile: apps/frontend/electron/resources/certificate/Self.pfx
  # certificatePassword: ""
nsis:
  installerIcon: dist/apps/frontend-electron-icons/setup.ico
  artifactName: frontend-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
  include: C:\git-projects\ErickRodrCodes\medical-equipment-record\apps\frontend\electron\install.nsh
mac:
  entitlementsInherit: dist/apps/frontend-entitlements/entitlements.mac.plist
  icon: dist/apps/frontend-electron-icons/icon.icns
  extendInfo:
    - NSCameraUsageDescription: Application requests access to the device's camera.
    - NSMicrophoneUsageDescription: Application requests access to the device's microphone.
    - NSDocumentsFolderUsageDescription: Application requests access to the user's Documents folder.
    - NSDownloadsFolderUsageDescription: Application requests access to the user's Downloads folder.
  notarize: false
dmg:
  artifactName: frontend-${version}.${ext}
linux:
  icon: dist/apps/frontend-electron-icons/icon.ico
  target:
    - AppImage
    - snap
    - deb
  maintainer: electronjs.org
  category: Utility
appImage:
  artifactName: frontend-${version}.${ext}
npmRebuild: false
publish:
  provider: generic
  url: https://example.com/auto-updates
electronDownload:
  mirror: https://npmmirror.com/mirrors/electron/
```
