### ISSUE TITLE
Linux zip and tar.gz missing when building

### ISSUE THREAD

**Issue by f908** [electron-userland/electron-builder#8544]
* **Electron-Builder Version**: 25.0.5

* **Node Version**: 20.16.0

* **Electron Version**: 32.1.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: linux, windows zip,tar.gz,nsis

So, i migrated from package.json to electron-builder.yml to define my build settings.
Then i noticed that tar.gz builds are missing, so i started editing the config.
After editing the config, i noticed both zip and tar.gz missing now.

I have attached my electron-builder.yml here:
[electron-builder.txt](https://github.com/user-attachments/files/17174394/electron-builder.txt)

**Comment by mmaietta** [comment]
How are you executing electron-builder? Are you passing in a `--config <path-to-.yml>`. I was unable to reproduce the issue with your config.

**Comment by f908** [comment]
> How are you executing electron-builder? Are you passing in a `--config <path-to-.yml>`. I was unable to reproduce the issue with your config.

No need to pass such a argument, when you use the default electron-builder.yml (i send it as a txt format because of GitHub upload limitations) you don't need to pass the argument afaik

**Comment by mmaietta** [comment]
Can you post what your `file=dist/builder-effective-config.yaml` config is? Location is spit out in the first few lines of the build logs.

**Comment by f908** [comment]
> Can you post what your `file=dist/builder-effective-config.yaml` config is? Location is spit out in the first few lines of the build logs.

Sure (had to copy as txt because github refuses yaml files)
[builder-effective-config.txt](https://github.com/user-attachments/files/17175839/builder-effective-config.txt)

**Comment by mmaietta** [comment]
Hmmm, would you mind sharing your previous electron-builder config you had in your package.json? Or a link to your project repo if that's easier

Did this issue start after updating electron-builder from 24.x->25.x? Or only when you started migrating to a yml config?

**Comment by f908** [comment]
> Hmmm, would you mind sharing your previous electron-builder config you had in your package.json? Or a link to your project repo if that's easier
> 
> Did this issue start after updating electron-builder from 24.x->25.x? Or only when you started migrating to a yml config?

Sure, if that helps.
I have updated to 25.0.5 of electron-builder and 32.1.2 version of electron just today .
[package.json](https://github.com/user-attachments/files/17175891/package.json)

**Comment by mmaietta** [comment]
<img width="840" alt="Screenshot 2024-09-28 at 1 20 45 PM" src="https://github.com/user-attachments/assets/dfa6f054-c32f-4d34-bdc5-a309cce1519d">

So I'm unable to reproduce your issue with the config below. `zip` and `tar.gz` are both output into the dist directory.
```
appId: com.f908.eaglercraft-electron-1.8
productName: EaglercraftX
win:
  target:
    - target: nsis
    - target: zip
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  warningsAsErrors: false
linux:
  maintainer: idontknow3667@proton.me
  category: Game
  target:
    - target: zip
      arch:
        - x64
    - target: tar.gz
      arch:
        - x64
  desktop:
    Name: EaglercraftX
```
