### ISSUE TITLE
Universal Mac App - Not able to run in x64 environment - error: Invalid or incompatible cached data (cachedDataRejected)

### ISSUE THREAD

**Issue by AndrewEQ** [electron-userland/electron-builder#8550]
* **Electron-Builder Version**:  "^25.0.5"

* **Node Version**: v20.16.0

* **Electron Version**: ^32.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**:  
    - target: 'default'
      arch:
        - universal

I'm successful in building an app for Intel and Apple Silicon separately (both execute fine after they are each built in their own OS), but I am not successful in building a universal app on an M1 for both that executes correctly; when I run the universal app on arm64 it launches fine but when I run it on the Intel based Mac it fires the following JS error straight away: 
```Invalid or incompatible cached data (cachedDataRejected)```.

During the build process where it creates a tmp app for x64 and arm64, I grab the x64 version before it includes it in the universal just to see if it will run on the Intel Mac and the same error is fired as soon as its run.

Is there a setting I'm missing?

The core of my build yaml:
```
directories:
  buildResources: build
files:
  - '!**/.vscode/*'
  - '!src/*'
  - '!electron.vite.config.{js,ts,mjs,cjs}'
  - '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}'
  - '!{.env,.env.*,.npmrc,pnpm-lock.yaml}'
  - '!{tsconfig.json,tsconfig.node.json,tsconfig.web.json}'
asar: true
asarUnpack:
  - '**/*.node'
  - resources/**
  - resources/**/**
  - resources/icons/**
  - resources/browsericons/**
afterSign: afterSignHook.js
mac:
  category: public.app-category.utilities
  hardenedRuntime: true
  gatekeeperAssess: false
  entitlementsInherit: build/entitlements.mac.plist
  target:
    - target: 'default'
      arch:
        - universal
appImage:
  artifactName: ${name}-${version}.${ext}
```
