### ISSUE TITLE
NSIS does not work on GitHub Actions

### ISSUE THREAD

**Issue by minai621** [electron-userland/electron-builder#8613]
* **Electron-Builder Version**: 25.1.8

* **Node Version**: 18.x

* **Electron Version**: 33.0.1
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows

When using windows@latest as the GitHub Actions runner OS, the default version of NSIS is 3.10.0.

However, electron-builder requires version 3.0.4.1, and because it cannot find this version, the following error occurs:

```
exited          command=makensis.exe code=-4058 pid=undefined
⨯ spawn C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe ENOENT  failedTask=build stackTrace=Error: spawn C:\Users\runneradmin\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe ENOENT
```

Here is my action script 
```yaml
name: electron-build
on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install --prefer-offline --no-frozen-lockfile

      - name: Deploy native project
        run: pnpm --filter native deploy ./standalone-native

      - name: Build/release Electron app (macOS and Linux)
        if: runner.os != 'Windows'
        env:
          GH_TOKEN: ${{ secrets.github_token }}
          DEBUG: electron-builder
        working-directory: ./standalone-native
        run: pnpm run release

      - name: Build/release Electron app (Windows)
        if: runner.os == 'Windows'
        env:
          GH_TOKEN: ${{ secrets.github_token }}
          DEBUG: electron-builder,electron-builder:*
        working-directory: ./standalone-native
        run: pnpm run build && pnpx electron-builder --win --x64 --publish always
```
My package.json build configuration is as follows
```json
"build": {
    "publish": {
      "provider": "github",
      "releaseType": "draft"
    },
    "appId": "com.example.product",
    "productName": "product",
    "files": [
      "dist/**/*",
      "node_modules/**/*",
      "package.json",
      "!node_modules/**/*.{ts,map}"
    ],
    "directories": {
      "output": "release"
    },
    "mac": {
      "target": "dmg"
    },
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64"
          ]
        }
      ]
    },
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true
    },
    "linux": {
      "target": "AppImage"
    }
  }
```
It seems that the issue is related to the cache for NSIS `electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe ENOENT`
Could you help me understand why this issue occurs and what might be causing the cache problem?
