### ISSUE TITLE
Code signing / notarizing help

### ISSUE THREAD

**Issue by mrmartineau** [electron-userland/electron-builder#8628]
* **Electron-Builder Version**: 
```
"electron-builder": "^24.13.3",
"electron-builder-notarize": "^1.5.2",
"electron-updater": "6.3.4",
```
* **Node Version**: v22.6.0
* **Electron Version**: ^32.1.0
* **Electron Type (current, beta, nightly)**: Current
* **Target**: MacOS and Windows. Not distributing through the Windows store or Mac App Store.
---
I am trying to get an internal app code signed / notarized so that we can allow users to auto update without issue. I am fairly new Electron but even newer to code signing etc.

The code signing docs [here](https://www.electron.build/code-signing) are confusing (Windows and Mac information is mixed together for example) so I am hoping for some clarification. It recommends [this article](https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/) right at the top but that article only concerns Mac apps and does not mention the `CSC_*` environment variables. 

It seems that there are a few different ways to code sign using electron builder so I would like help to know what route I should take, and with any luck, help to improve the docs based off the response here.

For context, I would like to use CI (in my case GitHub Actions) to build and code sign my app. Because of this, I think I should be using (for Mac at least) an App Store Connect API key, issuer etc

With that in mind, do I need the `CSC_*` environment variables at all?

Should I set `mac.notarize = true` like below? The docs [here](https://www.electron.build/mac#notarize) suggest that I can set it to `true` and then add these env vars: `APPLE_API_KEY`, `APPLE_API_KEY_ID` and `APPLE_API_ISSUER`. Is that enough? For me, I get the `Failed to staple your application with code: 65` error which leads me to [this comment thread](https://github.com/electron/notarize/issues/120#issuecomment-1382039042) on the @electron/notarize repo which suggests that it is a certificate issue..

My electron builder config is below. You will see that I have commented out the `afterSign: scripts/mac-notarise.js` item. This was added based on the recommended article mentioned above. If I have `afterSign` does that mean that there's no need for the `mac.notarize` key? Are they mutually exclusive?

On **Windows**, I have a Digicert hardware key (EV code signing certificate) and I'm fairly certain that it won't be possible to make use of it on CI. I think I can export the certificate but even then the hardware key would still be needed.. I think. Can someone clarify?

```yml
appId: com.cool.app
productName: AppName
directories:
  buildResources: buildResources
files:
  - "!**/.vscode/*"
  - "!src/*"
  - "!electron.vite.config.{js,ts,mjs,cjs}"
  - "!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}"
  - "!{.env,.env.*,.npmrc,pnpm-lock.yaml}"
  - "!{tsconfig.json,tsconfig.node.json,tsconfig.web.json}"
  - "!buildResources/*.p12"
  - "!buildResources/*.txt"
asarUnpack:
  - resources/**
npmRebuild: false
publish:
  provider: generic
  url: https://electron-updates.com

# Windows
win:
  executableName: AppName
nsis:
  artifactName: ${name}-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always

# MacOS
mac:
  notarize: true
  hardenedRuntime: true
  entitlements: buildResources/entitlements.mac.plist
  entitlementsInherit: buildResources/entitlements.mac.plist
  gatekeeperAssess: false
dmg:
  artifactName: ${name}-${version}.${ext}
  sign: false

# MacOS Notarisation
# afterSign: scripts/mac-notarise.js
```
