### ISSUE TITLE
[ Windows - arm64 • ⨯ zip: not a valid zip file ] - Setting arch doesn't override defaultArch

### ISSUE THREAD

**Issue by sipsuru** [electron-userland/electron-builder#8699]
* **Electron-Builder Version**: 25.1.8

* **Node Version**: 22.8.0

* **Electron Version**: 33.2.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: nsis, zip, 7z, portable, msi (arch: x64, ia32, arm64)

#8687 is a previous issue I opened. Might be related to it.

I'm building my electron app for multiplatform & cross arch.

Here the electron-builder configuration for Windows
```yml
win:
  target:
    - target: nsis
      arch: [x64, ia32, arm64]
    - target: msi
      arch: [x64, ia32, arm64]
    - target: portable
      arch: [x64, ia32, arm64]
    - target: zip
      arch: [x64, ia32, arm64]
    - target: 7z
      arch: [x64, ia32, arm64]
  executableName: wp-downloader-electron
nsis:
  artifactName: ${name}-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always

npmRebuild: true

publish:
  provider: generic
  url: https://example.com/auto-updates

electronDownload:
  mirror: https://npmmirror.com/mirrors/electron/
```

And it leaves me with:

```bash
• downloading     url=https://npmmirror.com/mirrors/electron/v33.2.0/electron-v33.2.0-win32-arm64.zip size=120 MB parts=8
  • retrying        attempt=1
  • retrying        attempt=1
  • retrying        attempt=1
  • retrying        attempt=1
  • retrying        attempt=1
  • retrying        attempt=1
  • retrying        attempt=1
  • signing with signtool.exe  path=dist\wp-downloader-electron 1.0.0.msi
  • no signing info identified, signing is skipped  signHook=false cscInfo=null
  • signing with signtool.exe  path=dist\wp-downloader-electron 1.0.0 ia32.msi
  • no signing info identified, signing is skipped  signHook=false cscInfo=null
  • downloaded      url=https://npmmirror.com/mirrors/electron/v33.2.0/electron-v33.2.0-win32-arm64.zip duration=6m16.254s
  ⨯ zip: not a valid zip file
github.com/develar/app-builder/pkg/archive/zipx.(*Extractor).extractAndWriteFile
	/Users/runner/work/app-builder/app-builder/pkg/archive/zipx/unzip.go:234
github.com/develar/app-builder/pkg/archive/zipx.Unzip.func1.1
	/Users/runner/work/app-builder/app-builder/pkg/archive/zipx/unzip.go:104
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
	/Users/runner/work/app-builder/app-builder/pkg/util/async.go:68
runtime.goexit
	/Users/runner/hostedtoolcache/go/1.21.13/arm64/src/runtime/asm_amd64.s:16[50](https://github.com/sipsuru/wp-downloader-electron/actions/runs/11930938744/job/33252739649#step:8:51)  
  ⨯ D:\a\wp-downloader-electron\wp-downloader-electron\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: D:\a\wp-downloader-electron\wp-downloader-electron\node_modules\app-builder-bin\win\x64\app-builder.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (D:\a\wp-downloader-electron\wp-downloader-electron\node_modules\builder-util\src\util.ts:2[55](https://github.com/sipsuru/wp-downloader-electron/actions/runs/11930938744/job/33252739649#step:8:56):14)
    at Object.onceWrapper (node:events:622:26)
    at ChildProcess.emit (node:events:507:28)
    at ChildProcess.cp.emit (D:\a\wp-downloader-electron\wp-downloader-electron\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1101:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
Error: Process completed with exit code 1.
```
 - While building `arm64` artifacts.
 
 Here's the [repo](https://github.com/sipsuru/wp-downloader-electron) for failing build, and the [workflow run](https://github.com/sipsuru/wp-downloader-electron/actions/runs/11930938744/job/33252739649) and the [electron-builder.yml](https://github.com/sipsuru/wp-downloader-electron/blob/main/electron-builder.yml).

 ---

 But the most confusing thing is when using same configuration for the same electron app in [this repo], but only with Windows configurations, it builds without any errors. 
 
 [Here the repo](https://github.com/WPDLDeploy/wp-downloader-electron-arm64-test) and [actions workflow run](https://github.com/WPDLDeploy/wp-downloader-electron-arm64-test/actions/runs/11930648037) and [electron-builder.yml](https://github.com/WPDLDeploy/wp-downloader-electron-arm64-test/blob/main/electron-builder.yml) of the same application that's building succesfully.
 
 ---
 
 I'm so lost here. Is it because I'm building for all platforms in the first repo I mentioned here? Or what?
