### ISSUE TITLE
Arch Linux pacman distribution incomplete, breaks auto update

### ISSUE THREAD

**Issue by chrbayer84** [electron-userland/electron-builder#8710]
* **Electron-Builder Version**: 25.0.5

* **Node Version**: 18.20.5

* **Electron Version**: 31.0.2
* **Electron Type (current, beta, nightly)**: current

* **Electron-updater**: 6.1.7

* **Target**:  Arch Linux/Pacman

The pacman build does not produce a latest-linux.yml manifest file (unlike the other targets like deb, rpm etc). That seems to break auto-update capabilities on Arch Linux. Our app auto-updates fine on Windows, Debian and RPM-based distros, however the updater does not find a new pacman distribution package and instead tries to download and install an rpm:

Output of auto-update on Arch Linux (Manjaro but vanilla Arch does the same): 
```
13:30:02.184 › Checking for update
13:30:03.541 › Found version 2.241124.0 (url: GridTracker2-2.241124.0-x86_64.AppImage, GridTracker2-2.241124.0-amd64.deb, GridTracker2-2.241124.0-x86_64.rpm)
13:30:03.544 › Downloading update from GridTracker2-2.241124.0-x86_64.AppImage, GridTracker2-2.241124.0-amd64.deb, GridTracker2-2.241124.0-x86_64.rpm
13:30:03.551 › updater cache dir: /home/christian/.cache/gridtracker2-updater
13:30:05.317 › Update has already been downloaded to /home/christian/.cache/gridtracker2-updater/pending/GridTracker2-2.241124.0-x86_64.rpm).
```
We believe that the missing manifest is at least part of the problem. here is what it generates for a deb package:
```
~/Downloads/gridtracker2/dist $ ls
__appImage-x64     builder-effective-config.yaml      GridTracker2-2.241123.1-x64.pacman  linux-unpacked
builder-debug.yml  GridTracker2-2.241123.1-amd64.deb  latest-linux.yml
 ~/Downloads/gridtracker2/dist $ cat latest-linux.yml
version: 2.241123.1
files:
  - url: GridTracker2-2.241123.1-amd64.deb
    sha512: SsEKPLFcPdHzgS492F1WDCUrsEDJYUdaUX9AfQXGQIi23DhJptP8PCVmFEeykB6D3e2KJxEV1LWQEwhqb0/piQ==
    size: 96541614
path: GridTracker2-2.241123.1-amd64.deb
sha512: SsEKPLFcPdHzgS492F1WDCUrsEDJYUdaUX9AfQXGQIi23DhJptP8PCVmFEeykB6D3e2KJxEV1LWQEwhqb0/piQ==
releaseDate: '2024-11-26T20:13:25.394Z'
```
relevant section in `electron-builder.yml`, full file: https://gitlab.com/gridtracker.org/gridtracker2/-/blob/main/electron-builder.yml?ref_type=heads
```
[..]
linux:
  target:
    - deb
    - pacman
    # freebsd # These aren't true FreeBSD builds, it's a Lin AMD64 binary in FreeBSD wrapper which isn't BSD legal
    # requires building on a linux machine or a multipass.run account
    #- snap
  maintainer: gridtracker.org
  category: Utility
  artifactName: ${name}-${version}-${arch}.${ext}
flatpak:
  runtimeVersion: 23.08
npmRebuild: false
publish:
  provider: generic
  url: https://download2.gridtracker.org
```
