### ISSUE TITLE
allowPrerelease not working for GitHub provider

### ISSUE THREAD

**Issue by itsskofficial** [electron-userland/electron-builder#8893]
I have been trying this for long but I don't get how to release stable and beta versions for my users. As GitHub doesn't support channels I aim to treat Pre-Releases as beta releases and Latest Releases as stable releases for my users. I want to conditionally allow prerelease auto updates based on whether the user is in the beta program or not

I tried setting `autoUpdater.allowPrelease = true` and released v1.4.4 as Pre-Release on GitHub. Then I released v1.4.5 with the same config. I also tried setting channel to beta and releasing with v1.4.5-beta but to no avail. It seems auto update is not triggered at all for pre releases cause the same scenario works well for latest releases in my case

Here is my code

```
const checkForUpdates = async () => {
	const betaUserStatus = await getBetaUserStatus() // this is set conditonally

	if (betaUserStatus) {

		autoUpdater.allowPrerelease = true
	} 

	if(autoUpdater.allowPrerelease) {
		writeToLog("Checking for updates (beta)") // i can see this log in my log file
	}

	createAppWindow()

	autoUpdater.checkForUpdatesAndNotify()
}
```

Here is my Electron builder config

```
appId: "com.existence-sentient.sentient"
productName: "Sentient"
copyright: "Existence"
generateUpdatesFilesForAllChannels: true

win:
  target:
    - "nsis"
    - "dir"
  icon: "public/images/half-logo-dark.png"
  requestedExecutionLevel: "requireAdministrator"

nsis:
  allowToChangeInstallationDirectory: false
  runAfterFinish: false
  createDesktopShortcut: true
  createStartMenuShortcut: true
  include: "build/installer.nsh"
  artifactName: "ClientInstaller.${ext}"

linux:
  target:
    - "AppImage"
    - "deb"
  icon: "public/images/half-logo-dark.png"

mac:
  target:
    - "dmg"
    - "zip"
  icon: "public/images/half-logo-dark.png"

extraResources:
  - ".env"

publish:
  provider: "github"
  owner: "existence-master"
  repo: "Sentient-Internal"
```

I don't understand what to do. Ideally, this should work. 

Any help is appreciated
