### ISSUE TITLE
[docker wine] corepack cannot use pnpm

### ISSUE THREAD

**Issue by thomasneger** [electron-userland/electron-builder#8925]
Hi, this is an upstream issue (see https://github.com/nodejs/corepack/issues/627#issuecomment-2685646029) that was fixed with Node.js version 22.14.0.

Steps to reproduce is to use the `electronuserland/builder:wine` in some CI job:

```yml
build:desktop:
  image: electronuserland/builder:wine
  stage: deploy
  script:
    - corepack enable
    - corepack install
    - pnpm config set store-dir .pnpm-store
```

Error:
```
/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21535
  if (key == null || signature == null) throw new Error(`Cannot find matching keyid: ${JSON.stringify({ signatures, keys })}`);
```

Proposal: update Node.js v22.13.0 to latest v22.14.0 (LTS) which contains corepack 0.31.0 with the fix.

Thank you very much.
