### ISSUE TITLE
Old source version used in app.asar within pnpm, npm and yarn workspace projects

### ISSUE THREAD

**Issue by falkfrentzen** [electron-userland/electron-builder#8982]
Hello everyone, 

first of all thanks for developing this easy-to-use project! 

I came across this peculiar problem: 
electron-builder uses an old code source for the app.asar assets, when the following conditions are met: 
- the app package is in a monorepo; I tested it in different monorepos: 
   1. Turborepo based on pnpm workspace, 
   2. pnpm workspace
   3. yarn workspace
   4. npm workspace
- and the monorepo project is open in any editor (tried it with VSCode, Cursor and Atom)

I use electron-vite for scaffolding the app package and building the source into a directory called "out" in the app package's root. When starting the editor, opening the project and running the electron-builder --"target" (e.g. electron-builder --mac) command (tested mac and windows nsis) the source from out is correctly copied into the app.asar, but subsequent calls of the command result in the source from the first run being bundled to app.asar. Only after relaunching the editor does the electron-builder --"target" command work for the first try. 

![Image](https://github.com/user-attachments/assets/b1602f07-0454-4e85-9bb7-8860380f8b8c)

This is a recreation of an npm monorepo with an app package, that uses electron-builder for building the app: https://codesandbox.io/p/devbox/xq7hs8
Installing the packages seems to not work in the sandbox due to electron-builder failing, but forking it to the local environment should work. 

This is the electron-builder config yml used:

```
appId: com.electron.app
productName: electron-vite-debug
directories:
  buildResources: build
files:
  - '!**/.vscode/*'
  - '!src/*'
  - '!electron.vite.config.{js,ts,mjs,cjs}'
  - '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}'
  - '!{.env,.env.*,.npmrc,pnpm-lock.yaml}'
  - '!{tsconfig.json,tsconfig.node.json,tsconfig.web.json}'
asarUnpack:
  - resources/**
win:
  executableName: electron-vite-debug
nsis:
  artifactName: ${name}-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
mac:
  entitlementsInherit: build/entitlements.mac.plist
  extendInfo:
    - NSCameraUsageDescription: Application requests access to the device's camera.
    - NSMicrophoneUsageDescription: Application requests access to the device's microphone.
    - NSDocumentsFolderUsageDescription: Application requests access to the user's Documents folder.
    - NSDownloadsFolderUsageDescription: Application requests access to the user's Downloads folder.
  notarize: false
dmg:
  artifactName: ${name}-${version}.${ext}
linux:
  target:
    - AppImage
    - snap
    - deb
  maintainer: electronjs.org
  category: Utility
appImage:
  artifactName: ${name}-${version}.${ext}
npmRebuild: false
publish:
  provider: generic
  url: https://example.com/auto-updates
```

I'd be happy to provide further information if needed. 

Thanks in advance!
