### ISSUE TITLE
Error: Cannot find module '@electron-toolkit/utils'

### ISSUE THREAD

**Issue by roshan00123** [electron-userland/electron-builder#8986]
We have uploaded the electron app on Mac App Stores and they gave this error while reviewing.
We generate both dmg and MAS app. DMG is working fine in our setup, but MAS build the .pkg file is giving this error after launching the app.

Full error is below:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@electron-toolkit/utils'
Require stack:
- /Applications/AppName.app/Contents/Resources/app.asar/out/main/index.js
at
Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
at s._resolveFilename (node:electron/js2c/browser_init:2:114421)
at
Module._load (node:internal/modules/cjs/loader:929:27)
at c._load (node:electron/js2c/node_init:2:13672)
at Module.require (node:internal/modules/cjs/loader:1150:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Module.<anonymous> (/Applications/AppName.app/Contents/Resources/ app.asar/out/main/index.js:25:15)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
OK
```

Anyone have any idea on this? @mmaietta

**Comment by mmaietta** [comment]
>DMG is working fine in our setup

Does the `.app` within the DMG still run as expected?

**Comment by roshan00123** [comment]
> > DMG is working fine in our setup
> 
> Does the `.app` within the DMG still run as expected?

Yes, the DMG is running properly. 

This is our electron-builder.yaml file

```
appId: io.app.mac
productName: AppName
directories:
  buildResources: build
afterSign: scripts/notarize.mjs
files:
  - '!**/.vscode/*'
  - '!src/*'
  - '!electron.vite.config.{js,ts,mjs,cjs}'
  - '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}'
  - '!{.env,.env.*,.npmrc,pnpm-lock.yaml}'

asarUnpack:
  - resources/**

win:
  executableName: AppName
  extraFiles:
  - from: "publish/win"
    to: "resources/publish/win"
    filter:
      - "**/*"
nsis:
  artifactName: ${name}-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
  deleteAppDataOnUninstall: true
mac:
  target:
    - dmg
    # Enable mas while delivering the app on App Stores
    - mas
    - zip
  entitlementsInherit: build/entitlements.mac.plist
  provisioningProfile: build/antarcticaiomac.provisionprofile
  minimumSystemVersion: "12.0"
  extendInfo:
    #For CFBundleVersion error in azure pipelines
    CFBundleVersion: "0.0.20"
    CFBundleShortVersionString: "0.0.20"
    NSCameraUsageDescription: Application requests access to the device's camera.
    NSMicrophoneUsageDescription: Application requests access to the device's microphone.
    NSDocumentsFolderUsageDescription: Application requests access to the user's Documents folder.
    NSDownloadsFolderUsageDescription: Application requests access to the user's Downloads folder.
  notarize: false
  hardenedRuntime: true
  gatekeeperAssess: false
  
  entitlements: build/entitlements.mac.plist
  extraFiles:
  - from: "publish/mac/${env.NMT_FOLDER_MAC}"
    to: "resources/publish/mac"
    filter:
      - "**/*"
dmg:
  artifactName: ${name}-${version}.${ext}
pkg:
  artifactName: ${name}-${version}.${ext}

mas:
  minimumSystemVersion: "12.0"
  entitlementsInherit: build/entitlements.mas.plist
  entitlements: build/entitlements.mas.plist
  extendInfo:
    CFBundleVersion: "0.0.20"
    CFBundleShortVersionString: "0.0.20"
linux:
  target:
    - AppImage
    - snap
    - deb
  maintainer: electronjs.org
  category: Utility
appImage:
  artifactName: ${name}-${version}.${ext}
npmRebuild: false
publish:
  provider: "s3"
  bucket: static-content.antarctica.io
  acl: null
  path: ${env.RELEASE_BUCKET_PATH}
```
