### ISSUE TITLE
Help: Incorrect icon size for mac

### ISSUE THREAD

**Issue by DestroyerV** [electron-userland/electron-builder#9017]
I am packing my electron app using electron-builder for mac but the icon size is little bit larger than other apps in the launchpad and in the dock .I have used icns for my app icon.

config:
```
mac:
  icon: build/icon.icns
  entitlements: build/entitlements.mac.plist
  identity: null
  notarize: false
dmg:
  artifactName: ${name}-${version}.${ext}
```
