### ISSUE TITLE
Custom icon not showing (nsis target) after upgrading electron-builder

### ISSUE THREAD

**Issue by dmm9** [electron-userland/electron-builder#9030]
I recently upgraded electron-builder from `24.13.3` to `26.0.12`. Using to build windows/nsis target. After building and installing the app, I find some unexpected differences:
 
- The application icon is not anymore the configured icon, but the default electron icon.

- The application exe's properties shows Company: `GitHub, Inc.` and Copyright:  `Copyrigth (C) 2015, Inc. All rights reserved` and original filename: `electron.exe`, instead of the configured values.

However, the installer and uninstaller still show the configured values and icon.

Here is my config
```yaml
productName: MyApp
copyright: Copyright © 2025 MyInc
win:
  icon: resources/icons/my_icon.ico
  target:
    - nsis
  [...]
```

What has changed between both versions? Is my config not valid anymore or is it an issue?
