### ISSUE TITLE
ARM64 doesn't seem to install with nsis-web

### ISSUE THREAD

**Issue by wartab** [electron-userland/electron-builder#9131]
Hello,

I'm sorry for being unable to provide a minimal reproduction at this time (we don't have an ARM64 system in our office), but it doesn't seem like the nsis-web installer does actually download ARM64 versions. 

We use electron-builder 25.1.8.

One of our customers, who is on an ARM64 system got the following error when trying to run our installer (there were others as well):
![Image](https://github.com/user-attachments/assets/121ff7ca-5df7-4b30-8901-6d9d75cb1870)

[I saw electron-updater 6.6.4 did address something like that](https://github.com/electron-userland/electron-builder/pull/9059), but this isn't the update process that fails, but the install process.

After checking further, I can see in our Github releases using the `Refined Github` Firefox extension that the `*-arm64.nsis.7z` is NEVER downloaded. Our users are business people, not tech people, so I doubt that Windows-ARM64 has 0 users, while the .deb package is downloaded 100+ times.

![Image](https://github.com/user-attachments/assets/a380e73b-bdc2-4438-9ac6-807ce5e5c8e8)

https://github.com/horussoftware/falco3_4/releases

`latest.yaml` does contain a reference to the arm64 file:
```
version: 3.5.17
files:
  - url: InstallFalco.exe
    sha512: 4RIMXHEdiof/NnMAe8iKwzvYxdqXoYj/HGAFmeKx0h5i79zncBUDzuxGykj/qmRe9yDlviIS2Rkkg42OLtIeVw==
path: InstallFalco.exe
sha512: 4RIMXHEdiof/NnMAe8iKwzvYxdqXoYj/HGAFmeKx0h5i79zncBUDzuxGykj/qmRe9yDlviIS2Rkkg42OLtIeVw==
packages:
  x64:
    size: 103176127
    sha512: aHhNfLW2BAR3IR5NuyTHHc87KdFRYG9G1JtWG0dZnaHJk2rcIlhgHGq1POarykUEE9azRt2RKkFRC0WFYgwMwA==
    blockMapSize: 106641
    path: falco-app-3.5.17-x64.nsis.7z
    file: falco-app-3.5.17-x64.nsis.7z
  arm64:
    size: 107011475
    sha512: 0MisXHn3fY9Uo4TN6PZE3VVBGIUw3lEp0Wd7/pPMYokw84x52eVUuEoE71ixKvw8AlnuXqPQUX2CnGeimJ2jEQ==
    blockMapSize: 112533
    path: falco-app-3.5.17-arm64.nsis.7z
    file: falco-app-3.5.17-arm64.nsis.7z
releaseDate: '2025-05-09T16:56:40.640Z'
```

Is this a known issue with electron-builder 25.1.8? I wasn't able to find anything related to this. Note that we used to have 32-bit Windows releases and those were being downloaded back then.
